### ISSUE TITLE
Check fuzzing results in CI

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#1037]
In CI, we test each fuzzer by running the fuzzer with a timeout. (`cargo make test`)
This checks if the fuzzer builds and runs without any error.

We should check if the fuzzer has found any new testcases too.

**Comment by SpaceWhite** [comment]
I'm thinking what would be the correct approach here.

Since most fuzzers are using either `SimplePrintingMonitor` or `MultiMonitor`, grep the stdout should be sufficient right?

**Comment by domenukk** [comment]
Yes or checking if the out dir and objective dir are filled, alternatively
