### ISSUE TITLE
frida-asan: hook mmap in order to unpoison allocated memory

### ISSUE THREAD

**Issue by s1341** [AFLplusplus/LibAFL#105]
At the moment, if the target calls `mmap` to map memory or a file, we do not unpoison the returned memory, which will cause false ASAN errors and make the target fail to function as expected.

We need to hook `mmap` and unpoison the returned memory.

**Comment by domenukk** [comment]
So, basically replicate libqasan from qemuafl, right? 
The hooks are here:
https://github.com/AFLplusplus/AFLplusplus/blob/stable/qemu_mode/libqasan/hooks.c

**Comment by s1341** [comment]
I think you meant that comment for #104, but yes, that's pretty much it.

**Comment by s1341** [comment]
This should now be implemented.
