### ISSUE TITLE
FridaInstrumentationHelper::new should return a Result

### ISSUE THREAD

**Issue by fabianfreyer** [AFLplusplus/LibAFL#1053]
`FridaInstrumentationHelper::new` has a bunch of unwraps and expects that could instead be Results using the `try` operator.

**Comment by tokatoka** [comment]
True, Done in #1056

**Comment by tokatoka** [comment]
Sadly it didn't work

**Comment by domenukk** [comment]
guess this maybe needs #1018 (?)

**Comment by tokatoka** [comment]
I think that capstone one is about code generation (?) 

but this issue is *probably* due to frida-rust's drop() called prematurely.
