### ISSUE TITLE
Use the log crate's logging facade

### ISSUE THREAD

**Issue by fabianfreyer** [AFLplusplus/LibAFL#1055]
**Is your feature request related to a problem? Please describe.**
I'm trying to fuzz on platforms using non-stdout logging facilities, and observe LibAFL's output. When debugging issues, I want to be able to enable more verbose messages from within LibAFL and have them go to the same logging facilities.

**Describe the solution you'd like**
Please make use of the [log](https://crates.rs/crate/log) crate's logging facade. Messages that are currently printed with `println!` should probably be translated to `log::info`, while setting an appropriate `target` parameter.

e.g.:
```rust
            // We setup signal handlers to clean up shmem segments used by state restorer
            #[cfg(unix)]
            if let Err(_e) = unsafe { setup_signal_handler(&mut SHUTDOWN_SIGHANDLER_DATA) } {
                // We can live without a proper ctrl+c signal handler. Print and ignore.
                log::error!("Failed to setup signal handlers: {_e}");
            }

            let mut ctr: u64 = 0;
            // Client->parent loop
            loop {
                log::info!("Spawning next client (id {ctr})");
```

Using high-verbosity log levels such as `log::trace` would allow logging all the things, while setting sane compile_time min levels so it doesn't impact runtime performance.

Harnesses can provide their own log implementations using the facade such as [oslog](https://crates.rs/crate/oslog) on macOS/iOS or using a dedicated UART on an embedded target.

**Describe alternatives you've considered**
There's a ton of other logging facades, but the log crate seems to be the one that's most used.

**Comment by domenukk** [comment]
Duplicate with #127

**Comment by fabianfreyer** [comment]
Oh, didn't see that one, closing this then
