### ISSUE TITLE
Coverage Stats

### ISSUE THREAD

**Issue by bitterbit** [AFLplusplus/LibAFL#106]
Hi everyone! I am loving this project 🎉 

Is it possible to print coverage stats? 
And if not, is it a wanted feature or should the library users just implement it on their own?

I was thinking the best way to add support for coverage stats was to adding a field to `ClientStats` similar to `introspection_stats` but I am still learning the structure of LibAFL so I am not sure. What do you think?

**Comment by domenukk** [comment]
What exactly do you want to track? How many bits are currently set in the coverage map?
For this, one easy way could be to wrap the `MapFeedback` with your own feedback that also keeps track of the current progress. Could this roughly be what you are looking for? In case it's unclear please don't hesitate to ask further questions. :)

**Comment by bitterbit** [comment]
> one easy way could be to wrap the `MapFeedback`

I'll look into it sounds cool :) 

I was actually thinking more about how to display the stats with all other stats in `SimpleStats`. I can wrap `MapFeedback` and make it emit a new event `FeedbackEvent` which the event manager will receive and update the `Stats` field.  I guess displaying custom stats could be common case for fuzzers, maybe we could do a custom stats event that passes a KV to be printed? 

Or I could just hack a loop with a sleep to ask `MapFeedback` how many edges it collected. What would you suggest be better?

**Comment by domenukk** [comment]
Ah sorry, I get the question a bit better, now. :)
The plan is to allow custom events, however we had to comment them out at some point during refactoring. I think it should be asy to bring them back, see https://github.com/AFLplusplus/LibAFL/blob/b51936397b3ac428455a8b61d6a4f60f179bf50f/libafl/src/events/mod.rs#L127
With this, emitting your own events shoud be easy.

Thinking about it, it may also make sense to make the normal stats event take additional data, @andreafioraldi what do you think?

**Comment by andreafioraldi** [comment]
Yes is a thing that we planned, but not in our priority list ATM. If you want to implement it, don't use a CustomEvent, add a field to the Event enum as it is a common thing that users want to log.

**Comment by andreafioraldi** [comment]
Anyway, I plan a refactgor of the Stats system as now we print cumulative stats of all the clients while it is interesting to have stats from each client (the coverage stats would fall in this case) and global stats

**Comment by bitterbit** [comment]
Cool i'll look into it and update if I come up with something useful
Thanks guys

**Comment by bitterbit** [comment]
Just made a PR #107, let me know what you think

**Comment by andreafioraldi** [comment]
Hey @bitterbit can you give a look to #114 and see it if cover your usecase?

Now there are custom stats events and can be sent in this way https://github.com/AFLplusplus/LibAFL/blob/new_stats/libafl/src/feedbacks/map.rs#L302

**Comment by andreafioraldi** [comment]
The interface is now this and prints each MapFeedback using the name

![Screenshot at 2021-05-20 16-36-41](https://user-images.githubusercontent.com/16168186/118998338-a849d080-b989-11eb-985d-0ddbff7e8efc.png)

**Comment by bitterbit** [comment]
@andreafioraldi looks perfect! 💪
