### ISSUE TITLE
Path too long on windows

### ISSUE THREAD

**Issue by cokeBeer** [AFLplusplus/LibAFL#1083]
**Describe the bug**
As mentioned in https://github.com/AFLplusplus/LibAFL/issues/1059 , libafl 0.9.0 has a problem. So I tried to use a specific rev like 7ed1ac9.  However, when I ran `cargo build` on my windows 10 system, I got a new error.

**To Reproduce**
1. a rev in cargo.toml, like `libafl = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "7ed1ac9" }`
2. cargo build

**Expected behavior**
success

**Screen output/Screenshots**
![image](https://user-images.githubusercontent.com/70683161/219852338-4b664b23-33a8-4c71-9aa4-28f693b8e005.png)

**Comment by andreafioraldi** [comment]
Hey @cokeBeer , this is not a LibAFL issue, but a cargo issue https://github.com/rust-lang/cargo/issues/9770

As a workaround, you can enable long paths https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

**Comment by cokeBeer** [comment]
@andreafioraldi  I have known this before but it does not work well.
How I solve this problem in the end:
First change the reg as it mentioned in https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
Then run this in your terminal
```
git config --system core.longpaths true
```
Then everything is ok
