### ISSUE TITLE
Unintuitive interface of ForkServerExecutorBuilder

### ISSUE THREAD

**Issue by clesmian** [AFLplusplus/LibAFL#1089]
Thanks for the great work you do, it is really fun to work with LibAFL and get great results in a short time!

I'm not sure where this fits because it's not really a bug or feature request, but maybe this can save some headache for others. 

The interface of the `ForkServerExecutorBuilder` seems rather unintuitive in some places. It looks to be straightforward, but actually makes it easy to introduce hard to spot problems that are masked behind the interface.

## `parse_afl_cmdline`

For example `parse_afl_cmdline` ([src](https://github.com/AFLplusplus/LibAFL/blob/8bffd28b4c357b315acb9cecd92cbf2b734a625a/libafl/src/executors/forkserver.rs#L824)) does not really parse an AFL commandline, but only the arguments part of it. For a new user like me that lead to some confusion as I could not figure out, why the builder could not find the fuzz target and why the fuzz target ran so slow after I added the program.

Comparing to the implementation of `parse_afl_cmdline` for the `CommandExecutor` ([src](https://github.com/AFLplusplus/LibAFL/blob/53dba5f49d035006b435d7ef652cf3c7a9b0ecde/libafl/src/executors/command.rs#L255)) this is also inconsistent with other parts of LibAFL, as this version does indeed expect the fuzz target as the first argument in the command line.

One minor issue is that only the first occurrence of `@@` is replaced, even though afl-fuzz will be happy to replace multiple occurrences and it is possible to add the file to the commandline multiple times in other ways, i.e. by repeatedly using `arg_input_file_std`.

## `arg_input_file_std`
In case you use the `ForkServerExecutor` with multiple instances started in the same working directory (or by using the launcher) all instances write to the same file. This  leads to poor performance of the fuzzer, as the input to the fuzz target may not be the one the particular fuzzing instance expects. 

I'm not sure which would be the best way to go about this. Apart from just adding a caveat to the documentation, it could be beneficial to ensure uniqueness of the file used to pass the test case in some way or another. 

## Missing validation
All in all the builder is missing validation of input files i.e. it allows to specify multiple input files with different filenames, even though only the one specified last is actually written to.

In case that this is something you think is worth working on, would be happy to contribute some bits and pieces.

**Comment by domenukk** [comment]
> In case you use the ForkServerExecutor with multiple instances started in the same working directory (or by using the launcher) all instances write to the same file. This leads to poor performance of the fuzzer, as the input to the fuzz target may not be the one the particular fuzzing instance expects.

Nice find. I think we either want to randomize the filename for this use case, or use a .lafl_lock-like approach to deduplicate

> In case that this is something you think is worth working on, would be happy to contribute some bits and pieces.

We always appreciate help :)
