### ISSUE TITLE
GSoC 2023

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#1098]

**Comment by juppytt** [comment]
Hi. I'm interested in "Start rewriting AFL++'s afl-fuzz in Rust as a frontend of LibAFL" in #119.

**Comment by Srg213** [comment]
Hello. I am working on #36 and will open PR soon. I am open to work on Rust projects and would like to contribute to LibAFL

**Comment by tokatoka** [comment]
We'll select the candidates based on the contribution to the project.
So please send some PRs to contribute before you submit your GSoC proposal. 

For example, there're some easy issues marked with `good first issue` to work on. #1084 #1037 #777 #609 #424 #36

**Comment by matheusbaptistella** [comment]
Hello, I'm interested in working with issue #777. I don't have much experience with libafl_frida but it seems a great opportunity to learn new and more about the subject. Can I use that issue's discussion topic for further doubts?

**Comment by tokatoka** [comment]
yes

**Comment by shubhangi013** [comment]
Hey @tokatoka ! I am Shubhangi, an electrical engineering undergrad and a student developer from IIT BHU. I would love to contribute to AFL++. I am starting out in fuzzing and have beginner level experience in Rust. I am keen to contribute to ``Start rewriting AFL++'s afl-fuzz in Rust as a frontend of LibAFL`` . I am a quick learner and have contributed to opensource previously, particularly to security applications.

**Comment by soumya-78** [comment]
Hello @tokatoka  Soumya Ranjan here, and I am a third-year undergrad with proficiency in various tech stacks, including Rust, NodeJS, JavaScript, Python, PostgreSQL, MySQL, and C++. Currently, I am enthusiastic about contributing to the "Fuzzer template generator." project as a part of the AFL++ community. I am thrilled to be a part of this community and eager to make meaningful contributions.
As there is no github link provided there in project description can you please guide me how to set up my local environment and proceed.

**Comment by tokatoka** [comment]
Yes
Basically you are asked to build a wizard for libafl
https://en.wikipedia.org/wiki/Wizard_(software)
Your program asks the user what component of the fuzzer to use. and then later build the fuzzer rust code according to the user's preference.

Please send some PRs & contribute to libafl beforehand if you want to participate.

**Comment by soumya-78** [comment]
Thanks for replying @tokatoka . So i have to set up my local environment for libafl and solve some issues to proceed further. Can you please help me by mentioning some good issues which are still open to get familier with the codebase.

**Comment by tokatoka** [comment]
any issue with good first issue tag
but some people already pushed pr for some of them

if you can fix #701 then it's really helpful for us

**Comment by soumya-78** [comment]
Can you please confirm are there any pr pushed for any of the issue #1084 #609 and #424 . As they are marked as good first issue i will try to solve them and add a pr.

**Comment by tokatoka** [comment]
#1084 is done

**Comment by soumya-78** [comment]
The other 2 are still open along with #701?

**Comment by s1341** [comment]
Note that ideally the wizard shouldn’t ask which components to use, but rather what kind of fuzzing the user is intending to do, and then suggest components/modes/capabilities that match.

**Comment by tokatoka** [comment]
> The other 2 are still open along with https://github.com/AFLplusplus/LibAFL/issues/701?

yeah

you can work on any open issue (not necessarily good first issue)

**Comment by soumya-78** [comment]
Hello @tokatoka Actually when following the contributing guide and running the "cargo build --release" command i am finding error and resolve it out. Can you please help me with it
My llvm version is 14.0.6 
![Screenshot from 2023-03-10 22-43-36](https://user-images.githubusercontent.com/81842974/224380303-8c39af6d-2657-4525-b80a-5ee3293b780e.png)

**Comment by tokatoka** [comment]
do you have llvm-config

**Comment by soumya-78** [comment]
Yes version 14.0.6 
![Screenshot from 2023-03-10 22-50-45](https://user-images.githubusercontent.com/81842974/224381419-e9981bc1-3377-42cf-bff6-be2d0702b349.png)

**Comment by tokatoka** [comment]
can you try things on this issue?
https://github.com/AFLplusplus/LibAFL/issues/1070

- Run with RUST_BACKTRACE=full
- check stderr file in /target/release

**Comment by shubhangi013** [comment]
Hey @tokatoka are there any good first issues left? I would love to contribute to AFL :))

**Comment by tokatoka** [comment]
there're some issues with "good first issue" or "enhancement" that you can work on

**Comment by soumya-78** [comment]
Hello @tokatoka After making certain changes in code mentioned in that issue 
![Screenshot from 2023-03-11 18-01-24](https://user-images.githubusercontent.com/81842974/224484620-95e0d526-d259-4608-be1d-7bc1850b8f04.png)
there is no error in build but several warnings
![Screenshot from 2023-03-11 17-56-55](https://user-images.githubusercontent.com/81842974/224484653-cfc2285c-1dee-4f19-8560-7983db96b38a.png)

and this error still exist in code showing 
![Screenshot from 2023-03-11 18-04-40](https://user-images.githubusercontent.com/81842974/224484856-e9c47800-82f5-40ff-8f63-2ae0f6a3cd08.png)

can you please guide me what to do?

**Comment by tokatoka** [comment]
are you on windows? or linux?

**Comment by soumya-78** [comment]
I am in linux

**Comment by tokatoka** [comment]
Ok

> here is no error in build but several warnings

Where does these 4 warnings come from?
Are they from println!("cargo:warning={:#?}", r)?
(but then it is guarded with cfg!(windows) so that means you are on windows)

are you on mingw or something?

**Comment by soumya-78** [comment]
Actually i have dual booted with windows but currently i am in ubuntu linux.

**Comment by tokatoka** [comment]
ah ok.
then it doesn't matter.

so I'm sure 
```
println!("cargo:warning={:#?}", r)? 
```
is printing out file XXX is missing. can you find out what is missing in your case?

**Comment by soumya-78** [comment]
Yes the warning come from println!("cargo:warning={:#?}", r)

**Comment by tokatoka** [comment]
> Actually i have dual booted with windows but currently i am in ubuntu linux.

wait.. that's odd. 

because you're running code that is only supposed to run if you are on windows.
https://github.com/AFLplusplus/LibAFL/blob/main/libafl_cc/build.rs#L151
it's guarded with cfg!(windows) so it'll never run on linux host

**Comment by soumya-78** [comment]
Yes clang-cl is not available.

**Comment by tokatoka** [comment]
can you show the result of `rustc -vV`

**Comment by soumya-78** [comment]
yes 
![Screenshot from 2023-03-11 19-17-01](https://user-images.githubusercontent.com/81842974/224488283-a9adeef1-d881-4bf1-86af-039b6924885b.png)

**Comment by tokatoka** [comment]
hmm
I don't know.. cargo is running the build code for windows when your rustc is for linux..

**Comment by soumya-78** [comment]
Actually in if the condition is for unix so it is running for linux. and in else it is for windows 
![Screenshot from 2023-03-11 19-15-39](https://user-images.githubusercontent.com/81842974/224488540-b9dd0657-81f4-4960-91d2-8f615a1a674e.png)

**Comment by tokatoka** [comment]
ok that code is for windows can you revert that change and see what file is missing in your case?
you can just the same as windows, println! the result of command::new() but this time for linux

**Comment by soumya-78** [comment]
And when i run cargo build --release code it is only showing 4 warning err messages. not specifically showing due to missing of which files these errors are occurring

**Comment by soumya-78** [comment]
if i modify the code in windows 
![Screenshot from 2023-03-11 19-31-03](https://user-images.githubusercontent.com/81842974/224488986-ffe2fcdb-b316-40b8-a68e-071ee628d350.png)
then i am getting the error as it is coming previously 
![Screenshot from 2023-03-11 19-30-29](https://user-images.githubusercontent.com/81842974/224489012-82d0a813-1ee9-4608-9291-72b35b1d9bd3.png)

**Comment by tokatoka** [comment]
yeah I mean If you want to insert debug prints, you have to do it in
```if cfg!(unix)```

do you have clang++ installed?

**Comment by soumya-78** [comment]
No clang++ is not installed

**Comment by tokatoka** [comment]
well, you have to install it to get it working

**Comment by soumya-78** [comment]
After installing clang++ I have to build the code again?

**Comment by tokatoka** [comment]
yeah

**Comment by soumya-78** [comment]
But finding same error again at the time of building. I tried to restart my pc also but facing the same problem

**Comment by tokatoka** [comment]
you need to find out what what file is missing from your system to make it work

**Comment by soumya-78** [comment]
Yes some header files are not present
as 
![Screenshot from 2023-03-11 20-04-59](https://user-images.githubusercontent.com/81842974/224490515-6119b5b6-ada2-4f90-9f7a-6032073cf0d9.png)
these error are user defined headers. the red line coming becuse there is error and the error is basically 
![Screenshot from 2023-03-11 20-06-24](https://user-images.githubusercontent.com/81842974/224490581-f372917f-dd3b-4ed9-b812-6f3347332231.png)

**Comment by soumya-78** [comment]
Is there any specific version of llvm required? i have installed 14.0.6

**Comment by tokatoka** [comment]
no anything between 11 and 15 should work
can you check this
https://github.com/AFLplusplus/LibAFL/issues/1070#issuecomment-1430250833

**Comment by soumya-78** [comment]
Actually i am also facing the same issue there is no stderr file exist in libfl_cc-xxx
![Screenshot from 2023-03-11 21-30-42](https://user-images.githubusercontent.com/81842974/224494682-7756cf5b-dd79-4b08-a52e-a9f2b09cd6b8.png)

**Comment by soumya-78** [comment]
@tokatoka i have corrected the include header erro but still facing the issue what should i do?
![Screenshot from 2023-03-11 22-47-40](https://user-images.githubusercontent.com/81842974/224502572-304cf111-ff6d-48ed-9b88-d31fc9f11d21.png)

**Comment by tokatoka** [comment]
You can send us the draft gsoc proposal to gsoc@aflplus.plus beforehand so we can take a look

**Comment by RougherO** [comment]
Hey @tokatoka  I am interested to work on AFL-style UI in #119. I am a beginner in rust and I have prior experience in TUI with python. I would really like to work on this to build my rust skills. Could you help me in providing some documentation and resources so that I could get up to speed.

Thanks in advance

**Comment by fbaltor** [comment]
Hey, @tokatoka and @soumya-78. I guess I found the solution. I was facing the same issue here, in my Ubuntu 22.04.

First, the outputs of `RUST_BACKTRACE=full cargo build --release`:

```
   Compiling libc v0.2.140
   Compiling proc-macro2 v1.0.52
   Compiling unicode-ident v1.0.8
   Compiling quote v1.0.26
   Compiling autocfg v1.1.0
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.158
   Compiling serde v1.0.158
   Compiling syn v1.0.109
   Compiling log v0.4.17
   Compiling scopeguard v1.1.0
   Compiling semver v1.0.17
   Compiling lock_api v0.4.9
   Compiling signal-hook v0.3.15
   Compiling smallvec v1.10.0
   Compiling parking_lot_core v0.9.7
   Compiling memchr v2.5.0
   Compiling bitflags v1.3.2
   Compiling version_check v0.9.4
   Compiling rustc_version v0.4.0
   Compiling syn v2.0.4
   Compiling rustversion v1.0.12
   Compiling ahash v0.8.3
   Compiling heapless v0.7.16
   Compiling jobserver v0.1.26
   Compiling signal-hook-registry v1.4.1
   Compiling mio v0.8.6
   Compiling cc v1.0.79
   Compiling parking_lot v0.12.1
   Compiling signal-hook-mio v0.2.3
   Compiling memoffset v0.7.1
   Compiling byteorder v1.4.3
   Compiling hash32 v0.2.1
   Compiling spin v0.9.6
   Compiling num-traits v0.2.15
   Compiling stable_deref_trait v1.2.0
   Compiling libm v0.2.6
   Compiling either v1.8.1
   Compiling gimli v0.27.2
   Compiling adler v1.0.2
   Compiling once_cell v1.17.1
   Compiling serde_json v1.0.94
   Compiling erased-serde v0.3.25
   Compiling backtrace v0.3.67
   Compiling libafl v0.9.0 (/home/fbaltor/LibAFL/libafl)
   Compiling miniz_oxide v0.6.2
   Compiling which v4.4.0
   Compiling crossterm v0.25.0
   Compiling getrandom v0.2.8
   Compiling object v0.30.3
   Compiling aho-corasick v0.7.20
   Compiling itoa v1.0.6
   Compiling regex-syntax v0.6.29
   Compiling cobs v0.2.3
   Compiling addr2line v0.19.0
   Compiling rustc-demangle v0.1.21
   Compiling unicode-segmentation v1.10.1
   Compiling unicode-width v0.1.10
   Compiling cassowary v0.3.0
   Compiling ryu v1.0.13
   Compiling pin-utils v0.1.0
   Compiling static_assertions v1.1.0
   Compiling match_cfg v0.1.0
   Compiling hostname v0.3.1
   Compiling nix v0.26.2
   Compiling tui v0.19.0
   Compiling regex v1.7.2
   Compiling num_enum_derive v0.5.11
   Compiling c2rust-bitfields-derive v0.17.0
   Compiling c2rust-bitfields v0.17.0
   Compiling typed-builder v0.12.0
   Compiling ctor v0.1.26
   Compiling num_enum v0.5.11
   Compiling libafl_derive v0.9.0 (/home/fbaltor/LibAFL/libafl_derive)
   Compiling libafl_cc v0.9.0 (/home/fbaltor/LibAFL/libafl_cc)
   Compiling libafl_targets v0.9.0 (/home/fbaltor/LibAFL/libafl_targets)
   Compiling crossterm v0.26.1
   Compiling wait-timeout v0.2.0
   Compiling uds v0.2.6
   Compiling tuple_list v0.1.3
   Compiling rand_core v0.6.4
   Compiling xxhash-rust v0.8.6
   Compiling rangemap v1.3.0
   Compiling intervaltree v0.2.7
error: failed to run custom build command for `libafl_cc v0.9.0 (/home/fbaltor/LibAFL/libafl_cc)`

Caused by:
  process didn't exit successfully: `/home/fbaltor/LibAFL/target/release/build/libafl_cc-a075cbaa423d57d2/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_CONFIG
  cargo:rerun-if-env-changed=LIBAFL_EDGES_MAP_SIZE
  cargo:rerun-if-env-changed=LIBAFL_ACCOUNTING_MAP_SIZE
  cargo:rerun-if-changed=src/common-llvm.h
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/cmplog-routines-pass.cc

  --- stderr
  Ubuntu clang version 14.0.6
  Target: x86_64-pc-linux-gnu
  Thread model: posix
  InstalledDir: /usr/lib/llvm-14/bin
  Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
  Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
  Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
  Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
  Candidate multilib: .;@m64
  Selected multilib: .;@m64
   "/usr/lib/llvm-14/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name cmplog-routines-pass.cc -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/fbaltor/LibAFL/libafl_cc -resource-dir /usr/lib/llvm-14/lib/clang/14.0.6 -I /usr/lib/llvm-14/include -D _GNU_SOURCE -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -D LIBAFL_EDGES_MAP_SIZE=65536 -D LIBAFL_ACCOUNTING_MAP_SIZE=65536 -D USE_NEW_PM -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++ -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/x86_64-linux-gnu -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/backward -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.6/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++14 -fdeprecated-macro -fdebug-compilation-dir=/home/fbaltor/LibAFL/libafl_cc -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/cmplog-routines-pass-7d9665.o -x c++ src/cmplog-routines-pass.cc
  clang -cc1 version 14.0.6 based upon LLVM 14.0.6 default target x86_64-pc-linux-gnu
  ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/x86_64-linux-gnu"
  ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/backward"
  ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include"
  ignoring nonexistent directory "/include"
  #include "..." search starts here:
  #include <...> search starts here:
   /usr/lib/llvm-14/include
   /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++
   /usr/lib/llvm-14/lib/clang/14.0.6/include
   /usr/local/include
   /usr/include/x86_64-linux-gnu
   /usr/include
  End of search list.
  src/cmplog-routines-pass.cc:25:10: fatal error: 'list' file not found
  #include <list>
           ^~~~~~
  1 error generated.
  thread 'main' panicked at 'assertion failed: Command::new(bindir_path.join(\"clang++\")).arg(\"-v\").args(cxxflags).arg(src_dir.join(src_file)).args(ldflags).arg(\"-o\").arg(out_dir.join(format!(\"{src_stub}.{}\",\n                        dll_extension()))).status().unwrap_or_else(|_|\n            panic!(\"Failed to compile {src_file}\")).success()', libafl_cc/build.rs:141:9
  stack backtrace:
     0:     0x556fc7de2e9a - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x556fc7de2e9a - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x556fc7de2e9a - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x556fc7de2e9a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x556fc7e03bbe - core::fmt::write::h93e2f5923c7eca08
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
     5:     0x556fc7ddf755 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
     6:     0x556fc7de2c65 - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x556fc7de2c65 - std::sys_common::backtrace::print::hcb5e6388b9235f41
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x556fc7de466f - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
     9:     0x556fc7de43ab - std::panicking::default_hook::h68fa2ba3c3c6c12f
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
    10:     0x556fc7de4d79 - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
    11:     0x556fc7de4ad2 - std::panicking::begin_panic_handler::{{closure}}::hf33414f5dabf6faf
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:577:13
    12:     0x556fc7de334c - std::sys_common::backtrace::__rust_end_short_backtrace::hc50389427413bb75
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
    13:     0x556fc7de4822 - rust_begin_unwind
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
    14:     0x556fc7d3c5b3 - core::panicking::panic_fmt::h2de7a7938f816de8
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
    15:     0x556fc7d3c64d - core::panicking::panic::h90931f06a97cc5e0
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:114:5
    16:     0x556fc7d43646 - build_script_build::build_pass::h038a39017ec22bd4
                                 at /home/fbaltor/LibAFL/libafl_cc/build.rs:141:9
    17:     0x556fc7d447a0 - build_script_build::main::h3bedf4bd3023a848
                                 at /home/fbaltor/LibAFL/libafl_cc/build.rs:321:9
    18:     0x556fc7d45b1b - core::ops::function::FnOnce::call_once::h6f230d6188b1f9c8
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
    19:     0x556fc7d4712e - std::sys_common::backtrace::__rust_begin_short_backtrace::hcf86b6f85543a62c
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:121:18
    20:     0x556fc7d469f1 - std::rt::lang_start::{{closure}}::he9a02485adbf00ab
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:166:18
    21:     0x556fc7ddbb0c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h699977d052768608
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:287:13
    22:     0x556fc7ddbb0c - std::panicking::try::do_call::h4e121e623c70f903
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
    23:     0x556fc7ddbb0c - std::panicking::try::hf9d919e062bc178a
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
    24:     0x556fc7ddbb0c - std::panic::catch_unwind::h7a7b12272684cb97
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
    25:     0x556fc7ddbb0c - std::rt::lang_start_internal::{{closure}}::hd96b0eb4844b8762
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:48
    26:     0x556fc7ddbb0c - std::panicking::try::do_call::h1af1f88f4f92a22c
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:483:40
    27:     0x556fc7ddbb0c - std::panicking::try::hf20d7abea7f0f097
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:447:19
    28:     0x556fc7ddbb0c - std::panic::catch_unwind::hb0e084c3a9c042e4
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panic.rs:140:14
    29:     0x556fc7ddbb0c - std::rt::lang_start_internal::hca9d5c7277f5b67c
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:148:20
    30:     0x556fc7d469ca - std::rt::lang_start::h473741ce03f07b13
                                 at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/rt.rs:165:17
    31:     0x556fc7d44a1e - main
    32:     0x7f2324c29d90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    33:     0x7f2324c29e40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    34:     0x556fc7d3cb35 - _start
    35:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
```

From this output I concluded the problem was in this command:

**Comment by tokatoka** [comment]
Probably you don't have libstdc++

**Comment by tokatoka** [comment]
@RougherO 
in addition to Rust, you can take a look at https://lcamtuf.coredump.cx/afl/technical_details.txt to get familiar with how fuzzing works

**Comment by fbaltor** [comment]
Yes. My great skills in editing big markdown files made me publish a incomplete answer hehe I choose to edit it instead.

**Comment by RougherO** [comment]
> @RougherO in addition to Rust, you can take a look at https://lcamtuf.coredump.cx/afl/technical_details.txt to get familiar with how fuzzing works

The text is a little difficult to understand, although I understood more or less of how its working it would be great if you could provide something which is a little more easier perhaps some examples would make it clear... Thanks

**Comment by matheusbaptistella** [comment]
> You can send us the draft gsoc proposal to [gsoc@aflplus.plus](mailto:gsoc@aflplus.plus) beforehand so we can take a look

Hello tokatoka, last Wednesday I sent my gsoc proposal draft to gsoc@aflplus.plus. Do I have to send it somewhere else? Because I don't know if you guys received or are still analysing it hahahahaha.

**Comment by tokatoka** [comment]
Sorry for being late
Yes we had discussion about it, and I sent the feedback to you now.

**Comment by ToSeven** [comment]
My contribution @tokatoka https://github.com/AFLplusplus/LibAFL/pull/1195
