### ISSUE TITLE
Macro to access State and Testcase metadata

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#1113]
Atm accessing metadata is quite some code, e.g.

```rust
let meta = state.corpus().get(id)?.borrow().metadata().get::<FooTestcaseMetadata>().ok_or_else(|| {
    Error::key_not_found("FooTestcaseMetadata not found".to_string())
})?;
```

we should create macros to do that and clean the code

**Comment by matheusbaptistella** [comment]
Hello, I've been checking the State.rs and Testcase.rs files, and also going through some references on how to implement macros in Rust. I understand that:

- Both structs, StdState and Testcase, have fields metadata with type SerdeAnyMap, whereras StdState has also a named_metadata field of type NamedSerdeAnyMap.
- They have implementations of HasMetadata with methods to get the metadata.
- The structure of the statements that get the metadata are usually composed by the module name, the metadata method, the get method specifying some type (I'm not sure what `get::<FooTestcaseMetadata>()` means) and some error checker, like in:

```
let meta = state
            .metadata()
            .get::<NautilusChunksMetadata>()
            .expect("NautilusChunksMetadata not in the state")
```

So, the idea would be to create macros that can substitue all that code and be somewhat generic? Could it look like this:

```
let meta = state_metadata!["FooTestCaseMetadata"];
let meta2 = state_named_metadata!["NautilusChunksMetadata"];
```

**Comment by andreafioraldi** [comment]
Hi, yes something like that

**Comment by matheusbaptistella** [comment]
So, I've been going through the cases where metadata is accessed (throughout the repository) and I could identify some common ways in which it is done, like on some `if` conditionals:

```
if state
    .metadata()
    .get::<Tokens>()
    .is_none() { ... }
```
or mutably and using unwrap:
```
let meta = state
    .metadata_mut()
    .get_mut::<ProbabilityMetadata>()
    .unwrap();
```
or like the one you used as example, but withou the "beggining":
```
let meta = state
    .metadata_mut()
    .get_mut::<EcoMetadata>()
    .ok_or_else(|| { Error::key_not_found("EcoMetadata not found".to_string())
})?;

I wanted to ask if just the case in which it is more verbose (when it uses `ok_or_else` due to the errror message) it is necessary to use the macro?

**Comment by matheusbaptistella** [comment]
Hi, I would like to have some feedback from what i've implemented so far, should I open a PR? I don't know if the macro is defined in the correct location, nor if it's already the way you wanted but if there are any mistakes I would gladly correct them!

**Comment by tokatoka** [comment]
you can open a pr at any time. then we can see

**Comment by tokatoka** [comment]
#1123
