### ISSUE TITLE
Corpora which store on-disk: permit skipping the generation of .lafl_lock files + duplicates with postfix

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#1129]
In many scenarios, it is not necessary to create/check `.lafl_lock` nor to duplicate files (in the form `<hash>-<number>`). We should allow users to disable this functionality.

**Comment by bkrl** [comment]
What would be the best way to add this option to the API? Adding a new argument to the constructors would have to be a breaking change since Rust doesn't have default arguments yet, and adding new constructors doesn't seem to be ideal since there are already three for `InMemoryOnDiskCorpus`.

**Comment by domenukk** [comment]
> What would be the best way to add this option to the API? Adding a new argument to the constructors would have to be a breaking change since Rust doesn't have default arguments yet, and adding new constructors doesn't seem to be ideal since there are already three for `InMemoryOnDiskCorpus`.

Sorry, missed that comment.
It might be useful to add a builder at some point, or simply make it a setting on the corpus after creation

**Comment by addisoncrump** [comment]
Implemented by #981.
