### ISSUE TITLE
How to move bytes out of a BytesInput?

### ISSUE THREAD

**Issue by wtdcode** [AFLplusplus/LibAFL#1134]
I'm trying to build a mutator that consists of many libafl mutators, which is pretty similar to what `StdScheduledMutator` does. But I'm trying to split the input to several short `vec<u8>`, applying mutations on each of them and putting them together (imagine apply mutations on all function arguments one by one).

Since I need to store some metadata along with such mutated inputs, I will prefer to take ownership of the `BytesInput` by moving out the inner `bytes` but looks like `BytesInpu` doesn't allow this. I know that it could be achieved by writing my own "BytesInput" or borrowing the content but I wonder why it's not allowed?

**Comment by domenukk** [comment]
I don't fully understand why you want to move out of the input, I would try to apply mutations to a subset of an input, so on a slice (?)

**Comment by wtdcode** [comment]
> I don't fully understand why you want to move out of the input, I would try to apply mutations to a subset of an input, so on a slice (?)

Unfortunately it's impossible because the bytes layout could change (imagine inserting new elements to an array in place)
