### ISSUE TITLE
[Docs] the link should direct to the mdBook website 

### ISSUE THREAD

**Issue by shubhangi013** [AFLplusplus/LibAFL#1137]
**Is your feature request related to a problem? Please describe.**
The link in [Getting started](https://github.com/AFLplusplus/LibAFL#getting-started)  that tells us about ``Browse the LibAFL book (WIP!) with (requires [mdbook](https://github.com/rust-lang/mdBook))`` , has link to mdBooks repository

**Describe the solution you'd like**
It should redirect to https://rust-lang.github.io/mdBook/index.html

**Describe alternatives you've considered**

**Additional context**

**Comment by shubhangi013** [comment]
I can work on this easily.

**Comment by soumya-78** [comment]
Can you please explain what you are trying to solve through this issue @shubhangi013 ?
Like what i encounter after installing mdbook through `cargo install mdbook` if we run the command `cd docs && mdbook serve` then the mdBook documentation will open in localhost port.

**Comment by domenukk** [comment]
I don't have a strong preference if we link to their book or github. Worst case ppl can google :) But feel free to open a PR if you prefer to update the link of course
