### ISSUE TITLE
Endless calibration if a corpus timeout

### ISSUE THREAD

**Issue by zeyugao** [AFLplusplus/LibAFL#1146]
**Describe the bug**

In [calibrate.rs#172](https://github.com/AFLplusplus/LibAFL/blob/6c98945fc368e6ddea0ecfed9fea56cc6774470d/libafl/src/stages/calibrate.rs#L172) , if a corpus timeout, `exit_kind` will be not ExitKind::Ok, but the variable `i` won't increase and it will result in an endless calibration.

This can happen when an initial seed is already a timeout.

In aflpp, if the calibration failed, it will [abandon this entry](https://github.com/AFLplusplus/AFLplusplus/blob/2ff0ff7a903c57f9df5ed1e97370c187ec45a31e/src/afl-fuzz-one.c#L483).

But in LibAFL, it seems that we cannot abort from one of the stages without stopping the whole fuzzing process.

**Comment by tokatoka** [comment]
> but the variable i won't increase and it will result in an endless calibration.

Nice catch!

> But in LibAFL, it seems that we cannot abort from one of the stages without stopping the whole fuzzing process.

Yes, because then later stages like powerschedule stage will panic.
If you abort in the middle of the calibration you don't get the necessary metadata attached to the testcase.

So I guess the solution here is just to remove this `continue`

**Comment by zeyugao** [comment]
> So I guess the solution here is just to remove this `continue`

Should we adopt the `cal_failed` in AFL++ to stop fuzzing this corpus instead of simply removing the `continue`?

The testcases generated by this corpus will likely result in timeout, which will incur about `iterations` * 1.5s's useless fuzzing (in fuzzbench for example), of course including the CmpLog stage.

We can return Err here and add a `match` [here](https://github.com/AFLplusplus/LibAFL/blob/6c98945fc368e6ddea0ecfed9fea56cc6774470d/libafl/src/fuzzer/mod.rs#L576) or [here](https://github.com/AFLplusplus/LibAFL/blob/6c98945fc368e6ddea0ecfed9fea56cc6774470d/libafl/src/stages/mod.rs#L144) to print the err and continue fuzz other corpus, instead of directly return Err to parent. Cause it is not a unrecoverable error.

**Comment by tokatoka** [comment]
I think the problem here is that any corpus entry that takes too long to execute, or already crashes should not go to the corpus.

Do you have timeout feedback?
If you have it, then any testcase that takes too long does not go to corpus, but they go to objectives instead.

**Comment by tokatoka** [comment]
> The testcases generated by this corpus will likely result in timeout, which will incur about iterations * 1.5s's useless fuzzing (in fuzzbench for example), of course including the CmpLog stage.

Yes but aborting during calibration does not help. Because it still remains in the corpus. So your corpus should not have take in these testcases.

**Comment by zeyugao** [comment]
> Do you have timeout feedback?

No. I am using fuzzbench_forkserver as a template. So it seems that it is missing in it. This applys to the fuzzbench related fuzzers too.

https://github.com/AFLplusplus/LibAFL/blob/6c98945fc368e6ddea0ecfed9fea56cc6774470d/fuzzers/fuzzbench_forkserver/src/main.rs#L268

**Comment by tokatoka** [comment]
Open this again if you have further question :D
