### ISSUE TITLE
Any reason StdMapObserver has to take a static map?

### ISSUE THREAD

**Issue by wtdcode** [AFLplusplus/LibAFL#1180]
```rust
#[derive(Clone, Serialize, Deserialize, Debug)]
#[serde(bound = "T: serde::de::DeserializeOwned")]
#[allow(clippy::unsafe_derive_deserialize)]
pub struct StdMapObserver<'a, T, const DIFFERENTIAL: bool>
where
    T: Default + Copy + 'static + Serialize,
{
    map: OwnedMutSlice<'a, T>,
    initial: T,
    name: String,
}

```

I doubt why `'static` is required for T here?

**Comment by domenukk** [comment]
CC @andreafioraldi 
I _think_ it might be enough to be `'a` here?

**Comment by andreafioraldi** [comment]
no, deserializeowned requires 'static

**Comment by andreafioraldi** [comment]
> > no, deserializeowned requires 'static
> 
> @andreafioraldi Reading from https://serde.rs/lifetimes.html , I assume using `'static` everywhere is not correct pattern?

That's true for the struct, but StdMapObserver can take non static maps (https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/observers/map.rs#L544) it is just the type inside the map that must be 'static (integers are in the case of an AFL-like map).

Btw try to remove 'static and see what happens.

**Comment by domenukk** [comment]
Please reopen if there are further questions or suggestions :)
