### ISSUE TITLE
Failed to run baby_fuzzer_nautilus.

### ISSUE THREAD

**Issue by s1awwhy** [AFLplusplus/LibAFL#1187]
I run  cargo run command in the LibAFL/fuzzers/baby_fuzzer_nautilus folder and this error occurs:
......
   Compiling c2rust-bitfields v0.17.0
   Compiling libm v0.2.6
   Compiling libafl v0.9.0 (/root/LibAFL/libafl)
error: failed to run custom build command for `libafl v0.9.0 (/root/LibAFL/libafl)`

Caused by:
  process didn't exit successfully: `/root/LibAFL/fuzzers/baby_fuzzer_nautilus/target/debug/build/libafl-a67174a760744ed6/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'The 'nautilus' feature of libafl requires a nightly compiler', /root/LibAFL/libafl/build.rs:10:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

Is it because some of my dependencies are not installed properly? Or because some reason of `/root/LibAFL/fuzzers/baby_fuzzer_nautilus/target/debug/build/libafl-a67174a760744ed6/build-script-build`?

**Comment by tokatoka** [comment]
as the message says
you need nightly compiler https://rust-lang.github.io/rustup/concepts/channels.html

**Comment by s1awwhy** [comment]
> as the message says you need nightly compiler https://rust-lang.github.io/rustup/concepts/channels.html

OK, thanks!!
