### ISSUE TITLE
Lifetime parameters for Executor trait

### ISSUE THREAD

**Issue by wtdcode** [AFLplusplus/LibAFL#1190]
**Is your feature request related to a problem? Please describe.**
I'm implementing `Executor` and `Input` for my custom structs, however, I'm stuck at one problem: I have a wrapper, say `MyInputView` for the actual struct `MyInput` by taking an immutable reference. Therefore, I get `MyInputView<'a, T: Input>` where `'a` denotes the lifetime of the reference of the `MyInput`.

I also need some metadata stored along with my executor struct and I need to call some functions like:

```rust
fn execute(input_wrapper: &'a mut MyInputWrapper<'b>, metadata: &'a mut SomeMetadata);

// Call it in run_target like
execute(&mut input_wrapper, &mut self.metadata);
// Again note lifetime here
//           |                       |
//   'a (from impl<'a>)      'b (from &self)
```

So far so good, yes? But when I'm faced with `Executor` trait:

```rust
pub trait Executor<EM, Z>: UsesState + Debug
where
    EM: UsesState<State = Self::State>,
    Z: UsesState<State = Self::State>,
{
    /// Instruct the target about the input and run
    fn run_target(
        &mut self,
        fuzzer: &mut Z,
        state: &mut Self::State,
        mgr: &mut EM,
        input: &Self::Input,
    ) -> Result<ExitKind, Error>;
}
```

The compiler complains about `input` may not live longer than `metadata` because from the signature, it infers that `input` lives as long as other references like `self` and `input`. However, this is probably overestimated and thus I propose to add a generic type argument for `input`. In this case, we have a chance to argue about the lifetime of `input` like `'a: 'b`.

Note, if I change ` input: &Self::Input` to ` input: &'a Self::Input` without changing the signature of `Executor`, the compiler will complain about mismatched function signatures.

Also sorry I can't give the full code because it's a bit too complex for problems here. Therefore I also attached a minimal reproduction at the end. If you have any difficulty understanding the context, just check the reproduction sample.

**Describe the solution you'd like**

```rust
pub trait Executor<'a, EM, Z>: UsesState + Debug // Note 'a here
where
    EM: UsesState<State = Self::State>,
    Z: UsesState<State = Self::State>,
{
    /// Instruct the target about the input and run
    fn run_target(
        &mut self,
        fuzzer: &mut Z,
        state: &mut Self::State,
        mgr: &mut EM,
        input: &'a Self::Input, // The minimal change is to add lifetime parameter for input, but adding more is also good I think
    ) -> Result<ExitKind, Error>;
}
```

Adding this allows users to reason about the lifetime of `input`.

**Describe alternatives you've considered**
At this moment, my solution is:

```rust
    fn run_target<'b>(
        &'b mut self,
        fuzzer: &'b mut Z,
        state: &'b mut Self::State,
        mgr: &'b mut EM,
        input: &'b Self::Input,
    ) -> Result<ExitKind, libafl::Error> {
        let input = unsafe { std::mem::transmute::<&'b Self::Input, &'a Self::Input>(input) };
}
```

Thankfully we have unsafe rust but I'm not 100% confident it will introduce any UB or not.

Note `'b` here is exactly the anonymous lifetime parameter saying `input` and `state` shares the same lifetime, which is probably overestimated in most cases.

**Additional context**
I tried the approach above but it will introduce a lot of change so I'm asking here if it's appropriate. If so I could submit a PR.

I could also give a minimal reproduction code:

```rust
trait MyTrait { // Imagine this is Executor trait
    fn my_method(&self, other: &mut i32) -> bool; // And this is run_target methods
}

struct MyStruct<'a> {
    data: &'a i32,
}

impl<'a> MyTrait for MyStruct<'a> {
    fn my_method(&self, other: &mut i32) -> bool // Image other is input
    {
        // How can I specify the lifetime of `other` equals to 'a?
        true
    }
}
```

Some fact from chatgpt: It's impossible to achieve the goal without changing signatures of `MyTrait`.

**Comment by domenukk** [comment]
Sounds like it makes sense but it also changes the API/makes it a bit more complex, right?

**Comment by domenukk** [comment]
Do you feel like opening a PR so we can see this in action?

**Comment by wtdcode** [comment]
> Sounds like it makes sense but it also changes the API/makes it a bit more complex, right?

Yes correct.


> Do you feel like opening a PR so we can see this in action?

After some deep thinking, I give up the idea of storing a reference. Instead, I clone the input and moving between my internal structures, which eases the pain of binding the lifetime to any `libafl` structures, though inevitably causing some performance penalty.

Speaking of the API design, the changes are really huge so it could not be easily done and I think doing an extra copy is a good tradeoff between efficiency and robust. So I will close this temporarily until I found some time to re-think everything together...
