### ISSUE TITLE
The "alternative architecture" mentioned in the LibAFL's paper

### ISSUE THREAD

**Issue by r4ve1** [AFLplusplus/LibAFL#1194]
I'm currently learning about LibAFL and I have a question about the architecture described in its paper. In the following line (marked in yellow), the paper mentions an "alternative architecture" implemented in LibAFL, which consists of a pipeline without any executor and can be used as a service:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/59314380/229354000-13d970f2-cd9b-425e-b183-68fe73b67077.png">

Are there any available examples or further explanations? Thanks.

**Comment by andreafioraldi** [comment]
https://github.com/AFLplusplus/LibAFL/blob/main/fuzzers/push_stage_harness/src/main.rs#L108

**Comment by r4ve1** [comment]
Thanks! I'll close this issue.
