### ISSUE TITLE
Access to `CPU` in QEMU syscall hooks

### ISSUE THREAD

**Issue by langston-barrett** [AFLplusplus/LibAFL#1202]
**Is your feature request related to a problem? Please describe.**
I'd like to write a fuzzer using QEMU user-mode that uses the exit code of the emulated process to decide whether or not the input was interesting. One way to do this would be to hook the `exit` system call, record the argument, and then jump to a predefined breakpoint, at which point control is returned from `emu.run()` to the harness, which can inspect the exit code and decide on an `ExitKind`. The problem is that I can't see how to jump to the breakpoint from inside a syscall hook.

I think the proposed solution would also be useful for a lot of other use-cases, e.g., inspecting memory from a syscall hook.

**Describe the solution you'd like**
At the spot at which the hooks are called:

https://github.com/AFLplusplus/qemu-libafl-bridge/blob/0dc52ed6f3915f727aaec8648706760f278f0571/linux-user/syscall.c#L13432

it looks like there's easy access to a `CPUState *`:

https://github.com/AFLplusplus/qemu-libafl-bridge/blob/0dc52ed6f3915f727aaec8648706760f278f0571/linux-user/syscall.c#L13405

which is what a `CPU` is made of:

https://github.com/AFLplusplus/LibAFL/blob/b519d249817742cc64027bfbfd09c11350d879a3/libafl_qemu/src/emu.rs#L483

That `CPUState *` could be passed to the syscall hook, which could use it to construct a `CPU` and do things like [write to registers](https://github.com/AFLplusplus/LibAFL/blob/b519d249817742cc64027bfbfd09c11350d879a3/libafl_qemu/src/emu.rs#L615) (like `rip` for my use-case).

**Describe alternatives you've considered**
Not doing this. I could possibly support my use-case by writing to shared memory or something? Seems much harder, and access to the CPU seems useful in this context anyway. But I might be missing something!

**Additional context**
If y'all think this is a good idea, I'm happy to take a first pass at it.

**Comment by andreafioraldi** [comment]
from the syscall hook you can get the current cpu with `hooks.emulator().current_cpu()` and call the trigger_breakpoint method there. never tried bu should (TM) work, if works from an hypercall

**Comment by langston-barrett** [comment]
I'm probably missing something here, but given [the signature of the hook in `set_pre_syscall_hook`](https://docs.rs/libafl_qemu/0.9.0/libafl_qemu/emu/struct.Emulator.html#method.set_pre_syscall_hook)
```rust
extern "C" fn(_: i32, _: u64, _: u64, _: u64, _: u64, _: u64, _: u64, _: u64, _: u64) -> SyscallHookResult
```
I assumed that the hook itself has to be an `extern "C" fn` like so:
```rust
extern "C" fn my_syscall_hook(
    code: i32,
    _arg0: u64,
    _arg1: u64,
    _arg2: u64,
    _arg3: u64,
    _arg4: u64,
    _arg5: u64,
    _arg6: u64,
    _arg7: u64,
) -> SyscallHookResult {
    // ...
}
```
In this case, I don't see how the hook would have access to a `hooks: QemuHooks` variable, as it can't have captured it from its environment as a closure might. Besides, the `hooks` are passed by `&mut`-reference to the `QemuExecutor`, so IIUC having another reference to them would be UB?

**Comment by andreafioraldi** [comment]
You are using the Emulator hooks, that are just rust equivalent of the raw C interface. Use the hooks in QemuHooks, like https://github.com/AFLplusplus/LibAFL/blob/main/libafl_qemu/src/snapshot.rs#L609

**Comment by langston-barrett** [comment]
Ah, I see what you mean! Looks like that would work for this use-case. Do you think it's worth it to point to `QemuHooks::syscalls` from the docs for `Emulator::set_pre_syscall_hook` (and perhaps similarly for other hook-related functions on `Emulator`) in case future users also don't see the connection? If so, I'm happy to make a PR, if not, we can go ahead and close this.

Rather than add comments for each individual hooking function, the top-level comment for `Emulator` could mention `QemuHooks`.

**Comment by domenukk** [comment]
Sounds like a footgun, feel free to add docs :)

**Comment by domenukk** [comment]
Until then, I guess this can be closed
