### ISSUE TITLE
Encountered compilation error on Apple computer with M2 version, error message is as follows

### ISSUE THREAD

**Issue by llllIIIllll** [AFLplusplus/LibAFL#1214]
Encountered compilation error on Apple computer with M2 version, error message is as follows：

 Compiling libafl_targets v0.10.0 (/Volumes/POOI/CODE/FUZZ/LIBAFL/LibAFL/libafl_targets)
error: failed to run custom build command for `libafl_cc v0.10.0 (/Volumes/POOI/CODE/FUZZ/LIBAFL/LibAFL/libafl_cc)`

Caused by:
  process didn't exit successfully: `/Volumes/POOI/CODE/FUZZ/LIBAFL/LibAFL/target/release/build/libafl_cc-708fd67f23865c7b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_CONFIG
  cargo:rerun-if-env-changed=LIBAFL_EDGES_MAP_SIZE
  cargo:rerun-if-env-changed=LIBAFL_ACCOUNTING_MAP_SIZE
  cargo:rerun-if-changed=src/common-llvm.h
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/cmplog-routines-pass.cc

  --- stderr
  Homebrew clang version 16.0.1
  Target: arm64-apple-darwin22.3.0
  Thread model: posix
  InstalledDir: /opt/homebrew/Cellar/llvm/16.0.1/bin
   "/opt/homebrew/Cellar/llvm/16.0.1/bin/clang-16" -cc1 -triple arm64-apple-macosx13.0.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name cmplog-routines-pass.cc -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -funwind-tables=1 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu apple-m1 -target-feature +v8.5a -target-feature +crc -target-feature +crypto -target-feature +dotprod -target-feature +fp-armv8 -target-feature +fp16fml -target-feature +lse -target-feature +ras -target-feature +rcpc -target-feature +rdm -target-feature +neon -target-feature +zcm -target-feature +zcz -target-feature +fullfp16 -target-feature +sm4 -target-feature +sha3 -target-feature +sha2 -target-feature +aes -target-abi darwinpcs -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=lldb -target-linker-version 820.1 -v -fcoverage-compilation-dir=/Volumes/POOI/CODE/FUZZ/LIBAFL/LibAFL/libafl_cc -resource-dir /opt/homebrew/Cellar/llvm/16.0.1/lib/clang/16 -I /opt/homebrew/Cellar/llvm/16.0.1/include -D __STDC_CONSTANT_MACROS -D __STDC_FORMAT_MACROS -D __STDC_LIMIT_MACROS -D LIBAFL_EDGES_MAP_SIZE=65536 -D LIBAFL_ACCOUNTING_MAP_SIZE=65536 -D USE_NEW_PM -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -stdlib=libc++ -internal-isystem /opt/homebrew/Cellar/llvm/16.0.1/bin/../include/c++/v1 -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/local/include -internal-isystem /opt/homebrew/Cellar/llvm/16.0.1/lib/clang/16/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include -std=c++17 -fdeprecated-macro -fdebug-compilation-dir=/Volumes/POOI/CODE/FUZZ/LIBAFL/LibAFL/libafl_cc -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fmax-type-align=16 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /var/folders/vg/0hh5sv7j7pv8xsxy9nj915640000gn/T/cmplog-routines-pass-370dce.o -x c++ src/cmplog-routines-pass.cc
  clang -cc1 version 16.0.1 based upon LLVM 16.0.1 default target arm64-apple-darwin22.3.0
  ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/local/include"
  ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/Library/Frameworks"
  #include "..." search starts here:
  #include <...> search starts here:
   /opt/homebrew/Cellar/llvm/16.0.1/include
   /opt/homebrew/Cellar/llvm/16.0.1/bin/../include/c++/v1
   /opt/homebrew/Cellar/llvm/16.0.1/lib/clang/16/include
   /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include
   /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks (framework directory)
  End of search list.
   "/Users/poi/POI/SOFT/ANDROIDSTUDIO/SDK/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/ld" -demangle -lto_library /opt/homebrew/Cellar/llvm/16.0.1/lib/libLTO.dylib -no_deduplicate -dynamic -dylib -arch arm64 -platform_version macos 13.0.0 13.0.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -undefined dynamic_lookup -undefined dynamic_lookup -o /Volumes/POOI/CODE/FUZZ/LIBAFL/LibAFL/target/release/build/libafl_cc-b750d290b6b35c4b/out/cmplog-routines-pass.dylib -L/opt/homebrew/Cellar/llvm/16.0.1/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib /var/folders/vg/0hh5sv7j7pv8xsxy9nj915640000gn/T/cmplog-routines-pass-370dce.o -search_paths_first -headerpad_max_install_names -lLLVM-16 -lc++ -lSystem /opt/homebrew/Cellar/llvm/16.0.1/lib/clang/16/lib/darwin/libclang_rt.osx.a
  ld: error: unknown argument '-no_deduplicate'
  ld: error: unknown argument '-dynamic', did you mean '-Bdynamic'
  ld: error: unknown argument '-dylib'
  ld: error: unknown argument '-arch'
  ld: error: unknown argument '-platform_version'
  ld: error: unknown argument '-syslibroot'
  ld: error: unknown argument '-search_paths_first'
  ld: error: unable to find library -lto_library
  ld: error: /opt/homebrew/Cellar/llvm/16.0.1/lib/libLTO.dylib: unknown file type
  ld: error: cannot open arm64: No such file or directory
  ld: error: cannot open macos: No such file or directory
  ld: error: cannot open 13.0.0: No such file or directory
  ld: error: cannot open 13.0.0: No such file or directory
  ld: error: cannot open /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk: Is a directory
  ld: error: /var/folders/vg/0hh5sv7j7pv8xsxy9nj915640000gn/T/cmplog-routines-pass-370dce.o: unknown file type
  ld: error: unable to find library -lLLVM-16
  ld: error: unable to find library -lc++
  ld: error: unable to find library -lSystem
  ld: error: /opt/homebrew/Cellar/llvm/16.0.1/lib/clang/16/lib/darwin/libclang_rt.osx.a: unknown file type
  clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
  thread 'main' panicked at 'assertion failed: Command::new(bindir_path.join(\"clang++\")).arg(\"-v\").args(cxxflags).arg(src_dir.join(src_file)).args(ldflags).arg(\"-o\").arg(out_dir.join(format!(\"{src_stub}.{}\",\n                        dll_extension()))).status().unwrap_or_else(|_|\n            panic!(\"Failed to compile {src_file}\")).success()', libafl_cc/build.rs:141:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by llllIIIllll** [comment]
oMacBook-Pro LibAFL % llvm-config --version
14.0.7git
My llvm‘s version is 14.0.7git,but the error still exists

**Comment by andreafioraldi** [comment]
>  Homebrew clang version 16.0.1

specify the correct llvm-config with the env LLVM_CONFIG=llvm-config, otherwise we default to the one installed with brew as usually the llvm-config binary is the one provided by Apple that is not compatible with LLVM passes
