### ISSUE TITLE
Update windows.rs

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#122]
Our windows.rs is 0.4 and now it is at 0.10, they have broken the API but we should update it for 0.4

**Comment by domenukk** [comment]
I started this over at https://github.com/AFLplusplus/LibAFL/tree/win_010

**Comment by andreafioraldi** [comment]
Good, so i'll wait it to implement timeouts on windows

**Comment by domenukk** [comment]
Closing this in favor of  #184
