### ISSUE TITLE
Could not compile `libafl_cc`

### ISSUE THREAD

**Issue by NeXX451** [AFLplusplus/LibAFL#1234]
Hi,
I'm trying to build the library using ``cargo build --release``. However, the process terminates with the error:

```
warning: Failed to find clang frontend.
   Compiling libafl_cc v0.10.0 (D:\C\rust\fuzzing\LibAFL\libafl_cc)
error[E0425]: cannot find value `LIBAFL_CC_LLVM_VERSION` in this scope
   --> libafl_cc\src\clang.rs:309:36
    |
309 |                 if let Some(ver) = LIBAFL_CC_LLVM_VERSION {
    |                                    ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `CLANG_PATH` in this scope
   --> libafl_cc\src\clang.rs:398:25
    |
398 |             wrapped_cc: CLANG_PATH.into(),
    |                         ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `CLANGXX_PATH` in this scope
   --> libafl_cc\src\clang.rs:399:26
    |
399 |             wrapped_cxx: CLANGXX_PATH.into(),
    |                          ^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
The following warnings were emitted during compilation:

warning: Failed to find clang frontend.

error: could not compile `libafl_cc` due to 3 previous errors
```

Now, I have installed LLVM-14.06 and I have also compiled the llvm-project (same version) to get the llvm-config executable. I have also set the path variable LLVM_CONFIG. The strange thing is that I have set the path to clang and I can compile with clang without problem.. here is the version:

```
PS D:\C\rust\fuzzing> clang --version
clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

PS D:\C\rust\fuzzing> llvm-config --version
14.0.6
```

Any suggestions appreciated.

**Comment by tokatoka** [comment]
do you have `./target/release/build/libafl_cc-<random number>/out/clang_constants.rs` in your directory?
https://github.com/AFLplusplus/LibAFL/blob/main/libafl_cc/build.rs#L271 this is an auto-generated file needed to compile libafl_cc

**Comment by NeXX451** [comment]
Yup, I have ``libafl_cc-12ae2230e3679ae0`` which contains some build scripts and ``libafl_cc-85d22745fcb8a4f6`` which contains the mentioned ``/out/clang_constants.rs``, however, it is an empty file.

**Comment by tokatoka** [comment]
ok, then 
https://github.com/AFLplusplus/LibAFL/blob/main/libafl_cc/src/clang.rs#L26
this line is where it includes the aforementioned clang_constants.rs.

Can you check if this is the right file, that has all the CLANG, LLVM_CC_LLVM_VERSION, definitions?

**Comment by NeXX451** [comment]
Ok, after a bit of digging, I have verified that yes it is indeed the correct file. However, in in here https://github.com/AFLplusplus/LibAFL/blob/8ff8ae41f1ed2956bb1e906c5c7bd0505ca110c0/libafl_cc/build.rs#L218 it should populate the ``clang_constants.rs`` file, but only if it can't find llvm-config??

```
    if find_llvm_config().is_err() {  <-------- true if llvm-config not found
        println!(
            "cargo:warning=Failed to find llvm-config, we will not build LLVM passes. If you need them, set the LLVM_CONFIG environment variable to a recent llvm-config."
        );

        write!(
            clang_constants_file,
            "// These constants are autogenerated by build.rs
/// The path to the `clang` executable
pub const CLANG_PATH: &str = \"clang\";
/// The path to the `clang++` executable
pub const CLANGXX_PATH: &str = \"clang++\";
/// The llvm version used to build llvm passes
pub const LIBAFL_CC_LLVM_VERSION: Option<usize> = None;
    "
        )
```

so the file is populated only if it *doesn't* find llvm-config? I'm confused. If I negate the if clause, I get the warning that llvm-config wasn't found but the file is populated. Namely with:
```
// These constants are autogenerated by build.rs
/// The path to the `clang` executable
pub const CLANG_PATH: &str = "clang";
/// The path to the `clang++` executable
pub const CLANGXX_PATH: &str = "clang++";
/// The llvm version used to build llvm passes
pub const LIBAFL_CC_LLVM_VERSION: Option<usize> = None;
```

**Comment by tokatoka** [comment]
if llvm-config is installed. then it'll get populated here
https://github.com/AFLplusplus/LibAFL/blob/8ff8ae41f1ed2956bb1e906c5c7bd0505ca110c0/libafl_cc/build.rs#L271

**Comment by NeXX451** [comment]
ok I found the issue, why it can't find clang. It's because of this
```
    let llvm_bindir = exec_llvm_config(&["--bindir"]);
    let bindir_path = Path::new(&llvm_bindir);

    let clang = bindir_path.join("clang");
```

If one installs the LLVM-tools on windows, it doesn't come with llvm-config, for that you have to compile the llvm-project yourself. Long story short, llvm-config and the clang executable are in two different locations. You can close this now :D 
However it wouldn't be a bad idea to include another env variable just for clang.

**Comment by tokatoka** [comment]
> However it wouldn't be a bad idea to include another env variable just for clang.
Yes, if you can submit a pr that'll be helpful. We don't have anybody with access to windows now.
