### ISSUE TITLE
Type driven-programming practice improvement

### ISSUE THREAD

**Issue by July541** [AFLplusplus/LibAFL#1264]
**Is your feature request related to a problem? Please describe.**
Thanks for this brilliant project! I'm trying a type-driven programming practice, starting from the declaration of `StdFuzzer` and its runner `fuzz_loop`. Like `let fuzzer = StdFuzzer::new()`, and then fill the hole by referencing type information. Thanks to excellent type design, I can fill most components with the help of type info and IDE's code completion, like `observer`, `manager` etc. The advantage of this practice is that I can write a fuzzer without any demonstration, it is also helpful for calling some new functions that haven't been well documented yet.

But I am still frustrated by some gaps, which make me have to look up the official document. It would be great if we can have a better experience with it.

**Describe the solution you'd like**

1. The trait name [HasSlution](https://docs.rs/libafl/0.10.0/libafl/state/trait.HasSolutions.html#) is vague, especially in the [constructor](https://docs.rs/libafl/0.10.0/libafl/state/struct.StdState.html#method.new) of `StdState`, I can't infer what does the `solution` mean and what should be passed. Maybe it is the idiom in fuzz? It should have a better name to indicate that is for some final result(like crash?) corpus.
2. It looks like the type parameter `C` and `SC` for [`StdState`](https://docs.rs/libafl/0.10.0/libafl/state/struct.StdState.html) always are the same type, it doesn't have any difference on type level between `input corpus` and `solution corpus`, that makes I can't infer what should be passed in. Is it possible to have a new type wrapper for `solution`?
3. If users don't call initial state generators like [`generate_initial_inputs`](https://docs.rs/libafl/0.10.0/libafl/state/struct.StdState.html#method.generate_initial_inputs) and [`load_initial_inputs`](https://docs.rs/libafl/0.10.0/libafl/state/struct.StdState.html#method.load_initial_inputs) doesn't load any corpus, the fuzzer will raise an error like `No item in Corpus`, it would be more helpful if we can suggest users to uses these generate function.

**Describe alternatives you've considered**
Keep the current circumstances.

**Additional context**
All suggestions are my experience while using the library.

I'm willing to offer prs if we agree on some aspects.

**Comment by tokatoka** [comment]
> The trait name [HasSlution](https://docs.rs/libafl/0.10.0/libafl/state/trait.HasSolutions.html#) is vague, especially in the [constructor](https://docs.rs/libafl/0.10.0/libafl/state/struct.StdState.html#method.new) of StdState, I can't infer what does the solution mean and what should be passed. Maybe it is the idiom in fuzz? It should have a better name to indicate that is for some final result(like crash?) corpus.

We can call it HasObjectives perhaps. we are using both solutions/objectives now

> It looks like the type parameter C and SC for [StdState](https://docs.rs/libafl/0.10.0/libafl/state/struct.StdState.html) always are the same type, it doesn't have any difference on type level between input corpus and solution corpus, that makes I can't infer what should be passed in. Is it possible to have a new type wrapper for solution?

In general you should use faster-corpus like inmemory or inmemoryondisk for corpus and ondisk for solutions. But it really depends on the user

> If users don't call initial state generators like [generate_initial_inputs](https://docs.rs/libafl/0.10.0/libafl/state/struct.StdState.html#method.generate_initial_inputs) and [load_initial_inputs](https://docs.rs/libafl/0.10.0/libafl/state/struct.StdState.html#method.load_initial_inputs) doesn't load any corpus, the fuzzer will raise an error like No item in Corpus, it would be more helpful if we can suggest users to uses these generate function.

For this, i don't know. Your fuzzing campaign would be super ineffective if you don't prepare suitable an initial corpus to start. I think raising an error is better tbh

**Comment by tokatoka** [comment]
Reopen if you have further questions
