### ISSUE TITLE
Nonexistent submodule commit for qsym_backend/qsym

### ISSUE THREAD

**Issue by novafacing** [AFLplusplus/LibAFL#1267]
**Describe the bug**

When creating a crate with:
```toml
libafl = { git = "https://github.com/AFLplusplus/LibAFL.git", branch = "main" }
```

I get an issue:

```
error: failed to get `libafl` as a dependency of package `windows-cpp-fuzz v0.1.0 (C:\Users\user\windows-cpp-fuzz)`

Caused by:
  failed to load source for dependency `libafl`

Caused by:
  Unable to update https://github.com/AFLplusplus/LibAFL.git?branch=main

Caused by:
  failed to update submodule `libafl_concolic/symcc_runtime/symcc`

Caused by:
  failed to update submodule `qsym_backend/qsym`

Caused by:
  object not found - no match for id (d17a39d40dc3ea1d17262dd52607f8a6527dde10); class=Odb (9); code=NotFound (-3)
```

As far as I can tell, this is because the commit actually is missing, I get an error message when visiting https://github.com/eurecom-s3/qsym/tree/d17a39d40dc3ea1d17262dd52607f8a6527dde10

**Expected behavior**

LibAFL should probably build from git, I don't know if there is any influence over QSYM but maybe the `libafl_concolic` submodule can be fixed.

**Comment by tokatoka** [comment]
i think we should stop using submodules

**Comment by novafacing** [comment]
I've had good luck with just cloning into `OUT_DIR` in `build.rs`, looks like `symcc_runtime` already has a build script so if that sounds like a good alternative I can look at fixing it. This isn't blocking me (just cloned directly and used `{ path = ... }` but I need to fix it before I can ship my fuzzer to other people :)
