### ISSUE TITLE
Multiple BytesDeleteMutator instantiations in havoc mutations

### ISSUE THREAD

**Issue by poemonsense** [AFLplusplus/LibAFL#1272]
**Describe the bug**
I'm new to fuzzing and LibAFL. I just noticed from the source code that BytesDeleteMutator is instantiated more than once, while other mutations are instantiated only once. Is this the expected behavior of havoc mutations? I search the internet/issues/PRs but did not find any related information.

**To Reproduce**
https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/mutators/scheduled.rs#L219-L222

**Expected behavior**
I think every mutator should be instantiated only once to have the same probability of being chosen. 

**Additional context**
I don't know much on fuzzing and LibAFL, so probably I was just missing something.

**Comment by tokatoka** [comment]
Yes this is intended
