### ISSUE TITLE
Baby fuzzer crash?

### ISSUE THREAD

**Issue by kokkonisd** [AFLplusplus/LibAFL#1290]
Is it normal for the baby fuzzer example in `./fuzzers/baby_fuzzer/` to crash after finding a bug?

```console
$ cargo run --release
...
[Stats #0] run time: 0h-0m-0s, clients: 1, corpus: 0, objectives: 0, executions: 0, exec/sec: 0.000
[Testcase #0] run time: 0h-0m-0s, clients: 1, corpus: 1, objectives: 0, executions: 1, exec/sec: 0.000
[Stats #0] run time: 0h-0m-0s, clients: 1, corpus: 1, objectives: 0, executions: 1, exec/sec: 0.000
[Testcase #0] run time: 0h-0m-0s, clients: 1, corpus: 2, objectives: 0, executions: 27, exec/sec: 0.000
[Stats #0] run time: 0h-0m-0s, clients: 1, corpus: 2, objectives: 0, executions: 27, exec/sec: 0.000
[Testcase #0] run time: 0h-0m-0s, clients: 1, corpus: 3, objectives: 0, executions: 390, exec/sec: 0.000
thread 'main' panicked at 'Artificial bug triggered =)', src/main.rs:47:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Objective #0] run time: 0h-0m-0s, clients: 1, corpus: 3, objectives: 1, executions: 390, exec/sec: 0.000
$ echo $?
134
```

AFAICT, it exits with a SIGABRT because of [this line in the in-process executor](https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/executors/inprocess.rs#L725), but to be honest I'm not sure why that's the case. Shouldn't it exit normally (with a return code of 0) since no problems came up during fuzzing and the only panic was caused by the bug that the fuzzer was trying to find?

**Comment by tokatoka** [comment]
I think this is intended.

Crash handler should return with exitcode SIGABRT. else we can't tell if it really aborted() or the harness called exit(0) itself

**Comment by domenukk** [comment]
Ah, I see this is an issue for #1289 right? Not sure what to do here tbh, finding the panic is the whole point of the fuzzer :P

**Comment by kokkonisd** [comment]
Understood, thanks for the explanation! This is indeed for #1289, but I think we can easily get around it by adding an `ignore` attribute to the failing code listings (which I've already done).
