### ISSUE TITLE
Help fuzzing binary target with cmplog

### ISSUE THREAD

**Issue by kokkonisd** [AFLplusplus/LibAFL#1313]
Hello folks!

I need some help putting together a fuzzer that can fuzz binary-only, uninstrumented targets (i.e. not compiled with `afl-cc` or similar), and with cmplog enabled.
I've put together a prototype using pieces from the example fuzzers in this repo, most notably `fuzzers/fuzzbench_qemu/` and `fuzzers/qemu_launcher/`. While it can indeed fuzz magic bytes in direct comparisons (e.g. nested `if`s comparing a single byte at a time), it doesn't seem to work with indirect comparisons (e.g. through `strcmp()`).
Is this a feature that's available in LibAFL?

If it helps: I'm essentially trying to reproduce fuzzing with AFL++ using `-Q -c 0` and `AFL_COMPCOV_LEVEL=2` as mentioned [here](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/fuzzing_binary-only_targets.md#fuzzing-binary-only-targets-with-afl).

**Comment by domenukk** [comment]
@andreafioraldi is the right person to answer qemu question (and maybe @tokatoka for cmplog)

**Comment by andreafioraldi** [comment]
nope. there are two ways to do that, a runtime library that hooks cmp functions that you preload, which should be easy to write, or functions calls hooks that are not a thing yet in LibAFL QEMU as they are arch dependent code and I never had time to work on them

**Comment by kokkonisd** [comment]
@andreafioraldi so if I understand correctly, probably the simplest way to do it would be to preload AFL++'s libcompcov and then just use "normal" cmplog functionality from LibAFL?

**Comment by andreafioraldi** [comment]
No because libcompcov works only when run in afl++, It maps the afl++ shared memory and writes the matching bytes as coverage. You need to modify it to report to the libafl fuzzer the matching byte, either adding a new map just for that (and additional Feedback in your fuzzer)

**Comment by andreafioraldi** [comment]
Also, libcompcov is not cmplog, it is more similar to laf-intel

**Comment by kokkonisd** [comment]
Okay, I think I see how to proceed more or less :) thanks!

(I'm fine with closing the issue now if nobody has something to add)
