### ISSUE TITLE
frida_gdiplus fuzzer panics on Windows

### ISSUE THREAD

**Issue by m-gsch** [AFLplusplus/LibAFL#1320]
**Describe the bug**
Running the fuzzer `frida_gdiplus` on Windows panics after less than a minute.

**To Reproduce**
1. Follow the setup from the README.
2. Install clang and llvm-tools from Visual Studio 2022
3. Point LIBCLANG_PATH to libclang path.
4. `cargo build --release`, `cl.exe /LD harness.cc /link /dll gdiplus.lib ole32.lib`
5. Run `target\release\frida_gdiplus.exe -H harness.dll -i corpus -o output --libs-to-instrument gdi32.dll --libs-to-instrument gdi32full.dll --libs-to-instrument gdiplus.dll --libs-to-instrument WindowsCodecs.dll`
6. Fuzzer panics after less than a minute on Windows 11 22H2 (usually, it's not deterministic) 
```
The application panicked (crashed).
Message:  Fuzzer-respawner: Storing state in crashed fuzzer instance did not work, no point to spawn the next client! This can happen if the child calls `exit()`, in that case make sure it uses `abort()`, if it got killed unrecoverable (OOM), or if there is a bug in the fuzzer itself. (Child exited with: exit code: 0)
```

**Expected behavior**
The fuzzer should run without panics.

**Screen output/Screenshots**
Example output before panic
```
[Testcase    #1]  (GLOBAL) run time: 0h-0m-42s, clients: 2, corpus: 139, objectives: 0, executions: 114183, exec/sec: 2.700k
                  (CLIENT) corpus: 139, objectives: 0, executions: 114183, exec/sec: 2.700k, edges: 5353/65536 (8%)
[Stats       #1]  (GLOBAL) run time: 0h-0m-42s, clients: 2, corpus: 139, objectives: 0, executions: 114183, exec/sec: 2.690k
                  (CLIENT) corpus: 139, objectives: 0, executions: 114183, exec/sec: 2.690k, edges: 5357/65536 (8%)
[Testcase    #1]  (GLOBAL) run time: 0h-0m-42s, clients: 2, corpus: 140, objectives: 0, executions: 114500, exec/sec: 2.696k
                  (CLIENT) corpus: 140, objectives: 0, executions: 114500, exec/sec: 2.696k, edges: 5357/65536 (8%)
[Stats       #1]  (GLOBAL) run time: 0h-0m-42s, clients: 2, corpus: 140, objectives: 0, executions: 114500, exec/sec: 2.694k
                  (CLIENT) corpus: 140, objectives: 0, executions: 114500, exec/sec: 2.694k, edges: 5366/65536 (8%)
[Testcase    #1]  (GLOBAL) run time: 0h-0m-42s, clients: 2, corpus: 141, objectives: 0, executions: 114573, exec/sec: 2.695k
                  (CLIENT) corpus: 141, objectives: 0, executions: 114573, exec/sec: 2.695k, edges: 5366/65536 (8%)
The application panicked (crashed).
Message:  Fuzzer-respawner: Storing state in crashed fuzzer instance did not work, no point to spawn the next client! This can happen if the child calls `exit()`, in that case make sure it uses `abort()`, if it got killed unrecoverable (OOM), or if there is a bug in the fuzzer itself. (Child exited with: exit code: 0)
```

**Additional context**
I can reproduce the same issue in a Windows Server 2022 21H2 and also it only seems to happen when both gdiplus.dll and WindowsCodecs.dll are instrumented or at least the panic doesn't happen that easily since leaving it running for 5min didn't produce a panic but with both of them instrumented it panics in less than a minute.

**Comment by tokatoka** [comment]
if gdi_plus calls ExitProcess(0) then that is the problem

**Comment by tokatoka** [comment]
i think this one is solved with the update. before frida rust bindings had a bug

**Comment by s1341** [comment]
This issue is sovled I believe on my frida_windows branch.
