### ISSUE TITLE
** ./configure aborting

### ISSUE THREAD

**Issue by Smilebirds** [AFLplusplus/LibAFL#1321]
hello here.i am new to libafl, and when i am running example of qemu_arm_launcher with "cargo make run ", i get:

[cargo-make] INFO - cargo make 0.36.11
[cargo-make] INFO - Calling cargo metadata to extract project info
[cargo-make] INFO - Cargo metadata done
[cargo-make] INFO - Project: qemu_arm_launcher
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: run
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Skipping Task: zlib_unix_wget 
[cargo-make] INFO - Running Task: zlib
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
[cargo-make] ERROR - Error while executing command, exit code: 1
[cargo-make] WARN - Build Failed.

and it's fine when i run "cd zlib-1.2.13 && CC=$CROSS_CC ./configure --prefix=./zlib" alone:
➜  qemu_arm_launcher git:(main) ✗ cd zlib-1.2.13 && CC=$CROSS_CC ./configure --prefix=./zlib
Checking for gcc...
Checking for shared library support...
Building shared library libz.so.1.2.13 with gcc.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.

any idea?please

**Comment by domenukk** [comment]
There are not a lot of errors to understand what's going on (?)
More information would be needed, also what's your OS, etc?

**Comment by Smilebirds** [comment]
thanks。and yes, there are not a lot of errors, that's also confused me.
here is the more detail of my system:
➜  ~ uname -a
Linux ubuntu 5.15.0-75-generic #82~20.04.1-Ubuntu SMP Wed Jun 7 19:37:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
➜  ~ clang --version
Ubuntu clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
➜  ~ clang++ --version
Ubuntu clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
➜  ~ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
➜  ~ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
➜  ~ cargo --version  
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
➜  ~ rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
➜  ~ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
 
i also tried 
1."sudo apt install build-essential autoconf automake libtool"
2."export CC=gcc"
3.reinstall rust and cargo-make
4.reinstall gcc
and all not work.
"cargo build" is fine , so maybe there are some error on cargo-make?

**Comment by Smilebirds** [comment]
thanks for your time @domenukk 
I just figured out that i forgot to install “gcc-arm-linux-gnueabi g++-arm-linux-gnueabi”
