### ISSUE TITLE
Backstrace Observer

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#134]
For crash dedup, we can implement a backtrace observer.

As the backtrace must be at crash point, and the crash point differ for each type of executor, this is not trivial.

I was thinking about adding a on_crash and on_timeout methods to InProcessExecutor that take a closure each for the type `|fuzzer, state, manager, observers, input| { .. }`. Here an user can fill the BactraceObserver calling the Linux backtrace() for instance.

For the Forkserver we need a shared memory. 

AFL never did this type of dedup, we should look at Honggfuzz instead.

**Comment by maxammann** [comment]
I worked around this by using AddressSanitizer. After collecting the crashes in the `crashes` directory I rerun the seeds and collect the stderr or each run.

Then I use this script to deduplicate crashes: https://gist.github.com/bitrot-sh/5acbc7c154f0fc7cf2b8c02d41d5be41

While this is not ideal it works for me right now.
Having feedback directly in Rust would be nice though.

**Comment by s1341** [comment]
I agree that feedback in rust would be better. Rerunning crashes is a little more difficult at the moment with e.g. frida-asan.

**Comment by andreafioraldi** [comment]
WIP #379
