### ISSUE TITLE
Simplify InProcessExecutor + TimeoutExecutor

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#1380]
With #1336 we add a lot of extra compatibility just to make InProcessExecutor wrappable in a TimeoutExecutor without leading to race conditions.
I think at this point it's fair to say that the `timeout` feature should be part of InProcessExecutor instead. It's a very common use case and merging them will get rid of a lot of useless code.

**Comment by tokatoka** [comment]
yes i'll do this
