### ISSUE TITLE
Memory safety issue in frida fuzzer breaks Windows CI

### ISSUE THREAD

**Issue by Mrmaxmeier** [AFLplusplus/LibAFL#1383]
Windows CI is sad at the moment. I tried investigating and found a gnarly UB issue in the frida fuzzer:

Due to an unsound API in frida-gum (https://github.com/frida/frida-rust/issues/102), this callback references a dangling stack object (`helper`):
https://github.com/AFLplusplus/LibAFL/blob/37bfead4e57f4f4c98e6fff1728518e39f1fbbd2/libafl_frida/src/helper.rs#L258

Unfortunately this is not trivial to fix, as `helper` is returned (and thus moved) later as part of the `FridaInstrumentationHelper::new` API.

It seems like this was noticed previously (https://github.com/AFLplusplus/LibAFL/pull/992), but it is still an issue.

**Comment by tokatoka** [comment]
thanks for the investigation

do you think this is related? i feel it is.
https://github.com/AFLplusplus/LibAFL/issues/1053

here i tried to make FridaInstrumentationHelper return Result<>, but it simply doesn't work (which is suprising)

**Comment by Mrmaxmeier** [comment]
Using a `Result<>` instead wouldn't fix the underlying issue. The closure passed to `Transformer::from_callback` needs to `move` it's context (currently it's not moving but referencing it). In order to do so the `helper` object would need be refactored into something that's reference-counted because we need to move it both into the closure context and return it from the `Helper::new` function.

**Comment by tokatoka** [comment]
Yeah i know. I mean Making it return Result<> simply make the entire frida_fuzzer break, which makes no sense.
So I guess the root cause of my issue is the same as yours.

**Comment by domenukk** [comment]
Any chance you can open a PR for that against frida @Mrmaxmeier ? I'd be more than happy to get frida fixed at some point :D

**Comment by Mrmaxmeier** [comment]
> So I guess the root cause of my issue is the same as yours.

Yes, wrapping the Helper in a Result probably changed the layout on the stack, which messes up the dangling reference in the callback closure. It still feels a bit like a miracle though that the code has ever worked correctly. :upside_down_face:

> Any chance you can open a PR for that against frida?

I've opened https://github.com/frida/frida-rust/pull/103, but the PR is not required to fix the issue on LibAFL's side.
