### ISSUE TITLE
Panic from `postcard` when using `Launcher`

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#1400]
### Discussed in https://github.com/AFLplusplus/LibAFL/discussions/1393

<div type='discussions-op-text'>

<sup>Originally posted by **langston-barrett** August  2, 2023</sup>
I have a fuzzer that uses `Launcher` like so:
```rust
    let mut run_client = |state: Option<_>, mut mgr, _core_id| -> Result<(), Error> { /* ... */ }
    {
        use libafl::bolts::{
            core_affinity::Cores,
            launcher::Launcher,
            shmem::{ShMemProvider, StdShMemProvider},
        };
        use libafl::monitors::MultiMonitor;
        use libafl::prelude::EventConfig;

        let shmem_provider = StdShMemProvider::new().expect("Failed to init shared memory");
        let monitor = MultiMonitor::new(|s| println!("{s}"));
        let broker_port = 1337; // TODO(lb): configurable
        let cores = Cores::from_cmdline("1-4").unwrap(); // TODO(lb): configurable

        // Build and run a Launcher
        match Launcher::builder()
            .shmem_provider(shmem_provider)
            .broker_port(broker_port)
            .configuration(EventConfig::from_build_id())
            .monitor(monitor)
            .run_client(&mut run_client)
            .cores(&cores)
            .stdout_file(Some("log"))
            .build()
            .launch()
        {
            Ok(()) => (),
            Err(Error::ShuttingDown) => println!("Fuzzing stopped by user. Bye!"),
            Err(err) => panic!("Failed to run launcher: {err:?}"),
        }
    }
```
However, it panics with:
```
    thread 'main' panicked at 'An error occurred when brokering. Exiting.: Serialize("WontImplement", ErrorBacktrace)', /home/langston/.cargo/git/checkouts/detect-libafl-ee5dccf8ba74c2f8/be25e73/libafl/src/bolts/llmp.rs:2265:18
    stack backtrace:
       0: rust_begin_unwind
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
       1: core::panicking::panic_fmt
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
       2: core::result::unwrap_failed
                 at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
       3: core::result::Result<T,E>::expect
       4: libafl::bolts::llmp::LlmpBroker<SP>::loop_forever
       5: libafl::events::llmp::LlmpEventBroker<I,MT,SP>::broker_loop
       6: libafl::events::llmp::RestartingMgr<MT,S,SP>::launch::{{closure}}
       7: libafl::events::llmp::RestartingMgr<MT,S,SP>::launch
       8: libafl::bolts::launcher::Launcher<CF,MT,S,SP>::launch
       9: dxezz::fuzz::fuzz
      10: dxezz::main
      11: core::ops::function::FnOnce::call_once
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
After a bit of digging, it appears likely that this is coming from [`postcard::Deserializer::deserialize_any`](https://github.com/jamesmunns/postcard/blob/672f0ee37b8ab66f124642b6c04bccb8cbb10a63/src/de/deserializer.rs#L217). Is this expected behavior? If so, is there a way I can modify my fuzzer to avoid this?</div>

**Comment by domenukk** [comment]
@langston-barrett 
So what happens is apparently that the Launcher sets up a Llmp channel (IPC between fuzzer nodes) and then for some reason `LlmpBroker::handle_new_msgs` (or some other handler) crashes when receiving.
Would be good to know what we send or what we receive...

**Comment by domenukk** [comment]
Any news @langston-barrett ?

**Comment by langston-barrett** [comment]
Sorry not yet! Definitely on my to-do list, but I'm currently prepping for a deadline in early Sept. that doesn't require this.

**Comment by langston-barrett** [comment]
It appears that this happens whenever asking `postcard` to deserialize my `Input` (which is a custom type, not one of the ones in LibAFL). Strange, because it serializes them fine...

**Comment by domenukk** [comment]
And you do properly add the input to the types registry, as well?
Can you try to share a minimal example somehow?

**Comment by langston-barrett** [comment]
> And you do properly add the input to the types registry, as well?

Hmm, I'm not sure - how would I do that?

FWIW, changing my input to get serialized/deserialized with `serde_json` made this go away.

**Comment by langston-barrett** [comment]
Looks like this doesn't depend on using `Launcher`, but can also happen with just a `SimpleRestartingEventManager`.

**Comment by domenukk** [comment]
So postcard is buggy?

**Comment by langston-barrett** [comment]
> And you do properly add the input to the types registry, as well?

I believe I tried this with:
```rust
    libafl::bolts::serdeany::RegistryBuilder::register::<T>();
```
with `T` being all the `SerdeAny` types in my program (there was only one, used for metadata). The `Input` does not implement `SerdeAny`.

**Comment by langston-barrett** [comment]
I've worked around this in my cause by making a new `EventManager` that doesn't restore the state (my fuzzer is a simple generative fuzzer, there's no real need to restore state):
```rust
use std::{env, fmt::Debug};

use libafl::{
    bolts::os::{fork, ForkResult},
    events::{
        Event, EventFirer, EventManager, EventManagerId, EventProcessor, EventRestarter,
        HasEventManagerId, ProgressReporter, SimpleEventManager,
    },
    inputs::UsesInput,
    monitors::Monitor,
    state::{
        HasClientPerfMonitor, HasCorpus, HasExecutions, HasLastReportTime, HasMetadata,
        HasSolutions, State, UsesState,
    },
    Error,
};

/// An [`EventManager`] that simply `fork`s and restarts the fuzzer every time
/// it crashes. Unlike `SimpleRestartingEventMananger`, it does not restore the
/// state of the fuzzer in any way.
#[derive(Debug)]
pub struct StatelessForkRestarter<MT, S: UsesInput>(SimpleEventManager<MT, S>);

impl<MT, S> UsesState for StatelessForkRestarter<MT, S>
where
    S: State,
{
    type State = S;
}

impl<MT, S> EventFirer for StatelessForkRestarter<MT, S>
where
    MT: Monitor,
    S: State,
{
    fn fire(
        &mut self,
        _state: &mut Self::State,
        event: Event<<Self::State as UsesInput>::Input>,
    ) -> Result<(), Error> {
        self.0.fire(_state, event)
    }
}

impl<MT, S> EventRestarter for StatelessForkRestarter<MT, S>
where
    MT: Monitor,
    S: State,
{
    fn on_restart(&mut self, _state: &mut S) -> Result<(), Error> {
        Ok(())
    }

    fn send_exiting(&mut self) -> Result<(), Error> {
        Ok(())
    }
}

impl<E, MT, S, Z> EventProcessor<E, Z> for StatelessForkRestarter<MT, S>
where
    MT: Monitor,
    S: State + HasExecutions,
{
    #[inline]
    fn process(
        &mut self,
        fuzzer: &mut Z,
        state: &mut Self::State,
        executor: &mut E,
    ) -> Result<usize, Error> {
        self.0.process(fuzzer, state, executor)
    }
}

impl<E, MT, S, Z> EventManager<E, Z> for StatelessForkRestarter<MT, S>
where
    MT: Monitor,
    S: State
        + HasClientPerfMonitor
        + HasExecutions
        + HasLastReportTime
        + HasMetadata
        + serde::Serialize,
{
}

impl<MT, S> ProgressReporter for StatelessForkRestarter<MT, S>
where
    MT: Monitor,
    S: State + HasClientPerfMonitor + HasExecutions + HasMetadata + HasLastReportTime,
{
}

impl<MT, S> HasEventManagerId for StatelessForkRestarter<MT, S>
where
    MT: Monitor,
    S: UsesInput,
{
    fn mgr_id(&self) -> EventManagerId {
        self.0.mgr_id()
    }
}

const DETECT_FUZZER_CHILD: &str = "_DETECT_FUZZER_CHILD";

#[allow(clippy::type_complexity, clippy::too_many_lines)]
impl<MT, S> StatelessForkRestarter<MT, S>
where
    S: UsesInput,
    MT: Monitor,
{
    pub fn launch(monitor: MT) -> Result<Self, Error>
    where
        S: serde::de::DeserializeOwned + serde::Serialize + HasCorpus + HasSolutions,
        MT: Debug,
    {
        if env::var(DETECT_FUZZER_CHILD).is_err() {
            env::set_var(DETECT_FUZZER_CHILD, "1");
            let mut ctr: u64 = 0;
            loop {
                let _child_status = match unsafe { fork() }? {
                    ForkResult::Parent(handle) => handle.status(),
                    ForkResult::Child => {
                        break;
                    }
                };
                ctr = ctr.wrapping_add(1);
            }
        }
        Ok(Self(SimpleEventManager::new(monitor)))
    }
}
```

**Comment by domenukk** [comment]
I still don't get why this happens at all, did you implement SerdeAny for your Input or no?

**Comment by langston-barrett** [comment]
No, my input does not have a `SerdeAny` impl, just the metadata does.

**Comment by domenukk** [comment]
Then just derive SerdeAny and it should work?

**Comment by langston-barrett** [comment]
Unfortunately, just adding `derive(SerdeAny)` doesn't work for me, because my `Input` type is generic:
```
error[E0107]: missing generics for struct `graph::Graph`
   --> apizz/src/graph.rs:245:12
    |
245 | pub struct Graph<FnId: Eq + Hash>(apizz_graph::Graph<Call<FnId>, Label>);
    |            ^^^^^ expected 1 generic argument
    |
note: struct defined here, with 1 generic parameter: `FnId`
   --> apizz/src/graph.rs:245:12
    |
245 | pub struct Graph<FnId: Eq + Hash>(apizz_graph::Graph<Call<FnId>, Label>);
    |            ^^^^^ ----
help: add missing generic argument
    |
245 | pub struct Graph<FnId><FnId: Eq + Hash>(apizz_graph::Graph<Call<FnId>, Label>);
    |                 ++++++

For more information about this error, try `rustc --explain E0107`.
error: could not compile `apizz` (lib) due to 2 previous errors
```
I could try working around this, but it would involve some changes across the codebase, as I also have `Generator`s, mutators, etc. operating on this type. Also, I'm surprised that `SerdeAny` would be required of my `Input`, but wouldn't be a trait bound on any relevant interface?

**Comment by domenukk** [comment]
Well SerdeAny is required the moment you want to use a state restorer, since it needs to be able to serialize the input, and the input is stored in the state, I assume?
Good question though, the input shouldn't be in the metadata, so not sure why it needs to be SerdeAny (cc @andreafioraldi )

That being said, at least `impl_serdeany!` will work with generics, else the MapObservers wouldn't work.

**Comment by langston-barrett** [comment]
> Well SerdeAny is required the moment you want to use a state restorer, since it needs to be able to serialize the input, and the input is stored in the state, I assume?

This makes sense to me, though it would be nice to learn this from a trait bound in the API rather than wasting your time :smile: 

> That being said, at least impl_serdeany! will work with generics, else the MapObservers wouldn't work.

Nice, this does appear to work:
```rust
libafl::impl_serdeany!(Graph<FnId: Debug + Eq + Hash + Serialize + 'static>);
```
... and it appears to solve my issue with the `WontImplement`! So the solution is probably just to add a relevant bound somewhere.

**Comment by domenukk** [comment]
PRs welcome 😬

I'm still a bit confused why this needs to be `SerdeAny`, tbh, I don't know where the input ends up in an `AnyMap`

**Comment by langston-barrett** [comment]
> ... and it appears to solve my issue with the WontImplement! So the solution is probably just to add a relevant bound somewhere.

Update: This actually does *not* appear to solve the issue. Perhaps I just didn't run into the situation that causes the `WontImplement` last time I tried it.

**Comment by domenukk** [comment]
No clue what to do here, works for me (tm) - Please reopen if this issue persists/we can help debug this somehow
