### ISSUE TITLE
Use `std::io::Error::last_os_error().raw_os_error().unwrap()` which gives us the errno string

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#1406]
There is `std::io::Error::last_os_error().raw_os_error().unwrap()` which gives us the errno string if I read this correctly, so that could be used for `Error` here

_Originally posted by @domenukk in https://github.com/AFLplusplus/LibAFL/pull/1389#discussion_r1287043229_

**Comment by gerceboss** [comment]
Hi , I am new here. Can you assign me this issue?
 I plan to replace all `perror` with the error string returning line you mentioned in [libafl_bolts/src/shmem.rs](https://github.com/AFLplusplus/LibAFL/pull/1389/files/3aced4fb2cba3e4afbba6b9bab777aee3b09c040#diff-fd31a9a2f96cfc4e7c89293c1ee08f834261ea22359bfac87d248c1a85ea310e)

**Comment by domenukk** [comment]
Feel free to do it :)

**Comment by gerceboss** [comment]
@domenukk 
while running the  `cargo clippy --all` command  I ran in one error , all other things were fine. Can you please guide me on this ? before I run the next set of commands to generate a PR


![clippy error](https://github.com/AFLplusplus/LibAFL/assets/122373295/f3e27552-8541-4f9d-9d41-ddd3679d5f0a)

**Comment by Mrmaxmeier** [comment]
@gerceboss `No such file or directory` might refer to the shell script's interpreter in the shebang in this case (Linux's error messages for process spawning issues are a bit weird..). Are you running on a system that does not provide bash under `/bin/bash`? Feel free to update the shebang to use `#!/usr/bin/env bash` instead, which should be more portable since `/usr/bin/env` is available on all Linux distros and avoids the hardcoded path to bash.

**Comment by gerceboss** [comment]
@domenukk  , I switched to linux for the repository.
 I am having this error while running `cargo clippy --all` , can you help me in this, please?

![Screenshot from 2024-02-07 03-21-37](https://github.com/AFLplusplus/LibAFL/assets/122373295/df26e3f3-f532-423f-baec-82f939990686)

**Comment by domenukk** [comment]
I don't see the actual error, but can you try if this works: `LLVM_CONFIG_PATH=/usr/bin/llvm-config cargo build`?

**Comment by gerceboss** [comment]
@domenukk can I just generate the PR? I think this error is occuring are related to the LLVM and clang installation .

**Comment by domenukk** [comment]
Sure, the CI will check it anyway - but you probably want to fix your LLVM install at some point ;)

**Comment by gerceboss** [comment]
Surely, I will fix it soon.

**Comment by tokatoka** [comment]
we don't need to get rid of it
https://github.com/am009/LibAFL/commit/bb2b63851ee38391c60865d0766bdf34b0f0de7f
this is fine
but we could add another enum like Error::UnixOSError()
see `libafl_bolts::Error`
