### ISSUE TITLE
LibAFL QEMU block execution hook pc parameter always 0

### ISSUE THREAD

**Issue by ravenolf** [AFLplusplus/LibAFL#1407]
**Note**
This issue was tested on the latest version of the main branch commit: `418d0dba91aa039f195848043c079c7117b88c70`
Testing Config: `IndexesLenTimeMinimizerScheduler`, `HitcountsMapObserver`, `SimpleMonitor`, `SimpleEventManager`.

**Describe the bug**
When fuzzing a binary with LibAFL QEMU and using a _custom qemu helper_ with a **basic block execution hook**, the value passed as the parameter `pc` is always 0. This issue does not happen with basic block generation hooks.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a simple fuzzer using LibAFL QEMU
2. Create a simple custom QEMU Helper for printing the value of pc:
    ```rust
    pub struct QemuBasicBlockHelper {}

    impl<S> QemuHelper<S> for QemuBasicBlockHelper
    where
        S: UsesInput + Debug + HasMetadata,
    {
        const HOOKS_DO_SIDE_EFFECTS: bool = false;

        fn init_hooks<QT>(&self, hooks: &QemuHooks<'_, QT, S>)
        where
            QT: libafl_qemu::QemuHelperTuple<S>,
        {
            hooks.blocks(None, None, Some(record_basic_block_execution::<QT, S>))
        }
    }

    fn record_basic_block_execution<QT, S>(
        _: &mut libafl_qemu::QemuHooks<'_, QT, S>,
        _: Option<&mut S>,
        pc: GuestAddr,
    ) where
        S: UsesInput + Debug + HasMetadata,
        QT: QemuHelperTuple<S>,
    {
        println!("recording executed basic block {pc:x}");
    }
    ```
3. Add the helper to the executor list of helpers:
    ```rust
    // ...
    let mut hooks = QemuHooks::new(
        &emu,
        tuple_list!(
            QemuBasicBlockHelper::default(),   // <---- added here
            QemuEdgeCoverageHelper::default(),
        ),
    );
    // ....
    let executor = QemuExecutor::new(
        &mut hooks, &mut harness,
        tuple_list!(edges_observer, time_observer),
        &mut fuzzer, &mut state, &mut mgr,
    )?;
    ```

**Expected behaviour**
The value of the parameter `pc` should be the address of the basic block currently executed

**Screen output/Screenshots**
When tested as `execution_hook`
![image](https://github.com/AFLplusplus/LibAFL/assets/38732323/da43d674-6157-448a-8e60-455ce6f8400d)

When tested as `post_generation_hook`
![image](https://github.com/AFLplusplus/LibAFL/assets/38732323/f0e3133b-99fe-4838-be9f-78878e1aeb5f)

**Comment by domenukk** [comment]
@andreafioraldi maybe you can take a look :)

**Comment by andreafioraldi** [comment]
Hi, this is intended as the execution hook parameter is not pc: GuestAddr but id: GuestAddr.
This id is generated by taking the return value of the generation hook, if you don't have one is 0.
For coverage for instance, this id is not the pc but an incremental counter for collision free coverage.

**Comment by andreafioraldi** [comment]
So, just add a generation hook and return Some(pc) in case you want an execution hook with the pc as id

**Comment by ravenolf** [comment]
Thank you so much for the clarification. Tested it today and it works perfectly!
