### ISSUE TITLE
in #1410

### ISSUE THREAD

**Issue by mark0-cn** [AFLplusplus/LibAFL#1412]
warning: Failed to find llvm-config, we will not build LLVM passes. If you need them, set the LLVM_CONFIG environment variable to a recent llvm-config.
 Documenting libafl v0.10.1 (D:\a\LibAFL\LibAFL\libafl)
error: unresolved link to `Testcase`
   --> libafl\src\schedulers\weighted.rs:305:25
    |
305 |     /// Called when a [`Testcase`] is added to the corpus
    |                         ^^^^^^^^ no item named `Testcase` in scope
    |
    = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
note: the lint level is defined here
   --> libafl\src\lib.rs:14:9
    |
14  | #![deny(rustdoc::broken_intra_doc_links)]
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not document `libafl`

**Comment by domenukk** [comment]
Copy-paste fail on my end..
