### ISSUE TITLE
Using already implemented C++ and Python code in Rust 

### ISSUE THREAD

**Issue by tejas012321011** [AFLplusplus/LibAFL#1426]
Hello, I was trying to implement the distance function of AFL-Go in Rust using LibAFL https://github.com/aflgo/aflgo/blob/master/scripts/distance.py and https://github.com/aflgo/aflgo/blob/master/distance_calculator/main.cpp. So, I would like to know the following two things : 
1. Since it will take significant effort to rewrite the code, is their some way I can call this code to serve the purpose of my fuzzer(like a wrapper, or something similar).
2. Is there any other way I can reuse the code, that you would like to sugest?

**Comment by domenukk** [comment]
Please reopen if things are still unclear :)

**Comment by tokatoka** [comment]
>  like what do you mean by compiling it and using it from the fuzzer.

your fuzzer is Rust. compile the code, then run it with Command::new('./main')

> I saw the cxx crate, i needed some guidance, on how can i learn to write crates in rust since I am still a beginner in the language.

i don't recommend using cxx for your case because the C++ code you want to translate is small
