### ISSUE TITLE
Rename tui_monitor feature to tui

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#1441]
Currently, we depend on the tui crate as an optional dep and enable it with the tui_monitor feature. We should instead replace this with the `tui` feature and specify `dep:tui` in the feature dependencies.

**Comment by domenukk** [comment]
Well it enables the TuiMonitor, hence the name(?)
We might have a Tui...something later

**Comment by domenukk** [comment]
We also have the `prometheus_monitor` that enables PrometheusMonitor, and other things with the same naming scheme.

**Comment by addisoncrump** [comment]
Ah, the main reason here is that most autocomplete tools will offer `tui` and `tui_monitor` as options for the features. If you're like me and don't read, this is quite misleading :upside_down_face:

**Comment by domenukk** [comment]
Alternatively we could do `monitor_tui`?

**Comment by domenukk** [comment]
Think I'm against this, sorry :)
