### ISSUE TITLE
MacOS Support for Frida ASAN / `walk_self_maps`

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#146]
If we want to support MacOS in Frida, we should reimplement `walk_self_maps`.
This could be rather straight forward, using this pointer:
https://jvns.ca/blog/2018/01/26/mac-memory-maps/

**Comment by oleavr** [comment]
Cool! FWIW Gum provides an API for doing this cross-platform: `gum_process_enumerate_ranges()` and `gum_module_enumerate_ranges()`.

**Comment by domenukk** [comment]
Fixed with #149
