### ISSUE TITLE
Flakey FreeBSD CI: CPU core count changes 

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#1462]
The following error occurs _sometimes_ in FreeBSD (rerun fixes it):
```rust
failures:
  
  ---- core_affinity::tests::test_get_core_ids stdout ----
  thread 'core_affinity::tests::test_get_core_ids' panicked at 'assertion failed: `(left == right)`
    left: `3`,
   right: `1`', libafl_bolts/src/core_affinity.rs:907:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  
  
  failures:
      core_affinity::tests::test_get_core_ids
  
  test result: FAILED. 20 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.29s
```

This is the assert that fails:
https://github.com/AFLplusplus/LibAFL/blob/4a9635427605e993039068615a6905912d7d9fe4/libafl_bolts/src/core_affinity.rs#L907

It seems like FreeBSD doesn't know how many cores it has?
CC @devnexen

**Comment by devnexen** [comment]
ah this one. I can never reproduce locally but seen few times in CI indeed. will have a look.

**Comment by domenukk** [comment]
Seems really hard to reproduce, see #1463

**Comment by domenukk** [comment]
let's see if this issue comes back

**Comment by domenukk** [comment]
Still exists apparently, according to @WorksButNotTested  ... But nothing we can do I guess

**Comment by WorksButNotTested** [comment]
Looks like the underlying implementation is [here](https://github.com/rust-lang/rust/blob/5a4e47ebedb4132168c1b22262f21f0d3a2a96df/library/std/src/sys/unix/thread.rs#L348C30-L348C48).

From the [docs](https://doc.rust-lang.org/stable/std/thread/fn.available_parallelism.html)
```
Returns an estimate of the default amount of parallelism a program should use.
...
Resource limits can be changed during the runtime of a program, therefore the value is not cached and instead recomputed every time this function is called. It should not be called from hot code.
```

Looks like the API says the value may change anyway?
