### ISSUE TITLE
the file `libafl/src/feedbacks/owned.rs` is not linked

### ISSUE THREAD

**Issue by lenawanel** [AFLplusplus/LibAFL#1504]

**Comment by domenukk** [comment]
Oh wow... potentially no longer needed then? @andreafioraldi can we delete it? Lot's of python stuff in there..

https://github.com/AFLplusplus/LibAFL/blob/b090bc7b4bd1ed5095205307779494099e717bbe/libafl/src/feedbacks/owned.rs#L48
