### ISSUE TITLE
ForkServer doesn't cleanup persistent mode binaries.

### ISSUE THREAD

**Issue by mvanotti** [AFLplusplus/LibAFL#1505]
It seems like LibAFL ForkserverExecutor doesn't stop the child process upon finishing, if it is a persistent-mode binary.

**To Reproduce**
1. Modify `fuzzers/forkserver_simple`, setting the forkserver to `is_persistent`:
```
    let mut forkserver = ForkserverExecutor::builder()
        .is_persistent(true)
        .program(opt.executable)
        .debug_child(debug_child)
        .shmem_provider(&mut shmem_provider)
        .autotokens(&mut tokens)
        .parse_afl_cmdline(args)
        .coverage_map_size(MAP_SIZE)
        .build(tuple_list!(time_observer, edges_observer))
        .unwrap();
```
2. Use a persistent-built binary, look for the AFL persist signature:
```
strings /data/fuzzing/png_fuzzer/png_fuzzer  | grep "PERSIST"
##SIG_AFL_PERSISTENT##
__AFL_PERSISTENT
AFL_PERSISTENT
AFL_PERSISTENT
```

3. Run the fuzzer for a certain number of iterations.
4. Check and see whether the child program is still running.
```
$ ps aux | grep png
user 2456790  0.0  0.0 21474889064 11828 ?   T    12:29   0:00 /data/fuzzing/png_fuzzer/png_fuzzer
```

**Expected behavior**
I expected the child process to die, and its resources to get cleaned up.

**Comment by mvanotti** [comment]
I think the error is caused because in the `Drop` implementation for the forkserver, we do `fsrv_handle.kill()`, instead of sending it a `SIGTERM`, which would allow it to cleanup its children.

**Comment by tokatoka** [comment]
how did you stop the fuzzer?
I think drop() is not called then we send SIGINT to it. I think we need to install proper signal handler for sigint

**Comment by tokatoka** [comment]
btw I can reproduce it too.

**Comment by tokatoka** [comment]
https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-fuzz.c#L48
we need this

**Comment by mvanotti** [comment]
> how did you stop the fuzzer?

In the forkserver simple example, I changed the code to use [`fuzz_loop_for`][fuzz_loop_for] instead of `fuzz_loop`. 

> I think drop() is not called then we send SIGINT to it. we need proper signal handler for it

> btw I can reproduce it too.
> and I replaced sigkill with sigterm, which didn't help. indeed drop() was never called, at least when I send sigint

I am seeing `drop` being called on [`Forkserver`][forkserver-drop]. I tried adding a sleep there and sending a `SIGTERM` to the process and it worked. I then changed the code the send a `SIGTERM` to that `fsrv_handle` from within rust, instead of doing the `kill`, and that seemed to have worked.

I am not sure what the correct fix for this issue is. What is the difference in the cleanup with the non-persistent forkserver executor?

[forkserver-drop]: https://github.com/AFLplusplus/LibAFL/blob/5311ce705acd9a43db5d3cf1fd2f7639969114a6/libafl/src/executors/forkserver.rs#L207
[fuzz_loop_for]: https://docs.rs/libafl/latest/libafl/fuzzer/trait.Fuzzer.html#method.fuzz_loop_for

**Comment by tokatoka** [comment]
> In the forkserver simple example, I changed the code to use [fuzz_loop_for](https://docs.rs/libafl/latest/libafl/fuzzer/trait.Fuzzer.html#method.fuzz_loop_for) instead of fuzz_loop.

ah ok. in this way drop() is called.
i just stopped it by pressing ctrl-c. in this case neither sigterm nor sigkill work.

> I am not sure what the correct fix for this issue is. What is the difference in the cleanup with the non-persistent forkserver executor?

i think we need to install sigint/sigterm handlers that will call drop() when they receive those signals

**Comment by tokatoka** [comment]
I think after #1521 this is actually fixed
