### ISSUE TITLE
QEMU persistent mode？

### ISSUE THREAD

**Issue by 01ChenQing** [AFLplusplus/LibAFL#1511]
I've only used afl++, does libafl provide QEMU persistent mode ? just like afl++. thx :)

**Comment by domenukk** [comment]
Yes, the InProcessExecutor does just that (roughly).
What LibAFL does should be faster for most use cases.

**Comment by 01ChenQing** [comment]
thanks a lot :)

**Comment by 01ChenQing** [comment]
> Yes, the InProcessExecutor does just that (roughly). What LibAFL does should be faster for most use cases.

thanks a lot :)
