### ISSUE TITLE
No entries in corpus bug?

### ISSUE THREAD

**Issue by DropTabl** [AFLplusplus/LibAFL#1513]
Hello,

Firstly, I'd like to extend my gratitude to everyone for the incredible work done here.
Problem Description

I've encountered the following issue:

I'm attempting to use **forkserver_simple** with **libpng** that was compiled and instrumented using **AFLplusplus/afl-clang-fast and AFLplusplus/afl-clang-fast++**. My understanding is that this binary can be executed with either a path to a file as an argument or with stdin. For instance:

```bash
./libpng_read_fuzzer kitty.png 
./libpng_read_fuzzer - "input on stdin"
```

The above commands execute without any problems.

However, when I use the **forkserver_simple**:

`./forkserver_simple <path_to_target> <path_to_corpus> -d`

I encounter the following error:

```
============================== INFO ================================
This binary is built for afl++.
To run the target function on individual input(s) execute:
  /magma_out/afl/libpng_read_fuzzer INPUT_FILE1 [INPUT_FILE2 ... ]
To fuzz with afl-fuzz execute:
  afl-fuzz [afl-flags] -- /magma_out/afl/libpng_read_fuzzer [-N]
afl-fuzz will run N iterations before re-spawning the process (default: INT_MAX)
For stdin input processing, pass '-' as single command line option.
For file input processing, pass '@@' as single command line option.
To use with afl-cmin or afl-cmin.bash pass '-' as single command line option
===================================================================
```

After some research, it appears (based on issue #1211) that forkserver_simple is designed for fuzzing programs that receive inputs from stdin rather than from a file. This would explain the error I've encountered since my target expects input as a filepath while the fuzzer gives input on stdin. But as the message suggest, I can set "-" as argument and then it should work. But setting this argument does not work and 'm currently stuck. I can't seem to find a way to pass the "-" as an argument for the target. The solution mentioned in #1211—adding `.arg_input_file_std() ` to the forkserver doesn't seem to work. Once I add this line, I receive the following error (normally, 4 inputs are loaded):

```
We imported 0 inputs from disk.
thread 'main' panicked at 'Error in the fuzzing loop: Empty("No entries in corpus", ErrorBacktrace)', src/main.rs:215:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

Additionally, using .`load_initial_inputs_force` when loading the initial corpus doesn't resolve the issue; the error persists.

I also tried adding an argument that accepts the "-" input and then using forkserver.arg with the argument. Unfortunately, this too triggers the same behavior and results in the "Failed to load initial corpus at..." error.
This is what i have done

```rust
...
#[arg(
        help = "Arguments passed to the target",
        short = 'a',
        name = "argt",
        allow_hyphen_values = true,

    )]
    argt: String,
...
 let mut forkserver = ForkserverExecutor::builder()
        .program(opt.executable)
        .debug_child(debug_child)
        .shmem_provider(&mut shmem_provider)
        .autotokens(&mut tokens)
        .parse_afl_cmdline(args)
        .arg(argt)
        .coverage_map_size(MAP_SIZE)
        .build(tuple_list!(time_observer, edges_observer))
        .unwrap();
...

```
But running 
`forkserver_simple -a - <target> <corpus> does also trigger the same error from above.`

How should I proceed? Is there something I might be overlooking?

Thank you in advance for your assistance.

**Comment by tokatoka** [comment]
> adding .arg_input_file_std()  to the forkserver doesn't seem to work.

> using .load_initial_inputs_force when loading the initial corpus doesn't resolve the issue; the error persists.

Feels like it's more about a problem in the instrumentation.
Can you tell me the exact step you used to build the harness?

**Comment by tokatoka** [comment]
Also
> I encounter the following error:

The output below that is the output from aflppdriver.c, meaning you are using a persistent mode harness. in this case you need to set `.persistent(true)`

**Comment by DropTabl** [comment]
Thank you so much for the help. 
I have forgotten `.is_persistent(true)`. That solved my issue

Just one more question.
Why is my corpus empty as soon as I add the code from above? What does the arg option has to do with the load of the initial input?

**Comment by tokatoka** [comment]
You linked your harness with this code when you compiled it.
https://github.com/AFLplusplus/AFLplusplus/blob/stable/utils/aflpp_driver/aflpp_driver.c

this is_persistent(true) just sets an env var and tells the forkserver that this harness is using persistent mode.
if you don't add is_persistent(true) then perhapes the harness just exits in this driver code and does not proceeds to the real target execution, thus nothing is deemed as interesting and no testcase is stored into the corpus.
