### ISSUE TITLE
Unsound implementation created misaligned pointer

### ISSUE THREAD

**Issue by shinmao** [AFLplusplus/LibAFL#1526]
### The source of unsoundness
Hi, we found that `<observers::map::HitcountsMapObserver<M> as observers::Observer<S>>::post_exec` could create a misaligned pointer:
https://github.com/AFLplusplus/LibAFL/blob/3625e881a3d7a838021046948fe710eab44ece69/libafl/src/observers/map.rs#L1246
At this line, the `u8` raw pointer was cast to `u16` pointer and passed to [core::slice::from_raw_parts_mut](https://doc.rust-lang.org/beta/core/slice/fn.from_raw_parts_mut.html#) which requires the pointer to be aligned. Otherwise, it could lead to undefined behavior.

**Comment by domenukk** [comment]
Great find, thanks! Can you please take a look at #1530 if this would be an okay fix?

**Comment by shinmao** [comment]
@domenukk thanks for the response. I just saw the code and considered it should be fixed!

**Comment by shinmao** [comment]
Another question:
https://github.com/AFLplusplus/LibAFL/blob/0e149afd7a08572cb85024328ec94e914d66c3ce/libafl_bolts/src/staterestore.rs#L215-L220
The safety of this function depends on the usage of internal library. The comments mentioned that "Beginning of the page will always be aligned": Is that guaranteed because the start address is 0x0 and could be multiple of any alignments?

**Comment by domenukk** [comment]
For all shmem implementations I know the start of the page will be aligned, but I'll happily replace this with a read_unaligned

**Comment by domenukk** [comment]
Ah no, it's not that easy

**Comment by shinmao** [comment]
I think it's fine if the address is 0x0.

**Comment by domenukk** [comment]
I'll add a debug_assert

**Comment by shinmao** [comment]
I have another issue about `bolts::anymap::unpack_type_id`. Personally, I would like to open another issue to avoid misunderstanding. Would you want me to describe it here?

**Comment by domenukk** [comment]
Yes please open another issue :)

**Comment by shinmao** [comment]
Would you mind help me report it to RUSTSEC so that we could remind users to update to the latest version?

**Comment by shinmao** [comment]
@tokatoka I just send the PR to the advisory-db (please see the link: https://github.com/rustsec/advisory-db/pull/1770/commits/03f3ceaa330ae17ef37418ba2e0859ba455a0f18). What I can do now is that update the information of patched version. Is it patched and release in a new version, and which version?

**Comment by tokatoka** [comment]
no there's no version released yet

**Comment by domenukk** [comment]
Maybe we should do a release then, cc @andreafioraldi

**Comment by shinmao** [comment]
Hi @domenukk , do you agree to create a [security policy](https://github.com/AFLplusplus/LibAFL/security) under the repo? Then I can send the advisory that all users can check the dependencies on Github.

**Comment by andreafioraldi** [comment]
> Hi @domenukk , do you agree to create a [security policy](https://github.com/AFLplusplus/LibAFL/security) under the repo? Then I can send the advisory that all users can check the dependencies on Github.

Hi @shinmao , thanks for the report!
I don't think that there is a threat model here and thus we cannot consider a bug in the code processing the coverage map as a security issue.
I don't mind too much about definitions, feel free to push things to advisory-db once we release the next version, but I would not bother by email any of our users for this bug.

**Comment by shinmao** [comment]
@andreafioraldi thanks for the response.
I have sent PR to advisory-db ([link](https://github.com/rustsec/advisory-db/pull/1770/commits/03f3ceaa330ae17ef37418ba2e0859ba455a0f18)) and wondering whether they have contacted you.

**Comment by andreafioraldi** [comment]
Not yet, but if they want to email users with things like dependabot i will not let them proceed, this is not a security vulnerability and users must not receive ambiguos alerts on their mailboxes.

**Comment by shinmao** [comment]
Understood. It is just something like undefined behavior from the perspective of Rust's language model.
