### ISSUE TITLE
Is lower weight really favored?

### ISSUE THREAD

**Issue by wtdcode** [AFLplusplus/LibAFL#1527]
From this:

https://github.com/AFLplusplus/LibAFL/blob/3625e881a3d7a838021046948fe710eab44ece69/libafl/src/schedulers/testcase_score.rs#L23

`/// Computes the favor factor of a [`Testcase`]. Lower is better.`

https://github.com/AFLplusplus/LibAFL/blob/3625e881a3d7a838021046948fe710eab44ece69/libafl/src/schedulers/testcase_score.rs#L282-L346

However, the implementation of `CorpusWeightTestcaseScore` is obviously favoring higher weight. Is it a document error?

**Comment by tokatoka** [comment]
> Is it a document error?

Yes nice find :+1:
