### ISSUE TITLE
Calibration stage noisily updates event manager

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#1541]
The calibration stage currently submits a stats update every time it is performed and completes calibration. It also does not update the number of executions.

The calibration stage should:
 - only update the statistics if the number of unstable edges has changed
 - update the execution count and send the associated updates

**Comment by tokatoka** [comment]
> only update the statistics if the number of unstable edges has changed

yes

> update the execution count and send the associated updates
I suspect it's not just calibration stage but in other stages too that we forget to update exec cnt. we have to check it.
