### ISSUE TITLE
Fuzzer performance regression since April 27?

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#1555]
https://storage.googleapis.com/www.fuzzbench.com/reports/experimental/2023-09-26-libafl/index.html

It's apparent that it performs worse than before

**Comment by addisoncrump** [comment]
We're still only 3 hours into that experiment. Still fully possible that it will pull ahead in the future, though yes I agree this is a noticeably slower start.

**Comment by tokatoka** [comment]
#1557
