### ISSUE TITLE
QEMU usermode input as files

### ISSUE THREAD

**Issue by seccompgeek** [AFLplusplus/LibAFL#1573]
Hi all, 
I am new to fuzzing and trying to get around binary-only fuzzing, so I understand I have to use the qemu mode. However, in the case of AFL++, when the program takes inputs as files there's the @@ option that would take care of things automatically. I found this works for instrumented fuzzing even in LibAFL, but for qemu mode, there doesn't seem to be such a thing. I need to add some hooks I figured using LibAFL would be much easier than building on AFL++, but I'm kind of stuck in this sense. Has anyone been in such a situation? As in, what if I want to start fuzzing from "main"? My current thought is simply putting a break point at "main" and write my input to the file in that harness, but I'm not sure this is the right way to go.
Any advice would be very much appreciated.

Thanks all.

**Comment by domenukk** [comment]
Two things:
a) you don't need to use qemu mode, you can also use frida or tinyinst to do the job. But at least frida and qemu should do the job equally well
b) for QEMU mode you are following the right approach, set a breakpoint at where you want to start to fuzz, basically.
look at the example in fuzzers, it uses a breakpoint at the entry point:
 https://github.com/AFLplusplus/LibAFL/blob/9755d189dd25c38bac1151efa7d668ada38a8859/fuzzers/qemu_launcher/src/client.rs#L117

Note that there might still be some things to consider, such as how to reset the state after each target execution (snapshots? use a forking executor?)
Also, make sure the target doesn't `exit()` if you are using an inprocess executor.
Best of luck ;)
