### ISSUE TITLE
How can I add new CLI options?

### ISSUE THREAD

**Issue by saruman9** [AFLplusplus/LibAFL#1583]
During the development of my fuzzer, I had a need to add several options for a CLI of an application. For example:
- [continuation of fuzzing](https://github.com/AFLplusplus/LibAFL/compare/main...saruman9:LibAFL:feat_cli_option_continue);
- [minimization of a corpus](https://github.com/AFLplusplus/LibAFL/compare/main...saruman9:LibAFL:feat_cli_option_minimization);
- [catch by timeout](https://github.com/AFLplusplus/LibAFL/compare/main...saruman9:LibAFL:feat_cli_option_timeout);
- [selection of modules for which coverage generation will not occur](https://github.com/AFLplusplus/LibAFL/compare/main...saruman9:LibAFL:feat_cli_option_dont_coverage).

What is the most correct way I can add these options to my fuzzer? I am currently editing LibAFL code. I can create a PR for all of the above options.

**Comment by domenukk** [comment]
Either you add a new CLI option behind a feature, yes, or you just create your own CLI parameters copying the original ones.
There isn't really a perfect answer I feel. :)
