### ISSUE TITLE
Un-macro SerdeAny

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#1605]
Historically, it was expected that we might allow for multiple registries, but we never used this functionality. We should remove the macro definition `create_serde_registry_for_trait` and unmacro the definition of SerdeAny.

**Comment by cy00r** [comment]
Hey, can I work on this issue?

**Comment by tokatoka** [comment]
you can work on any issue

**Comment by addisoncrump** [comment]
@cy00r did you want to claim this issue?

**Comment by cy00r** [comment]
@addisoncrump sure.
