### ISSUE TITLE
When using `ClangWrapper`, `dont_optimize()` must come before `parse_args(...)`

### ISSUE THREAD

**Issue by DanBlackwell** [AFLplusplus/LibAFL#1613]
Hi, not sure if this is really a bug or a feature (or maybe just more of a gotcha). I'm also not sure that there is an easy 'fix' other than documenting it.

In short, calling `parse_args(...)` when constructing the `ClangWrapper` tests the `optimize` field and populates the appropriate optimisation flags if it is set to true (which is the default). I had been calling `dont_optimize()` after `parse_args(...)` and thus the optimisation flags had already been added (resulting in my confusion). If for whatever reason you don't want optimisation, you must call `dont_optimize()` *before* `parse_args(...)`.

**Comment by tokatoka** [comment]
yes i think we should document it properly. there's no easy fix

**Comment by tokatoka** [comment]
fixed

**Comment by domenukk** [comment]
We could set a value to `true` in `parse_args` and then `panic` in `dont_optimize` if the args had already been parsed
