### ISSUE TITLE
Question: Why TinyInstExecutor's run_target returns without running the target?

### ISSUE THREAD

**Issue by mkravchik** [AFLplusplus/LibAFL#1660]
I'm new to LibAFL, so maybe I'm missing something. I'm running tinyinst_simple on Windows. It runs, but I noticed that the amount of actual test.exe processes spawned is an order of magnitude less then the number of calls to run_target. I added prints to run_target and can see that the call returns immediately with status OK, even though no new process was started. I tried to add some prints to the tinyinst' run code, but because it is no_std I don't know how to do it (yet).

Thanks a lot!

**Comment by tokatoka** [comment]
libafl_tinyinst is a (very) thin wrapper around the tinyinst APIs. you could simply insert your debug printfs into the C++ code.

**Comment by mkravchik** [comment]
Sure, I tried, but they don't appear.
________________________________

**Comment by tokatoka** [comment]
where did you put printf to?

**Comment by tokatoka** [comment]
but aren't you using persistent mode if you didn't change anything?
then new process is spawned every 10000 executions

**Comment by mkravchik** [comment]
I will check this.

**Comment by mkravchik** [comment]
Indeed, it is the persistent mode causing it
