### ISSUE TITLE
Keep non-interesting initial seeds around for Splicing and other things

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#1670]
**Is your feature request related to a problem? Please describe.**

When importing seeds initially, we only keep inputs in the corpus that are deemed interesting.
This seems like a good idea in general, but it will potentially lose state that the additional inputs contain.

**Describe the solution you'd like**

Instead of completely ignoring uninteresting inputs, we should import them but deactivate them, similar to how afl++ does it.

**Comment by R9295** [comment]
I'd like to take up this issue since I've been working on corpus loading. I'll have a look at the afl++ implementation and propose a solution

**Comment by R9295** [comment]
@tokatoka could you elaborate on the mutator side of things? Is it because it would have to consider disabled input once in a while?

**Comment by R9295** [comment]
So the way I would formulate the constraints for this issue:
1. create test case out of all initial corpus entries, do not discard any.
2. make sure this is not the case for ALL inputs, but only initial corpus.
3. how would the behavior work if the fuzzer was restarted?  unique  paths? (DiskCorpus)

**Comment by R9295** [comment]
Another question: Should the "force add input" option be removed after the implementation of disabled testcases?

**Comment by domenukk** [comment]
> @tokatoka could you elaborate on the mutator side of things? Is it because it would have to consider disabled input once in a while?
> 
> Edit: looked into it. So only the splice mutation should consider disabled testcases

Splicing mutators in AFL++ take disabled inputs into account, we should probably (optionally?) do the same.

> 
>     4. how would the behavior work if the fuzzer was restarted?  unique  paths? (DiskCorpus)

We don't have AFLplusplus like resume (yet) so it's a new initial corpus anyway


> Another question: Should the "force add input" option be removed after the implementation of disabled testcases?

I think they are slightly different, maybe leave it in place for blue

**Comment by tokatoka** [comment]
> @tokatoka could you elaborate on the mutator side of things? Is it because it would have to consider disabled input once in a while?

I think you need two components:
1. add a flag into `Testcase` to indicate if this input is non-interesting.
2. make a splice_mutations() just like havoc_mutations()

then something like `IfStage(|closure to check if it is uninteresting|, StdMutationalStage(splice_mutations()))` will do the job

**Comment by domenukk** [comment]
We probably need to specialize the corpus to allow ignoring those, as well in a performant way (or we could use a third corpus for those, too, but that'll be a bit painful)
