### ISSUE TITLE
Resolve CI instability

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#1678]
The CI has a number of unstable and inconsistent behaviours caused by reliance on external resources. Namely:
1. downloading of fuzz target sources
2. FreeBSD images inconsistently behave as expected
3. clippy frequently introduces new changes
4. Rust nightly changes which stabilise features

We should address each of these by using fixed, self-provided resources to reduce the overhead of submitting new changes:
1. git lfs storage for fuzz target sources
2. custom FreeBSD image that we refresh once a month or so
3. Rust nightly version pinning, which we update on the first of every month with an automatic PR
4. Same as above

As it stands, every PR is a fight with one of these sources of non-determinism and it makes every PR effectively five or six different PRs, or we have to rerun pipelines multiple times.

**Comment by tokatoka** [comment]
for 3 and 4.
we can add a bot that automatically open a pull request to change ci to use latest version every month. then we fixes it.

**Comment by tokatoka** [comment]
3 and 4 done
I'll tell it to open pr automatically if I confirm it is working with the current state

**Comment by addisoncrump** [comment]
I consider this effectively completed.
