### ISSUE TITLE
Observe statistics generated in the testing harness

### ISSUE THREAD

**Issue by maxammann** [AFLplusplus/LibAFL#171]
I'll post this here instead of going to the discord, such that other people can also find this.

I would like to collect statistics from the testing hardness. I think this should be done using an Observer, such that it is for example possible to update the user stats doing:

```rust
mgr.fire(_state, UpdateUserStats {});
```

The only data which can leave the harness function in the `InProcessExecutor` is the `ExitKind`. As far as I can tell the ´ExitKind` is only used to check whether something is interesting and is discarded after that check. Maybe the solution is as simple as passing the `ExitKind` to the `post_exec` function.
Do you have maybe more insight on where to change what?

As far as I can gell the `Executor` is not the problem but the `StdFuzzer` implementation.

**Comment by maxammann** [comment]
For now I'm using a global mutable constant to count stats:

`
pub static OPENSSL: AtomicUsize = AtomicUsize::new(0);
`

**Comment by s1341** [comment]
We did discuss a `CustomExitKind` enum variant at one point, which would provide what you're looking for. In frida-asan I'm currently using a global mutable as well. It's ugly though.

**Comment by domenukk** [comment]
Ah well, in the fuzzer the `ExitKind` is `drop`ped, right? Maybe at least that could be exposed as an observer, or attached to the input as metadata, would that make sense?
In general, you could probably collect stats in a feedback using, yet again, metadata.
What exactly do you want to collect?

**Comment by maxammann** [comment]
Yes I think it is dropped, I'm collecting stats about errors errors which are catched during executions. Those could give me insight on how good my mutators are working.

I think it would make sense to attach it as metadata to feedbacks.

**Comment by maxammann** [comment]
Closing this for now as a global mutable is just fine right now for me. Feel free to reopen if we have usecases where this is not possible.
