### ISSUE TITLE
Persistent mode forkserver child_id is reset to None while the pid is still valid

### ISSUE THREAD

**Issue by tbethe** [AFLplusplus/LibAFL#1714]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch

Yes.

**Describe the bug**
The Forkserver child_pid is always reset at the end of `run_target` while it's actually still valid when using persistent mode.
When persistent mode is used the child is actually stopped, so the PID remains valid.

**To Reproduce**
1. Create any persistent mode AFL compatible binary.
2. Access the `child_pid` inbetween executions.
3. child_pid will be 0 (or None in main).

**Expected behavior**

I expect to be able to get the PID of the stopped child instead of None.

**Additional context**
I think the following in `run_target` would fix it. 

```rust
if !libc::WIFSTOPPED(self.executor.forkserver().status()) {
        self.executor.forkserver_mut().reset_child_pid();
}
```

**Comment by tbethe** [comment]
I can create a pull request, just wanna make sure I'm not missing something obvious.

**Comment by tokatoka** [comment]
yes your change looks good thanks

**Comment by tbethe** [comment]
I also just noticed that the ForkserverExecutor has memory barriers and the TimeoutForkserverExecutor does not and I cannot think of a good reason why.

Maybe not so important since I read you wanna refactor TimeoutForkserverExecutor anyway

**Comment by tokatoka** [comment]
> I also just noticed that the ForkserverExecutor has memory barriers and the TimeoutForkserverExecutor does not and I cannot think of a good reason why.

I think that barrier is not needed in the pr you can delete it, (or add to TimeoutForkserverExecutor too)

> Maybe not so important since I read you wanna refactor TimeoutForkserverExecutor anyway

yes so the plan is to remove non-timeout version of any executor 
it's better in terms of performance but in reality you don't fuzz without timeouts else your fuzzer has the risk of getting stuck forever by some random inputs
