### ISSUE TITLE
Huge unused macro in anymap

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#1719]
Looks like the following macro is used nowhere, and not documented either. There are no tests for it, as well, so maybe it's broken, who knows?
https://github.com/AFLplusplus/LibAFL/blob/c2db7ad1623fceb047b3a22e51e0a91750ffc312/libafl_bolts/src/anymap.rs#L91

@andreafioraldi should we just remove it or write a test and docs?

**Comment by addisoncrump** [comment]
Duplicate of #1605

**Comment by domenukk** [comment]
> Duplicate of #1605

It's not a duplicate, the macro is completely unused and in a different file?
