### ISSUE TITLE
QEMU user-mode target hangs while executing code in RWX regions

### ISSUE THREAD

**Issue by cube0x8** [AFLplusplus/LibAFL#1736]
**Describe the bug**
I'm targeting an x86/64 application that heavily allocates, and executes, code in RWX memory regions. I'm experiencing hangs in the target when using `QemuEdgeCoverageHelper`.
I tried to debug using the QEMU logging features and realized that the application does not hang if `nochain` is used or `QemuEdgeCoverageClassicHelper` is used instead of  `QemuEdgeCoverageHelper`.

By using `QEMU_LOG=in_asm`, I got more details about the issue and it looks like the application hangs when trying to execute the following instruction:
```
IN: 
0x2aab050aa085:  
OBJD-T: ffa328000000 (jmp    QWORD PTR [rbx+0x28] )
```

which resulted to be the last instruction of a basic block.

**Comment by tokatoka** [comment]
the malloc problem is exists but the hanging is resolved right?
can i close? @cube0x8

**Comment by cube0x8** [comment]
Yes, this is fixed!
