### ISSUE TITLE
Document the difference between `OwnedRef` and `std::borrow::Cow`

### ISSUE THREAD

**Issue by langston-barrett** [AFLplusplus/LibAFL#1750]
`OwnedRef` (and similar types) abstract over whether a datum is borrowed or owned, in the same way that [`Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html) does. It would be great to have some documentation indicating why `OwnedRef` and friends are necessary, and when one might consider using one instead of `Cow`.

**Comment by domenukk** [comment]
OwnedRef can take pointers, while copy on write (I assume?) doesn't (right?)

**Comment by langston-barrett** [comment]
I asked this question one day before `RefRaw` was added :grin:
