### ISSUE TITLE
libafl-qemu docs build broken

### ISSUE THREAD

**Issue by langston-barrett** [AFLplusplus/LibAFL#1756]
See https://docs.rs/crate/libafl_qemu/0.11.2

**Comment by vringar** [comment]
The build also currently [fails in CI](https://github.com/AFLplusplus/LibAFL/actions/runs/8097113377/job/22127400404?pr=1894#step:12:3372)

**Comment by domenukk** [comment]
@rmalmain is this still relevant?

**Comment by rmalmain** [comment]
> @rmalmain is this still relevant?

Fixed in #1928 normally. It's not so easy to reproduce exactly the environment of docs.rs to follow the same build.
Hopefully, this will be enough.

**Comment by domenukk** [comment]
@rmalmain could you take a look?

**Comment by rmalmain** [comment]
I found the issue, I'll open a pr soon
