### ISSUE TITLE
Cannot compile libafl_concolic

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#1768]
```
error[E0407]: method `notify_basic_block` is not a member of trait `Filter`
   --> libafl_concolic/symcc_runtime/src/filter/coverage.rs:211:5
    |
211 | /     fn notify_basic_block(&mut self, location_id: usize) {
212 | |         self.register_location_on_hitmap(location_id);
213 | |     }
    | |_____^ not a member of trait `Filter`

error[E0407]: method `get_input_byte` is not a member of trait `Filter`
   --> libafl_concolic/symcc_runtime/src/filter.rs:153:5
    |
153 | /     fn get_input_byte(&mut self, offset: usize, _value: u8) -> bool {
154 | |         self.bytes_to_symbolize.contains(&offset)
155 | |     }
    | |_____^ not a member of trait `Filter`

```
we have these `is not a member of trait Filter` error. and I can't figure out what's missing
@julihoh do you have any idea how to fix this?

**Comment by domenukk** [comment]
I saw these a while ago when trying to change ... somehing? ... in CI

**Comment by domenukk** [comment]
IIRC it was the CI failure blocking this PR
https://github.com/AFLplusplus/LibAFL/pull/1370

**Comment by tokatoka** [comment]
the log for that one is lost. but yes it looks like so
for me it also happens when I run clippy

**Comment by domenukk** [comment]
Yes, seems to be the same issue.
https://github.com/AFLplusplus/LibAFL/pull/1370#issuecomment-1874596561

**Comment by tokatoka** [comment]
Oddly when i tried this on another machine everything is successful ... 🤷‍♂️ 🤷‍♂️ 🤷‍♂️

**Comment by tokatoka** [comment]
looks like
rust_exports_macro.rs is missing all the definitions

**Comment by tokatoka** [comment]
when I compared the successful build and the unsuccessful one
the rust-bindings from here https://github.com/AFLplusplus/LibAFL/blob/main/libafl_concolic/symcc_runtime/build.rs#L124 were empty in the unsuccessful builds

**Comment by tokatoka** [comment]
it's actually rust-bindgen that does not give the correct header file...

**Comment by julihoh** [comment]
Do I still need to look at this or is it fixed?

**Comment by tokatoka** [comment]
it's fixed now

**Comment by julihoh** [comment]
Great, thanks!
