### ISSUE TITLE
Port trim_case() from AFL++

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#177]
from @tokatoka

**Comment by andreafioraldi** [comment]
Testcase minimization has a low impact on fuzzing. It is ok to implement it, but not a priority now.

**Comment by tokatoka** [comment]
Closing because trim_case() seems to be useless.

**Comment by domenukk** [comment]
Don't we have tmin now which is basically that?

**Comment by tokatoka** [comment]
I think what they are trying to achieve is the same
but afl-tmin and trim_case() are doing different things as far as I can tell
