### ISSUE TITLE
Implement Mach ShMap for MacOS

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#178]
Right now, MacOS uses unix shared maps, however allowing programs to use more than 16 pages is non-trivial on MacOS.
Instead, we should move to the SharedMap API chrome uses, see
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/base/memory/platform_shared_memory_region_mac.cc#173

**Comment by domenukk** [comment]
Now that we have confirmed that https://github.com/AFLplusplus/LibAFL/blob/main/scripts/afl-persistent-config works for macos with SIP off, we can probably close/postpone this issue.

**Comment by s1341** [comment]
Isn't there still the issue with the shared-maps being deleted on the first `shmctl`?

**Comment by domenukk** [comment]
Ah right, forgot. However I wouldn't be sure if mach maps behave differently, so the issue may just always be there. 
Can you open an actual issue for that?
