### ISSUE TITLE
How to make libfuzzer_libpng_ctx test without stopping？

### ISSUE THREAD

**Issue by dierye** [AFLplusplus/LibAFL#1808]
When I run a test with libfuzzer_libpng_ctx, the execution count always stops at around 32687. Even though I provided enough initial corpus and modified the interesting mechanism to always find interesting test-cases, the test results still stop at around 32687. I would like to ask how to solve this problem?

--------------------------------------------------------------------------------------------------------------------------------------
[Timeout     #0]  (GLOBAL) run time: 0h-4m-4s, clients: 2, corpus: 76, objectives: 0, executions: 32687, exec/sec: 133.6
                  (CLIENT) corpus: 0, objectives: 0, executions: 0, exec/sec: 0.000
Client 001:
  0.0004: Scheduler
  0.0000: Manager
  Stage 0:
    0.0000: GetInputFromCorpus
    0.0021: Mutate
    0.0000: MutatePostExec
    0.0778: TargetExecution
    0.0011: PreExecObservers
    0.0077: PostExecObservers
  Feedbacks:
    0.9005: mapfeedback_metadata_edges
    0.0000: CrashFeedback
    0.0000: TimeoutFeedback
    0.0000: time
  0.0104: Not Measured

[Timeout     #0]  (GLOBAL) run time: 0h-4m-5s, clients: 2, corpus: 76, objectives: 0, executions: 32687, exec/sec: 133.1
                  (CLIENT) corpus: 0, objectives: 0, executions: 0, exec/sec: 0.000
Client 001:
  0.0004: Scheduler
  0.0000: Manager
  Stage 0:
    0.0000: GetInputFromCorpus
    0.0021: Mutate
    0.0000: MutatePostExec
    0.0778: TargetExecution
    0.0011: PreExecObservers
    0.0077: PostExecObservers
  Feedbacks:
    0.9005: mapfeedback_metadata_edges
    0.0000: CrashFeedback
    0.0000: TimeoutFeedback
    0.0000: time
  0.0104: Not Measured

[Timeout     #0]  (GLOBAL) run time: 0h-4m-6s, clients: 2, corpus: 76, objectives: 0, executions: 32687, exec/sec: 132.5
                  (CLIENT) corpus: 0, objectives: 0, executions: 0, exec/sec: 0.000
Client 001:
  0.0004: Scheduler
  0.0000: Manager
  Stage 0:
    0.0000: GetInputFromCorpus
    0.0021: Mutate
    0.0000: MutatePostExec
    0.0778: TargetExecution
    0.0011: PreExecObservers
    0.0077: PostExecObservers
  Feedbacks:
    0.9005: mapfeedback_metadata_edges
    0.0000: CrashFeedback
    0.0000: TimeoutFeedback
    0.0000: time
  0.0104: Not Measured

[Timeout     #0]  (GLOBAL) run time: 0h-4m-7s, clients: 2, corpus: 76, objectives: 0, executions: 32687, exec/sec: 132.0
                  (CLIENT) corpus: 0, objectives: 0, executions: 0, exec/sec: 0.000
Client 001:
  0.0004: Scheduler
  0.0000: Manager
  Stage 0:
    0.0000: GetInputFromCorpus
    0.0021: Mutate
    0.0000: MutatePostExec
    0.0778: TargetExecution
    0.0011: PreExecObservers
    0.0077: PostExecObservers
  Feedbacks:
    0.9005: mapfeedback_metadata_edges
    0.0000: CrashFeedback
    0.0000: TimeoutFeedback
    0.0000: time
  0.0104: Not Measured

**Comment by tokatoka** [comment]
>  the execution count always stops at around 32687

I can't reproduce this. For me it's working fine.
You are seeing timeout which should not happen with this fast target
Can you increase the duration for the timeout?

**Comment by dierye** [comment]
> > the execution count always stops at around 32687
> 
> I can't reproduce this. For me it's working fine. You are seeing timeout which should not happen with this fast target Can you increase the duration for the timeout?

I've tried turning the timeout up 100x, but it's not getting any better. How do I debug to make sure it's runnning and not just stopped working because the executions aren't increasing.
![2024-01-19 19-52-58](https://github.com/AFLplusplus/LibAFL/assets/43627503/4acb2f81-c8dc-4ef5-b063-ee1d469c7fda)
![2024-01-19 19-53-03](https://github.com/AFLplusplus/LibAFL/assets/43627503/0bc157fc-0b71-4680-b341-21d67fa372e3)
![2024-01-19 19-53-07](https://github.com/AFLplusplus/LibAFL/assets/43627503/2b595bb7-19c6-4f1e-a202-1551232cc5a7)

**Comment by tokatoka** [comment]
what hardware are you using?
252 execs/sec is too slow for a modern computer

**Comment by dierye** [comment]
> what hardware are you using? 252 execs/sec is too slow for a modern computer

This is normal because I added some instrumnet code to record the control flow graph.

**Comment by tokatoka** [comment]
that's the reason of the problem.
your fuzzer is simply too slow that it looks stuck.

**Comment by tokatoka** [comment]
try removing feature llmp_broker_timeouts from libafl then broker won't have timeouts enabled
