### ISSUE TITLE
Mapfeedback<DifferentIsNovel> judge novelty based on maximum ?

### ISSUE THREAD

**Issue by Kherrisan** [AFLplusplus/LibAFL#1809]
https://github.com/AFLplusplus/LibAFL/blob/72c862171e13cab0b140fe816e7c38225c458525/libafl/src/feedbacks/map.rs#L565C37-L565C39

```
if item > *history_map.get_unchecked(j) {
        novelties.push(j);
}
```

I guess this may be `if item != *history_map.get_unchecked(j)`

**Comment by Kherrisan** [comment]
And also `items.simd_max(history) != history`.

**Comment by tokatoka** [comment]
It means comparing history and max(history, item), and the difference in these two is novel.
the non-vectorized version is more clear with regard to this.
```
            let reduced = MaxReducer::reduce(*history, item);
            if DifferentIsNovel::is_novel(*history, reduced) {
                *history = reduced;
                interesting = true;
                if self.novelties.is_some() {
                    self.novelties.as_mut().unwrap().push(i);
                }
            }
```

and the the vector version of it is doing the same thing

**Comment by tokatoka** [comment]
So in the end `DifferentIsNovel::is_novel(*history, reduced)` is the same as this.

> items.simd_max(history) != history.
