### ISSUE TITLE
State Naming

### ISSUE THREAD

**Issue by julihoh** [AFLplusplus/LibAFL#183]
I realise it may be a little late, but here's an idea:
I struggled a bit with understanding the concept of [`State`](https://docs.rs/libafl/0.3.2/libafl/state/index.html) in LibAFL. I think what eluded me the whole time was [this comment](https://github.com/AFLplusplus/LibAFL/blob/main/fuzzers/baby_fuzzer/src/main.rs#L68):

> "They are the data related to the feedbacks that you want to *persist* in the State."

The persistence aspect wasn't clear to me and that persistence is the primary purpose of state, as anything that should not be persisted can simply be part of anything else (like that concrete Observer/Feedback/Mutator/... implementation). This is also not mentioned in the documentation.
Therefore:
1. Should the documentation be updated to include this aspect?
2. Should `State` be renamed to `PersistentState`?

**Comment by andreafioraldi** [comment]
> This is also not mentioned in the documentation.

Which doc lol

No IMO State is ok, we must just specify it in the book, I have to write a page on State only

**Comment by julihoh** [comment]
> > This is also not mentioned in the documentation.
> 
> Which doc lol

😅 

> 
> No IMO State is ok, we must just specify it in the book, I have to write a page on State only

okay
