### ISSUE TITLE
Experiencing random timeouts with CentralizedEventManager

### ISSUE THREAD

**Issue by cube0x8** [AFLplusplus/LibAFL#1850]
**Describe the bug**
I am fuzzing a target program using the `CentralizedLauncher` launcher and QEMU. After a few minutes of fuzzing, there is a significant decrease in the exec/s stat. Upon closer inspection with debugging enabled in LibAFL and additional logs in the entry point of the target program where PID and timestamp of execution are logged, I observed that some clients are still active (sending stats and emulating the target) even if they're declared timed out from the `CentralizedLlmpEventBroker`.

**Expected behavior**
Clients that send stats are not considered inactive and, consequently, are not disconnected.

**Comment by tokatoka** [comment]
i think this is another problem with `receivers_joined_count`

**Comment by cube0x8** [comment]
I debugged a bit further.
Now, I see that a process is hanging here:
```
[2024-02-14T09:58:07Z INFO  libafl_bolts::llmp] PID 1031209: Awaiting safe_to_unmap_blocking
[2024-02-14T09:57:05Z INFO  libafl_bolts::llmp] PID 1031209: Reading safe_to_unmap from 0x7fcfb9e7f000
```

I grepped for that memory address in the log and I got this (there are more records but I pasted only the last ones):
```
[...]
[2024-02-14T09:56:53Z INFO  libafl_bolts::llmp] Allocating 13 bytes on page 0x7fcfb9e7f000 / map "1968404" (last msg: 0x7fcfb9f793c0)
[2024-02-14T09:56:53Z INFO  libafl_bolts::llmp] Allocating 13349 bytes on page 0x7fcfb9e7f000 / map "1968404" (last msg: 0x7fcfb9f79400)
[2024-02-14T09:57:04Z INFO  libafl_bolts::llmp] Allocating 13 bytes on page 0x7fcfb9e7f000 / map "1968404" (last msg: 0x7fcfb9f79440)
[2024-02-14T09:57:04Z INFO  libafl_bolts::llmp] Allocating 14488 bytes on page 0x7fcfb9e7f000 / map "1968404" (last msg: 0x7fcfb9f7c8c0)
[2024-02-14T09:57:04Z INFO  libafl_bolts::llmp] Allocating 0 bytes on page 0x7fcfb9e7f000 / map "1968404" (last msg: 0x7fcfb9f7c8c0)
```

Does `Allocating 0 bytes on page` sounds a bit weird? How can I investigate the reason why the memory pages at `0x7fcfb9e7f000` are not being released?

**Comment by cube0x8** [comment]
@tokatoka helped me through this and it turned out to be the Broker who's too slow to process clients messages. Instead of running one fuzzer with 48 clients, I distributed the coverage surface to several small fuzzers and this seems to have fixed it.

I think this can be closed.

**Comment by domenukk** [comment]
Hmm... this is still something we should fix _somehow_..
Are your test cases very large?

**Comment by cube0x8** [comment]
In my seed corpus, the biggest test case is 100kb. In the harness, I have a
limit of 300kb. I dont know how to answer your question :) you tell me if
they can be considered big.

Is the coverage map sent in the messages too? I'm using
QemuInstrumentationFilter to select a specific surface but I think it is
still very big.

Wouldn't be helpful to have a stat that shows how the broker is keeping up
with messages? Like a % between messages received and messages consumed.

**Comment by domenukk** [comment]
Yes the coverage map is sent over, however it's gzipped (if you have that enabled?). The log above sais a message is `13349` bytes big, that should be quick to memcpy, shouldn't it?

**Comment by cube0x8** [comment]
Update:

Even with less clients and coverage surface, I got the error `The receiver/broker could not process our sent etc.` again. But, this time, the error appeared after ~24h of running, and not after 1h.

Yes, I think that `13349` bytes should be quick to memcpy. By looking at the logs, I also see size like `51121`, which I think should be quick to memcpy too.

I don't think I have enabled gzip for coverage map? I didn't enable anything like this explicitly in the Cargo.toml. I can give a look at it and enable it to see if something changes.

Btw, I think that all of this is surely related to the Broker load of work with messages. I also noticed that running the fuzzer with 12 clients is actually faster than running it with 48. I think it's the Broker that is slowing down the clients. Is this possible?

If you need more details or you think I should add more logs to understand better what's going on, please tell me so I can give you more details.

**Comment by tokatoka** [comment]
> I don't think I have enabled gzip for coverage map?

it is feature llmp_compression, enabled by default

**Comment by tokatoka** [comment]
> What looks strange to me, it is that the broker is still handling messages from client 1 even after the timeout:

Also the important thing here is even after Client 1 is removed it is still Client 1 with the same process (with the same PID) that sends message and the broker handles it when it is not supposed to

**Comment by tokatoka** [comment]
@domenukk 

Do you have any idea? especially on why the disconnected client are still sending/ the brokers are still managing message

**Comment by domenukk** [comment]
Sounds like `last_msg_time` needs to be updated as well, then? I guess the assumption was that at some point the broker will get a moment to breathe/receive `None` and updating the last_msg_time less often would be faster? Probably I was mistaken, great find :) Feel free to propose a fix

I don't know why disconnected clients are still being handled, though, maybe more flaws in my logic?

**Comment by cube0x8** [comment]
After further debugging with @tokatoka it turned out that, since Centralized has two brokers, and they're both reading messages from clients, the `last_msg_time` is not handled properly. I try to be more specific:

if we have 4 clients, for example, and two brokers reading and handling their messages, once a broker reads N messages from one of the clients by calling `client.recv`, and correctly updates its `last_msg_time` by doing:

`self.llmp_clients[pos].last_msg_time = current_time();`

then, as a side effect, you get the `last_msg_time` for that client updated for 1 broker only, but not for the other one. Subsequently, the other broker will declare that client timed out when `self.client_timeout` is hit. 

I don't have a good understanding of Centralized for now but, as far as @tokatoka explained to me, there should be a broker, which is actually client 1, that forwards messages to the main broker (client 0). The main broker keeps things updated. This said, I don't understand why the main broker too is reading messages from all the clients instead of reading only the messages from the secondary broker. In addition, both brokers have their own `self.llmp_clients` so all the updates made on the clients contained in that `Vec` are not shared between brokers.

How to fix it? I don't know. Actually I don't really understand how all of this Centralized is useful for and which are its benefits (I'm not saying there aren't benefit or that it is bad designed, I really don't understand the purpose behind it). I think I should dig a bit more and see how this should be fixed.


For now I ran the fuzzer using the "normal" `Launcher` to see if I can have my target running with it, then I guess I'll dig a bit more Centralized with @tokatoka and propose a fix.

Suggestions + further explanation about how things should be working and designed are well accepted :)

**Comment by cube0x8** [comment]
I'm convinced that there's an issue in the Centralized related to how the clients' messages are handled. I try to explain it in details below:

we have
1) a main broker: `[2024-02-26T18:09:01Z INFO  libafl::events::launcher] PID 2352446: I am broker!!.`
2) and a centralized broker: `[2024-02-26T18:09:01Z DEBUG libafl::events::centralized] CentralizedBroker 2352950 entering broker_loop`

At a certain point, the centralized broker declared ClientId(8) timed out:
`[2024-02-26T18:14:01Z ERROR libafl_bolts::llmp] Broker 2352950: Client #ClientId(8) timed out. Removing. (last_msg_time 1708970941.558544813s, current_time 1708971241.563236231s, client_timeout 300s)`

so, from my log I can get details about Client 8 and what's happening when CentralizedBroker and the main broker are reading its messages from the shared memory map. As an example, below I reported the case where ClientId(8) sends its first message, and main broker reads it:
```
[2024-02-26T18:09:02Z INFO  libafl_bolts::llmp] PID 2353020: Client ClientId(8) Sending msg 0x7f30ecb54030 / msg id MessageId(1). Total messages sent: 1
[...]
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352446 going to read messages for ClientId(8)
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352446: Reading message from page 0x7f30dfc00000. Last msg 0x0 of ClientId(8)
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352446: read current message id 1 from map
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352446: we never read a message from this queue. Returning pointer to first message
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352446: message with id MessageId(1) from ClientId(8) read from the map.
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352446: Received new message (id MessageId(1)) from Client ClientId(8). Total handled messages: 1.
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352446: We're done handling ClientId(8). Updated last_msg_time to 1708970942.537693424s.
```

then, centralized broker goes to read messages from ClientId(8) and this happens:
```
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352950 going to read messages for ClientId(8)
[2024-02-26T18:09:02Z DEBUG libafl_bolts::llmp] Broker 2352950: Reading message from page 0x7f30dfc00000. Last msg 0x0 of ClientId(8)
```

Do you see the page address, from where the brokers are reading the messages, in the logs above? It's the same for both brokers. So they're reading messages from the same memory page.

By looking at the `recv` code, I can see that it does `let current_msg_id = (*page).current_msg_id.load(Ordering::Relaxed);` to read the message on the memory map, and I also read that `load` is atomic so, even if the brokers can access that at the same time, the broker that arrives later won't have the data there anymore because consumed from the broker that arrived before. Here it's where the broker that arrived later fails to update `last_msg_time` and, subsequently, will declare the client timed out while, on the other side, the broker that arrived before and could read the client's messages, will consider it up and alive.

Consider that each broker has its own `self.llmp_clients` list and, when a client hits the broker timeout, it is removed from broker's list [(here)](https://github.com/AFLplusplus/LibAFL/blob/1dcfe8ef56f38cc15c9d2205756550fda7cdf85a/libafl_bolts/src/llmp.rs#L2288)
This explains why we see client activity even if it is considered timed out: since there are two brokers, the one that declared the client timed out will remove it from its list, but the other broker still has it in its list and it's handling its messages.

If I understood correctly the design of the centralized, I think that the main broker shouldn't be reading the messages of the secondary clients.

**Comment by tokatoka** [comment]
you reproduced it with main in the end right?

**Comment by cube0x8** [comment]
I believe @tokatoka and I have finally grasped the issue. Below are our findings:

1) The `launch_with_client_timeout` is currently setting the timeout exclusively for the `CentralizedLlmpEventBroker` and not for the main broker. I initially expected the timeout to apply to both brokers, so it was perplexing to observe the main broker declaring a client timed out after 5 minutes of inactivity when launch_with_client_timeout was set to 20 minutes. Additionally, the `CentralizedLlmpEventBroker` receives only test cases from the clients, implying that it makes timeout decisions based on the frequency of receiving test cases. I find this inappropriate because a client might still be sending stats even if it is not observing new coverage. In essence, if a client is not sending test cases, it doesn't necessarily mean it is stuck and should be disconnected.

2) The timeout logging facilities in the once function are unclear as they log the index in the `llmp_clients` vector instead of the actual `ClientId`. Consequently, you might see "Client #x timed out," but it is actually referring to Client #y.

3) Regardless, the `ClientId` can be confusing due to duplicated client IDs in the brokers' `llmp_clients` lists. Sometimes, there are two identical client IDs corresponding to different processes (and hence different clients). I think the `ClientId` should correspond to the PID of the client.

**Comment by tokatoka** [comment]
> "heartbeat" messages to CentralizedLlmpEventBroker are sent only once per fuzz_loop. maybe add a warning if a stage takes too long time @domenukk, else clients will timeout but without further explanation.

@domenukk 

This could be another reason why per-stage timeout is needed

**Comment by domenukk** [comment]
I guess we should send the heartbeat more often? Or increase the timeout time by _a lot_
or both?

**Comment by tokatoka** [comment]
no it's not the frequency that is the problem.
the problem is that heartbeat is sent only once per fuzz_loop (i.e. stage tuple execution)

Imagine this case, you have your client timeout as 5 min, and executor timeout as 5 seconds
sending heartbeat -> start executing stage -> sending heartbeat
what if your StdMutational stage is runnnng a testcase that takes 4secs to execute and you run it for 128 times in that stage?
You will send the next heart beat only after 4 * 128 seconds. This will exceed the client.

This is the case for StdMutational stage.
Now the problem is, for example, PowerMutationalStage. Here you can't have an upper bound for how many times you mutate and execute the testcase. Thus the time you spend for this specific stage is unknown.

**Comment by tokatoka** [comment]
Stage timeout will fix this problem though

**Comment by domenukk** [comment]
the broker could also _additionally_ (obviously not on no_std) observe the pid of the other node (in theory) to see if it's still alive

**Comment by tokatoka** [comment]
but sometimes the fuzzer is actually stuck so checking only if it's alive or not is not enough. (also (unlikely though) another process might have the same pid).

**Comment by tokatoka** [comment]
also i noticed that there's no clean way to actually replace pid with client id. 
one self.llmp_client could receive from multiple processes. (more than two senders writing to the map, and only one receiver receives it).
In this case you have to check who is attaching to this shmid. but to do this you need run `ipcs` or scan `/proc/` which is too ugly and i don;t want to implement

**Comment by tokatoka** [comment]
Closing this.
Most of the problems has PRs to solve it now
