### ISSUE TITLE
Token Mutations Crash

### ISSUE THREAD

**Issue by novafacing** [AFLplusplus/LibAFL#1853]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch

Thank you for making LibAFL better!

**Describe the bug**

There is a panic in AFLppRedQueen::cmp_extend_encoding when subtraction overflows at https://github.com/AFLplusplus/LibAFL/blob/dede78159c103fbca32615e5e1ea2402d49106b3/libafl/src/mutators/token_mutations.rs#L719.

**To Reproduce**

```
#[allow(arithmetic_overflow)]
fn main() {
    let i: u64 = 202;
    let b: u64 = 102;
    let diff: i64 = (b - i) as i64;
    println!("{diff}");
}
```
**Expected behavior**

Overflows should be handled gracefully, and in particular this type of function should probably have `#[no_panic]` to make this guarantee easier across the board.

**Screen output/Screenshots**
If applicable, add copy-paste of the screen output or screenshot that shows the issue. Please ensure the output is in **English** and not in Chinese, Russian, German, etc.

**Additional context**

**Comment by novafacing** [comment]
Actually it looks like this is already fixed by moving the `as i64` to each term, linked the code and didn't check if it was the same as last release :)

**Comment by novafacing** [comment]
I spoke too soon, this is still an issue:

```
attempt to subtract with overflow: /home/rhart/.cargo/git/checkouts/libafl-c33dc6f5ec2f7a70/dede781/libafl/src/mutators/token_mutations.rs:719:24
```

**Comment by tokatoka** [comment]
yes it's good to have
