### ISSUE TITLE
How to add a crashing input to the corpus?

### ISSUE THREAD

**Issue by DanielEbert** [AFLplusplus/LibAFL#1866]
I run automatically scheduled long running fuzzing sessions over weekends with the goal of finding as many bugs as possible.
However, when all initial seed inputs crash, the fuzzer stops immediately after evaluating the seed inputs. Because the fuzzer stops early, I may miss bugs in my target program that would've been found by fuzzing for a longer duration.
I assume libafl stops early in this case this is because the corpus contains 0 entries.

Can you point me in a direction on what I have to do to help me fuzz for longer duration, even if all initial seed inputs crash?

Like 'load_initial_inputs', 'load_initial_inputs_forced()' also executes the seed inputs and crashing seed inputs are not added to the corpus.

---
Below is what I have found out so far about why no input is added to the corpus in case of a crash:

The fuzzer adds the initial inputs with load_initial_inputs. This will eventually call fuzzer.add_input() in [fn continue_loading_initial_inputs_custom()](https://github.com/AFLplusplus/LibAFL/blob/50892ddc7592009eae6bc4af8b433977c3a3fed7/libafl/src/state/mod.rs#L731). [fn add_input()](https://github.com/AFLplusplus/LibAFL/blob/50892ddc7592009eae6bc4af8b433977c3a3fed7/libafl/src/fuzzer/mod.rs#L495) calls execute_input() and when the input crashes the target program, the input is not added to the corpus.

These are parts of the [fn add_input()](https://github.com/AFLplusplus/LibAFL/blob/50892ddc7592009eae6bc4af8b433977c3a3fed7/libafl/src/fuzzer/mod.rs#L495) function 
~~~
fn add_input(
        &mut self,
        state: &mut Self::State,
        executor: &mut E,
        manager: &mut EM,
        input: <Self::State as UsesInput>::Input,
    ) -> Result<CorpusId, Error> {
        let exit_kind = self.execute_input(state, executor, manager, &input)?;
        let observers = executor.observers();
        // Always consider this to be "interesting"
        let mut testcase = Testcase::with_executions(input.clone(), *state.executions());
...
 // Add the input to the main corpus
        self.feedback_mut()
            .append_metadata(state, observers, &mut testcase)?;
        let idx = state.corpus_mut().add(testcase)?;
        self.scheduler_mut().on_add(state, idx)?;
...
        manager.fire(
            state,
            Event::NewTestcase {
                input,
                observers_buf,
                exit_kind,
                corpus_size: state.corpus().count(),
                client_config: manager.configuration(),
                time: current_time(),
                executions: *state.executions(),
                forward_id: None,
            },
        )?;
~~~

Thanks in advance :)

**Comment by domenukk** [comment]
Why would you want to add crashing inputs to the corpus in the first place? They will just continue crashing the program, and every restart takes `x` milliseconds...
Instead, why not place a single non-crashing input in the corpus to make it fuzz _something_ at all (?)

**Comment by DanielEbert** [comment]
Your right, adding a crashing input to the corpus is not good.

Initially, I was not sure about how I can get a non-crashing input.
However, after you brought it up, I gave it more thought and realized that I can simply loop until I have one, e.g.:
~~~
while (state.corpus().count() == 0)
{
  // ...Generate a random seed input
  // ...Create seed_dir, write input to a file in seed_dir

  load_initial_inputs(seed_dir)
}
~~~

Thanks for your answer, I appreciate it!
