### ISSUE TITLE
Errors on running frida_gdiplus

### ISSUE THREAD

**Issue by GanbaruTobi** [AFLplusplus/LibAFL#1878]
1. You have verified that the issue to be present in the current `main` branch <-> yes

**Describe the bug**
```
C:\Users\gbaru\LibAFL\fuzzers\frida_gdiplus>target\release\frida_gdiplus.exe -H harness.dll -i corpus -o output --libs-to-instrument gdi32.dll --libs-to-instrument gdi32full.dll --libs-to-instrument gdiplus.dll --libs-to-instrument WindowsCodecs.dll --disable-excludes
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: LoadLibraryExW { source: Os { code: 193, kind: Uncategorized, message: "%1 ist keine zulässige Win32-Anwendung." } }
Location: src\fuzzer.rs:84

Backtrace omitted.

Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
The application panicked (crashed).
Message:  Fuzzer-respawner: Storing state in crashed fuzzer instance did not work, no point to spawn the next client! This can happen if the child calls `exit()`, in that case make sure it uses `abort()`, if it got killed unrecoverable (OOM), or if there is a bug in the fuzzer itself. (Child exited with: exit code: 101)
Location: C:\Users\gbaru\LibAFL\libafl\src\events\llmp.rs:1331
```

**To Reproduce**
1. build the fuzzer on windows like stated in the README.MD
2. execute the fuzzer

**Expected behavior**
No Errors

**Additional Information**
Up to date Windows 11 
rustc 1.76.0 (07dca489a 2024-02-04)
Visual Studio 2022 Community

**Comment by tokatoka** [comment]
it works for me (and for CI)
are you sure you are building stuff into 64bit?

**Comment by GanbaruTobi** [comment]
Argh! Thanks so much. The Developer CMD is making a 32-bit one.
I verified this using dumpbin /headers harness.dll
Using this script in Powershell and then compile worked: https://github.com/AFLplusplus/LibAFL/tree/main/fuzzers/libfuzzer_windows_asan#setup

Closing and thank you
