### ISSUE TITLE
Move Stages out of libafl_target

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#1889]
We have a number of stages in LibAFL targets.
They need to (somehow) move to the main LibAFL crate.

https://github.com/AFLplusplus/LibAFL/tree/1dcfe8ef56f38cc15c9d2205756550fda7cdf85a/libafl_targets/src/cmps/stages

**Comment by tokatoka** [comment]
it's there because it uses `AFLppCmpLogObserver` which depends on a symbol from libafl_targets

you cannot (naively) move it to `libafl` because then you have to include libafl_targets in libafl which causes circular dependency.

**Comment by domenukk** [comment]
A lot of Observers need `libafl_targets` under the hood to function properly. Worst case we need to change the constructor/API slightly. I don't think these components should be in targets

**Comment by domenukk** [comment]
The user may have to pass in the relevant values then, less magic anyway could be better.
Other option is to instead have the size live in LibAFL and targets reads it from there (worst case at build time)?

**Comment by addisoncrump** [comment]
Why do we need to move the stages to the main crate? It may make sense to keep some stages in libafl_targets, if they are truly specifically related to a specific target. IMO there are already several things in the main libafl crate that should not be there.

**Comment by domenukk** [comment]
On the one hand, I assume the stuff in libafl_targets they are not really target specific at the moment / could be generalized and on the other hand, how should anybody ever find components if they are not in LibAFL proper?

**Comment by domenukk** [comment]
What's the benefit of ripping things out of the core lib? Shouldn't the linker do its job and leave this stuff out anyway?

**Comment by addisoncrump** [comment]
Mostly code separation. Right now we have a massive crate that does a lot, but most of the stuff is just a handful of implementations that could be independently requested. This would potentially significantly reduce compilation time for the crate, since it wouldn't have to check the correctness of the unused types in the crate, and also would make things a little cleaner for downstream users who just want to look at the code.

**Comment by tokatoka** [comment]
it's impossible to move because that aflpp cmplog stage is only accessible from libafl_targets
