### ISSUE TITLE
Using libafl as libfuzzer for cargo-fuzz ignores -fork

### ISSUE THREAD

**Issue by wcampbell0x2a** [AFLplusplus/LibAFL#1891]
**To Reproduce**

I am using the following patch to use libafl as the libfuzzer for `cargo fuzz`:
```
libfuzzer-sys = { git = "https://github.com/AFLplusplus/LibAFL.git", branch = "libfuzzer-best", package = "libafl_libfuzzer" }
```
I run the following command, but it appears that the `-fork` is ignored. See right at the end of the `Running` line.
```
$ cargo fuzz run filesystem -j 6 --release -- -fork=20
    Finished `release` profile [optimized + debuginfo] target(s) in 0.11s
     Running `target/x86_64-unknown-linux-gnu/release/filesystem -artifact_prefix=/fuzz/artifacts/filesystem/ -fork=20 fuzz/corpus/filesystem -fork=6`
```

**Expected behavior**
I expected the fuzzer to use all 20 threads.

**Comment by addisoncrump** [comment]
The `-j` flag from `cargo-fuzz` specifies `-fork`; you need to use exactly one of these.

**Comment by wcampbell0x2a** [comment]
My bad. Thanks for the awesome work <3

**Comment by addisoncrump** [comment]
No sweat! This is not well-documented on `cargo-fuzz`.
