### ISSUE TITLE
rust-analyzer not being able to go to any definition

### ISSUE THREAD

**Issue by noobdoesre** [AFLplusplus/LibAFL#1892]
Hey! I've just started introducing myself to the project and stumbled upon not being able to navigate the codebase with vscode+rust-analyzer extension. My setup is fully updated ubuntu 22.04 with vscode. LibAFL is gitcloned, not installed as a crate or anything. I can build and run example fuzzers without any issues. rust-analyzer doesn't report any errors to it's "Output" window in vscode and overall seems to function properly, although I cannot navigate to any definition while studying example fuzzers. Of course I restarted the vscode and the language server, tried commenting out projects from the main Cargo.toml etc, but nothing worked.

Is there something I'm missing, should I prepare the repo somehow for rust-analyzer to start doing it's magic? Thanks!

**Comment by domenukk** [comment]
You'll need to open each example fuzzer folder as its own project to make vscode pick up the relationship to LibAFL, at least that's how I do it

**Comment by noobdoesre** [comment]
Many thanks!
