### ISSUE TITLE
Stop llmp loop via SIGINT/SIGTERM/SIGQUIT

### ISSUE THREAD

**Issue by maxammann** [AFLplusplus/LibAFL#191]
**Describe the bug**
I'm currently writing a `Stats` implementation using [tui](https://docs.rs/tui/0.15.0/tui/). I want to be able to stop fuzzing by sending a signal to the broker process. Unfortunately I can not get the process to exit gracefully. I'm using the Launcher to spawn the fuzzing clients.

Stopping via CTRL+C works fine. I guess it has something to do with signals also being sent to the children.

**To Reproduce**
1. Run fuzzer using Launcher
2. Send signal to parent process: `kill -SIGQUIT $parent_pid`

**Expected behavior**
The process should stop all of its childs and exit gracefully.

**Screen output/Screenshots**
Output after sending SIGINT to the parent process:

```
2021-06-27T12:09:38+02:00	[Stats       #1]  (GLOBAL) clients: 2, corpus: 27, objectives: 0, executions: 446, exec/sec: 78
2021-06-27T12:09:38+02:00	                  (CLIENT) corpus: 27, objectives: 0, executions: 446, exec/sec: 80, errors: fn:0|term:215|ssl:209|io:0|ag:0|str:0|ext:0, edges: 5076/47008 (10%)
thread 'main' panicked at 'Launcher failed: ShuttingDown', src/fuzzer/libafl_setup.rs:170:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Launcher failed: ShuttingDown', src/fuzzer/libafl_setup.rs:170:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Crashed with SIGABRT
Double crash

We crashed at addr 0x3e800004ca4, but are not in the target... Bug in the fuzzer? Exiting.
maps:
5609cb553000-5609cb692000 r--p 00000000 fe:03 3986639                    /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/tlspuffin
5609cb692000-5609cbfd5000 r-xp 0013f000 fe:03 3986639                    /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/tlspuffin
5609cbfd5000-5609cc25f000 r--p 00a82000 fe:03 3986639                    /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/tlspuffin
5609cc260000-5609cc309000 r--p 00d0c000 fe:03 3986639                    /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/tlspuffin
5609cc309000-5609cc33c000 rw-p 00db5000 fe:03 3986639                    /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/tlspuffin
5609cc33c000-5609cc351000 rw-p 00000000 00:00 0 
5609cc66e000-5609cc6a4000 rw-p 00000000 00:00 0                          [heap]
5609cc6a4000-5609cc99e000 rw-p 00000000 00:00 0                          [heap]
7f05129ac000-7f05131ad000 rw-p 00000000 00:00 0 
7f05131ad000-7f05231ad000 rw-s 00000000 00:01 229391                     /SYSV00000000 (deleted)
7f05231ad000-7f05331ad000 rw-s 00000000 00:01 229393                     /SYSV00000000 (deleted)
7f05331ad000-7f05431ad000 rw-s 00000000 00:01 229394                     /SYSV00000000 (deleted)
7f05431ad000-7f05531ad000 rw-s 00000000 00:01 229394                     /SYSV00000000 (deleted)
7f05531ad000-7f05631ad000 rw-s 00000000 00:01 229393                     /SYSV00000000 (deleted)
7f05631ad000-7f05731ad000 rw-s 00000000 00:01 229391                     /SYSV00000000 (deleted)
7f05731ad000-7f05731b2000 rw-p 00000000 00:00 0 
7f05731b2000-7f05731d8000 r--p 00000000 fe:03 396657                     /usr/lib/libc-2.33.so
7f05731d8000-7f0573323000 r-xp 00026000 fe:03 396657                     /usr/lib/libc-2.33.so
7f0573323000-7f057336f000 r--p 00171000 fe:03 396657                     /usr/lib/libc-2.33.so
7f057336f000-7f0573372000 r--p 001bc000 fe:03 396657                     /usr/lib/libc-2.33.so
7f0573372000-7f0573375000 rw-p 001bf000 fe:03 396657                     /usr/lib/libc-2.33.so
7f0573375000-7f057337e000 rw-p 00000000 00:00 0 
7f057337e000-7f0573380000 r--p 00000000 fe:03 396665                     /usr/lib/libdl-2.33.so
7f0573380000-7f0573382000 r-xp 00002000 fe:03 396665                     /usr/lib/libdl-2.33.so
7f0573382000-7f0573383000 r--p 00004000 fe:03 396665                     /usr/lib/libdl-2.33.so
7f0573383000-7f0573384000 r--p 00004000 fe:03 396665                     /usr/lib/libdl-2.33.so
7f0573384000-7f0573385000 rw-p 00005000 fe:03 396665                     /usr/lib/libdl-2.33.so
7f0573385000-7f0573394000 r--p 00000000 fe:03 396673                     /usr/lib/libm-2.33.so
7f0573394000-7f057342e000 r-xp 0000f000 fe:03 396673                     /usr/lib/libm-2.33.so
7f057342e000-7f05734c6000 r--p 000a9000 fe:03 396673                     /usr/lib/libm-2.33.so
7f05734c6000-7f05734c7000 ---p 00141000 fe:03 396673                     /usr/lib/libm-2.33.so
7f05734c7000-7f05734c8000 r--p 00141000 fe:03 396673                     /usr/lib/libm-2.33.so
7f05734c8000-7f05734c9000 rw-p 00142000 fe:03 396673                     /usr/lib/libm-2.33.so
7f05734c9000-7f05734d0000 r--p 00000000 fe:03 396706                     /usr/lib/libpthread-2.33.so
7f05734d0000-7f05734df000 r-xp 00007000 fe:03 396706                     /usr/lib/libpthread-2.33.so
7f05734df000-7f05734e3000 r--p 00016000 fe:03 396706                     /usr/lib/libpthread-2.33.so
7f05734e3000-7f05734e4000 ---p 0001a000 fe:03 396706                     /usr/lib/libpthread-2.33.so
7f05734e4000-7f05734e5000 r--p 0001a000 fe:03 396706                     /usr/lib/libpthread-2.33.so
7f05734e5000-7f05734e6000 rw-p 0001b000 fe:03 396706                     /usr/lib/libpthread-2.33.so
7f05734e6000-7f05734ea000 rw-p 00000000 00:00 0 
7f05734ea000-7f05734ed000 r--p 00000000 fe:03 396717                     /usr/lib/librt-2.33.so
7f05734ed000-7f05734f1000 r-xp 00003000 fe:03 396717                     /usr/lib/librt-2.33.so
7f05734f1000-7f05734f3000 r--p 00007000 fe:03 396717                     /usr/lib/librt-2.33.so
7f05734f3000-7f05734f4000 r--p 00008000 fe:03 396717                     /usr/lib/librt-2.33.so
7f05734f4000-7f05734f5000 rw-p 00009000 fe:03 396717                     /usr/lib/librt-2.33.so
7f05734f5000-7f05734f8000 r--p 00000000 fe:03 397449                     /usr/lib/libgcc_s.so.1
7f05734f8000-7f057350a000 r-xp 00003000 fe:03 397449                     /usr/lib/libgcc_s.so.1
7f057350a000-7f057350d000 r--p 00015000 fe:03 397449                     /usr/lib/libgcc_s.so.1
7f057350d000-7f057350e000 ---p 00018000 fe:03 397449                     /usr/lib/libgcc_s.so.1
7f057350e000-7f057350f000 r--p 00018000 fe:03 397449                     /usr/lib/libgcc_s.so.1
7f057350f000-7f0573510000 rw-p 00019000 fe:03 397449                     /usr/lib/libgcc_s.so.1
7f0573510000-7f0573512000 rw-p 00000000 00:00 0 
7f0573535000-7f0573536000 ---p 00000000 00:00 0 
7f0573536000-7f0573538000 rw-p 00000000 00:00 0 
7f0573538000-7f0573539000 r--p 00000000 fe:03 396645                     /usr/lib/ld-2.33.so
7f0573539000-7f057355d000 r-xp 00001000 fe:03 396645                     /usr/lib/ld-2.33.so
7f057355d000-7f0573566000 r--p 00025000 fe:03 396645                     /usr/lib/ld-2.33.so
7f0573566000-7f0573568000 r--p 0002d000 fe:03 396645                     /usr/lib/ld-2.33.so
7f0573568000-7f057356a000 rw-p 0002f000 fe:03 396645                     /usr/lib/ld-2.33.so
7ffe32769000-7ffe327be000 rw-p 00000000 00:00 0                          [stack]
7ffe327f7000-7ffe327fb000 r--p 00000000 00:00 0                          [vvar]
7ffe327fb000-7ffe327fd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]

Type QUIT to restart the child
[1]    19617 abort (core dumped)  target/x86_64-unknown-linux-gnu/debug/tlspuffin
```

**Additional context**

If I get to my goal quicky, I plan to create an extra crate for a TUI for LibAFL. I think it makes sense to put this into a separate crate as it may contain some heavy dependencies.

**Comment by domenukk** [comment]
Two things here:
1. `thread 'main' panicked at 'Launcher failed: ShuttingDown'`-> looks like you shouldn't `unwrap()` the fuzzer result, but instead differentiate between a normal `Err` and `Err(err) if err == Error::ShuttingDown`, see https://github.com/AFLplusplus/LibAFL/blob/bdb5efbf5b5118ba0ac290c69f9f28c6ae3ebc6c/fuzzers/libfuzzer_libpng/src/lib.rs#L61
2. The broker should broadcast a kill pill to its own shared map, or kill the connected clients in some other way. I don't think this is currently implemented. Also I'm not sure which thread dumps its core in your example (?), that looks like it's a client.

**Comment by domenukk** [comment]
We could also consider calling `exit` on interrupts, instead of returning `ShuttingDown`, that could be a more usable approach, what do you think?

**Comment by maxammann** [comment]
> Two things here:
> 
>     1. `thread 'main' panicked at 'Launcher failed: ShuttingDown'`-> looks like you shouldn't `unwrap()` the fuzzer result, but instead differentiate between a normal `Err` and `Err(err) if err == Error::ShuttingDown`, see https://github.com/AFLplusplus/LibAFL/blob/bdb5efbf5b5118ba0ac290c69f9f28c6ae3ebc6c/fuzzers/libfuzzer_libpng/src/lib.rs#L61

You are right, I think I copied this from some previous example. But I think this is not related to the crash we are seeing.

>     2. The broker should broadcast a kill pill to its own shared map, or kill the connected clients in some other way. I don't think this is currently implemented. Also I'm not sure which thread dumps its core in your example (?), that looks like it's a client.

I think this is already implemented [here](https://github.com/AFLplusplus/LibAFL/blob/bdb5efbf5b5118ba0ac290c69f9f28c6ae3ebc6c/libafl/src/bolts/launcher.rs#L158). I though I could reach this line by stopping the llmp loop [here](https://github.com/AFLplusplus/LibAFL/blob/bdb5efbf5b5118ba0ac290c69f9f28c6ae3ebc6c/libafl/src/bolts/llmp.rs#L1662)

Maybe this is not working because if we stop the fuzzing an error is returned and we are not reaching the killing.

**Comment by maxammann** [comment]
> We could also consider calling `exit` on interrupts, instead of returning `ShuttingDown`, that could be a more usable approach, what do you think?

Do you mean `std::process::exit`? If yes then I think this could have bad sideeffects. I already tried to stop the fuzzing by exiting. The bad thing is that (I suppose) the Rust `Drop` functions are not called. In the case of the TUI we need to reset the terminal. This happend on `drop`.

**Comment by andreafioraldi** [comment]
> > We could also consider calling `exit` on interrupts, instead of returning `ShuttingDown`, that could be a more usable approach, what do you think?
> 
> Do you mean `std::process::exit`? If yes then I think this could have bad sideeffects. I already tried to stop the fuzzing by exiting. The bad thing is that (I suppose) the Rust `Drop` functions are not called. In the case of the TUI we need to reset the terminal. This happend on `drop`.

Yes agree exit is a bad idea

**Comment by s1341** [comment]
I think the issue is that you are sending the `SIGINT` to the wrong process. You need to send it to the broker process, not the parent of the fuzzing process. The parent of the fuzzing process is the 'client', which has a signal handler in place to catch signals in the client or fuzzer. The graceful shutdown signal handler is in the broker.

**Comment by maxammann** [comment]
oh oke, I always thought that the parent process is the broker. Now the question is how do I find out the PID of the broker :thinking: 

I want to stop the whole process from within the display function of a Stats trait.

**Comment by s1341** [comment]
Hrm. I don't think we actually have a way at the moment. To work around this, you could set an environment variable in the launcher. Not particularly elegant, but it's a fast fix which should Just Work.

**Comment by domenukk** [comment]
print the PID of the broker after launch?

**Comment by maxammann** [comment]
Possible but I'm actually looking for a way to stop fuzzing from the parent process. Such that I can press 'q' and the fuzzer stops gracefully. Maybe not a priority right now, though

**Comment by s1341** [comment]
From the launcher process?

**Comment by maxammann** [comment]
> From the launcher process?

I'm not that sure which process is responsible for calling `display()` on the stats. I think it could either be the Launcher process or the broker process. Right now I thought about controlling the TUI and receiving key strokes from the display() function.

**Comment by domenukk** [comment]
Can this be closed or is there anything left to do at the moment?

**Comment by maxammann** [comment]
I'm not a 100% certain. What I would need is to stop the fuzzing gracefully from the broker process. 

* If the broker just kills itself, then all the clients will crash as far as I know. This works but is not really gracefully.
* If the parent process is stopped via CTRL+C (SIGINT) then the fuzzing stops gracefully I think.

We can close this now and as soon as I try to contribute a TUI based stats implementation like AFL++ I can reopen this.
