### ISSUE TITLE
Replace syscall() with write() in libafl_targets.

### ISSUE THREAD

**Issue by Skryptonyte** [AFLplusplus/LibAFL#1910]
There is a direct use of syscall() when its libc wrapper can be used instead. This is also the cause of a deprecation warning in macOS 10.12 and above.

https://github.com/AFLplusplus/LibAFL/blob/b7efe8eb7d95a1e7d39dd785ff1261c8be030af5/libafl_targets/src/cmplog.c#L124

```
warning: libafl_targets@0.11.2: src/cmplog.c:124:15: warning: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Wdeprecated-declarations]
warning: libafl_targets@0.11.2:   valid_len = syscall(SYS_write, dummy_fd[1], ptr, len);
```

I do already have a quick fix for this.

**Comment by tokatoka** [comment]
you can just replace it with libc's write

**Comment by domenukk** [comment]
FWIW we won't be able to get rid of syscalls in LibAFL, there are many instances where we need them.
