### ISSUE TITLE
Language: replace indices with indexes

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#1914]
We should unify our use of "indices" and "indexes"; presently, we use these effectively interchangeably around the codebase, but this has led to some inconsistent naming of types/information in documentation. Similarly, any types/functions we rename that existed in the previous release should have a second copy with the original name (e.g. a `pub type` for types, `pub fn` that calls the intended function for functions) and a `#[deprecated]` tag explaining the change.

This should preferably be completed after #1886 is merged.

**Comment by addisoncrump** [comment]
cc @domenukk @andreafioraldi @tokatoka: do we prefer "indices" or "indexes"? They are both valid; "indices" is primarily used in mathematical contexts, "indexes" for other fields.

**Comment by tokatoka** [comment]
for me indexes

**Comment by domenukk** [comment]
Looks like rust string uses `char_indices` - but otherwise we have way more uses of indexes in the codebase.

**Comment by addisoncrump** [comment]
Okay, then `indexes` should be used.

**Comment by domenukk** [comment]
This is done I think
