### ISSUE TITLE
Fetching corpus via TCP for inspection

### ISSUE THREAD

**Issue by maxammann** [AFLplusplus/LibAFL#192]
I think that debugging tools are quite important for a fuzzer. Sometimes a fuzzer behaves weird, because a lot of randomness is involved. I thought that it would be neat to have a way of fetching the current corpus. A process could fetch it and then do some analysis.

Is there a stable or unstable API to fetch the corpus in a serialized way?

Another approach for this would be to have a on-disk corpus. While this is definitely better than nothing, a dynamic full in memory approach would be more convenient.

**Comment by domenukk** [comment]
At the moment, the ways to access an InMemoryCorpus would be to either a) attach to the broker as client and listening to NewTestcase messages on the shared map, or b) attach to the Broker as second broker (b2b), in which case the testcases are actually shared via TCP.

This is somewhat related to the Main Broker concept, see #98

**Comment by domenukk** [comment]
Be aware that, while b2b can be used for this, currently doesn't

**Comment by domenukk** [comment]
If you want to patch in further TCP functionality, the `fn` to look at would be https://github.com/AFLplusplus/LibAFL/blob/f60148fc769740a1eefc2192d10705a558150c56/libafl/src/bolts/llmp.rs#L2062

**Comment by domenukk** [comment]
I thought about it and instead of adding your own functionality to the broker, it's probably easiest to spawn a second fuzzer running on the same node.
In it, never call `fuzz`, but instead wait for incoming connections on a different port, and have one thread (or the same thread) handling the latest events every few seconds, adding new testcases to the internal corpus. Engineering-wise, it may feel a bit odd, but that way the client won't interfere with the actual fuzzing

**Comment by maxammann** [comment]
> I thought about it and instead of adding your own functionality to the broker, it's probably easiest to spawn a second fuzzer running on the same node.
Do you mean starting a separate process which runs a client and connects on the port?

> In it, never fuzz, but instead wait for incoming connections on a different port, and have one thread (or the same thread) handling the latest events every few seconds, adding new testcases to the internal corpus. Engineering-wise, it may feel a bit odd, but that way the client won't interfere with the actual fuzzing

Thats a cool idea! Thanks for the input, I maybe look into it if the `python3 -m http.server` fails for me :)

**Comment by maxammann** [comment]
Btw, its possible to persist metadata to the ondisk corpus via: OnDiskCorpus::new_save_meta`

Maybe that helps somebody.
