### ISSUE TITLE
Missing dependency lock for the docker image

### ISSUE THREAD

**Issue by momvart** [AFLplusplus/LibAFL#1923]
**Describe the bug**
As no version locking is used in the project, it's possible to face version incompatibility issues when installing dependencies. Particularly, I faced such a problem when I tried to build the docker image at the latest published tag (`0.11.2`).
At this version, the docker image is based on Rust version `1.73.0`. Later when `sccache` is trying to be installed in the environment, one of its dependencies requires the minimum Rust version of `1.74.0` which causes the image build to fail.

**To Reproduce**
1. Checkout to tag `0.11.2`
2. Build the `Dockerfile`

**Expected behavior**
Dependency versions should be locked using `Cargo.lock` so we have the guarantee that the build is deterministic at each version.

**Comment by momvart** [comment]
While it makes sense to avoid pushing `Cargo.lock` on the main branch as the project is constantly updated with the latest versions, it's probably better to have it for the releases.

**Comment by domenukk** [comment]
As far as I understand, libraries should not have lock files in general(?)
Maybe the sccache problem might be a one-off?

**Comment by momvart** [comment]
> As far as I understand, libraries should not have lock files in general(?)

I think that's true. But this concerns the docker image and the build system where the behavior should be deterministic at each version (?). Thus fixed versions should be preferred.



> Maybe the sccache problem might be a one-off?

It is also true. Found this related issue: mozilla/sccache#1609

**Comment by momvart** [comment]
BTW, I maybe installing `sccache` after installing the latest nightly toolchain is enough to fix the problem. But still the non-determinism is there because of using the latest version of Rust's nightly toolchain.

**Comment by momvart** [comment]
NVM. It just misses the `--locked` flag to make sure that it uses the version of dependencies stated in `sccache`'s `Cargo.lock` file.
