### ISSUE TITLE
Using SanCov without libafl_cc layer?

### ISSUE THREAD

**Issue by noobdoesre** [AFLplusplus/LibAFL#1927]
I want to fuzz an open-source library for which I wrote a dylib harness which I load in my rust fuzzer and call target function in a fuzz loop. The problem I faced is the instrumentation callback (sanitizer_cov_trace_pc_guard) called from library leads into asan runtime library, not to the rust handler, which prevents fuzzer from getting any coverage information. 

I'm building the target library with stub_rt.c (fuzzbench fuzzer) which declares coverage specific functions as weak and I can see with nm -m that they are weak indeed although with definition inside asan runtime dylib. 

What is the trick to make it use coverage handlers defined in my rust fuzzer? I'm refraining from using libafl_cc simply because I can't fully grasp how it works

**Comment by domenukk** [comment]
libafl_cc just adds some compiler flags to clang, you can take a look at what it does and don't have to use it.
As for the symbols, are you using the correct feature flags in libafl_targets?

**Comment by tokatoka** [comment]
how about just compile asan statically instead of dylib

**Comment by domenukk** [comment]
Closing this for now, please reopen if this is not resolved
