### ISSUE TITLE
MapObserver should require Hash, not define a hash function

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#1977]
MapObserver currently defines a function `hash` which is used to get the current hash of the map. Instead, MapObserver should have a trait requirement of `Hash` so that it may be used with functions that accept `impl Hash` types.

Similarly, `hash_slice` should be deleted and usages replaced with the pre-defined Hasher::hash(&[T]).

**Comment by addisoncrump** [comment]
If no one takes this in 48 hours, I will implement it myself.

**Comment by domenukk** [comment]
Sounds useful

**Comment by tokatoka** [comment]
can you send a email to gsoc@aflplus.plus

**Comment by addisoncrump** [comment]
@edwin1729 Can you indicate when you plan to attempt this?

**Comment by edwin1729** [comment]
I've been trying to aflplusplus installed since yesterday.
On running
```
cargo build --release
```
I get
```
warning: libafl_cc@0.11.2: Skipping src/dump-cfg-pass.cc
warning: libafl_cc@0.11.2: Compiler version doesn't include clang or GCC: "cc" "--version".
.
.
.
```

**Comment by addisoncrump** [comment]
You may safely ignore that.

**Comment by edwin1729** [comment]
Okay thanks. Is it alright if a send a pull request tomorrow? Is this time sensitive?

**Comment by addisoncrump** [comment]
Preferably before Wednesday, but I recognise that this is a holiday weekend so Friday works as well.

**Comment by edwin1729** [comment]
Also, I still do have issues with running any of the example fuzzers. I believed that the warning might be the cause of the errors (since there's many of them right before the backtrace, which is quite long)

**Comment by addisoncrump** [comment]
Hm, are you building with `cargo make fuzzer`?

**Comment by edwin1729** [comment]
no `cargo make run` in `LibAFL/fuzzers/fuzzbench`

**Comment by addisoncrump** [comment]
That should work as well. I'm not sure what the issue is, but double check that you've installed all the required deps as listed in the README.

**Comment by edwin1729** [comment]
`LLVM Tools` is quite vague in the readme. I don't know what exactly it requires or even how to check if i have what it needs. I installed the apt packages `llvm-17-dev llvm-17-tools llvm-17 clang-17`

**Comment by addisoncrump** [comment]
AFL++ is not used in the example you are building. What exactly is the backtrace that you are seeing?

**Comment by edwin1729** [comment]
```
   0:     0x55e5f5cdd013 - std::backtrace_rs::backtrace::libunwind::trace::h6e4a662bea54ccfc
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55e5f5cdd013 - std::backtrace_rs::backtrace::trace_unsynchronized::hb42b4eb2797d9c0e
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e5f5cdd013 - std::sys_common::backtrace::_print_fmt::h2bc261f3223f4e4d
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55e5f5cdd013 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9cca0343d66d16a8
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e5f5c9dcb0 - core::fmt::rt::Argument::fmt::h8b666c45176be671
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/fmt/rt.rs:142:9
   5:     0x55e5f5c9dcb0 - core::fmt::write::h4311bce0ee536615
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/fmt/mod.rs:1120:17   6:     0x55e5f5cde6f4 - std::io::Write::write_fmt::h0685c51539d0a0cd
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/io/mod.rs:1846:15
   7:     0x55e5f5cde6f4 - std::sys_common::backtrace::_print::h25f19b1d64e81f86
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55e5f5cde6f4 - std::sys_common::backtrace::print::h2fb8f70628a241ed
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55e5f5cde3c8 - std::panicking::default_hook::{{closure}}::h05093fe2e3ef454d
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:272:22  10:     0x55e5f5cded9c - std::panicking::default_hook::h5ac38aa38e0086d2
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:292:9
  11:     0x55e5f5cded9c - std::panicking::rust_panic_with_hook::hed79743dc8b4b969
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:781:13  12:     0x55e5f5cde940 - std::panicking::begin_panic_handler::{{closure}}::ha437b5d58f431abf
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:659:13  13:     0x55e5f5cde896 - std::sys_common::backtrace::__rust_end_short_backtrace::hd98e82d5b39ec859
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55e5f5cde883 - rust_begin_unwind
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
  15:     0x55e5f5c90314 - core::panicking::panic_fmt::hc69c4d258fe11477
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14  16:     0x55e5f5c907e2 - core::result::unwrap_failed::hff299ec748d62aab
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1649:5
  17:     0x55e5f5c9953b - core::result::Result<T,E>::expect::h2e6b0e237343e7ff
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1030:23
  18:     0x55e5f5c9953b - libafl_cc::main::hc986a561adc1af70
                               at /home/ef322/LibAFL/fuzzers/fuzzbench/src/bin/libafl_cc.rs:27:29
  19:     0x55e5f5c92793 - core::ops::function::FnOnce::call_once::hfc3cdf54d5c38f17
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
  20:     0x55e5f5c92793 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9fd85d86772ad860
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:155:18
  21:     0x55e5f5c9b126 - main
  22:     0x7f9b10970083 - __libc_start_main
  23:     0x55e5f5c926ce - _start
  24:                0x0 - <unknown>
[cargo-make] ERROR - Error while executing command, exit code: 101
```

**Comment by addisoncrump** [comment]
Do you have the `clang` or `llvm-config` binary available?

**Comment by edwin1729** [comment]
Their both on $PATH, though i added them manually (`/usr/lib/llvm-17/bin/llvm-config`), perhaps that indicates something

**Comment by addisoncrump** [comment]
What is the actual error? You listed the warnings and the backtrace, but not the error.

**Comment by edwin1729** [comment]
Sorry, I've updated the stacktrace with the output from the entire command

**Comment by addisoncrump** [comment]
```
thread 'main' panicked at src/bin/libafl_cc.rs:38:14:
Failed to run the wrapped compiler: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

I'm guessing it's not finding clang. This is a pretty bad error message, though. @tokatoka @andreafioraldi, any ideas? I always just install with LLVM APT or Fedora :sweat_smile:

**Comment by edwin1729** [comment]
I'll just try reinstalling, or building llvm from source tomorrow, if there's no obvious solution here. Thank you!

**Comment by andreafioraldi** [comment]
The fuzzbench fuzzer uses the cmplog rtn llvm pass, make sure that is was
built. If libafl_cc cannot find your llvm installation is skips building
the passes.

You can force it to find your llvm config with an env:

LLVM_CONFIG=/path/to/llvm-config cargo make run

Il sab 30 mar 2024, 18:05 edwin1729 ***@***.***> ha scritto:

**Comment by tokatoka** [comment]
you should install the script from their website https://apt.llvm.org/

**Comment by edwin1729** [comment]
> Similarly, `hash_slice` should be deleted and usages replaced with the pre-defined Hasher::hash(&[T]).

There is no `Hasher::hash(&[T])` in std lib (or is there??). 
`Hash::hash<H:Hasher>(&self, state: &mut H)`  and 'MapObserver::hash(&self)' don't have the same signature. 
Since there's no function overloading in rust I think 'MapObserver::hash(&self)' might need to be renamed to something `hash_easy`.
 This feels quite messy, so maybe a macro around `Hash::hash<H:Hasher>(&self, state: &mut H)`  to get something like 'MapObserver::hash(&self)' ?

Either I'm over complicating or missing something. What was your original idea @addisoncrump ?

**Comment by edwin1729** [comment]
I've created a pull request to illustrate, the approach above (which I don't think is quite alright) #1989
