### ISSUE TITLE
Introspection: Some values are not used

### ISSUE THREAD

**Issue by maxammann** [AFLplusplus/LibAFL#198]
**Describe the bug**
I just noticed that some intro spection features are not sued:
* GetFeedbackInterestingAll
* PreExec
* PostExec

Actually I found no code usages for these.

Should we remove the feature types or is this a bug?

**Comment by andreafioraldi** [comment]
I'm going to remove them

**Comment by andreafioraldi** [comment]
Btw @maxammann I changed a bit introspection so that now the number of feedbacks and stages is not fixed

**Comment by domenukk** [comment]
This issue can be closed, right?
