### ISSUE TITLE
Break apart fuzzer test CI tasks into individual tasks per fuzzer

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#1999]
Right now, we have to wait a considerable amount of time to determine if each fuzzer successfully builds. While it is nice that we can reuse build artifacts from other fuzzers, it has the following problems:

 - if multiple fuzzers are broken, we only know about the first that was built
 - in the CI output, we only know that some fuzzers are broken; individuals who aren't contributors may not be able to see the log output
 - total time of build is significantly worse

For this reason, we should put fuzzer builds into a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) with each fuzzer listed. New fuzzers should be entered into this matrix.

**Comment by addisoncrump** [comment]
I would even like to see the separation of fmt and clippy tasks on fuzzers, if possible.

**Comment by tokatoka** [comment]
This is very easy..
1) make script/test_all_fuzzers.sh to accept an additional fuzzer name and run it.
2) put every fuzzer's name into matrix.fuzzer then it's done

**Comment by tokatoka** [comment]
#2010
