### ISSUE TITLE
`qemu.mappings()` returns invalid mapped memory region

### ISSUE THREAD

**Issue by psparc82** [AFLplusplus/LibAFL#2031]
Inside `snapshot.rs` we have the function that performs the QEMU snapshot:

```rust
 #[allow(clippy::uninit_assumed_init)]
  pub fn snapshot(&mut self, qemu: Qemu) {
      self.brk = qemu.get_brk();
      self.mmap_start = qemu.get_mmap_start();
      self.pages.clear();

      for map in qemu.mappings() {
          let mut addr = map.start();
         // snip
```

Calls to `snapshot()` will fail as `qemu.mappings()` always returns a junk entry after the final valid entry. 

For example if I run (to get the memory mappings of an example program): `qemu-arm ./busybox-armv6l cat /proc/self/maps` I get the following output, with `ffff0000-ffff1000` being the last mapping:

```
8000-117000 r-xp 00000000 08:01 11711166                                 /home/user/tools/LibAFL/fuzzers/test/busybox-armv6l
117000-11e000 ---p 00000000 00:00 0                                      
11e000-11f000 rw-p 0010e000 08:01 11711166                               /home/user/tools/LibAFL/fuzzers/test/busybox-armv6l
11f000-125000 rw-p 00000000 00:00 0                                      
40000000-40001000 ---p 00000000 00:00 0                                  
40001000-40801000 rwxp 00000000 00:00 0                                  [stack]
40801000-40802000 r-xp 00000000 00:00 0                                  [vdso]
ffff0000-ffff1000 r-xp 00000000 00:00 0 
```

Now running the same program via `libafl` and debugging the return value of `qemu.mappings()` shows the correct values being used all the way up to and including the last memory range (`ffff0000-ffff10000`), however `qemu.mappings()` returns an extra entry after the final mapping which is invalid and causes a panic. 

This extra entry contains random looking values each run, which then fail to be unpacked into an enum (causing a panic).

I don't know enough rust to attempt to fix this but it seems like an off by one.

Thanks!

**Comment by domenukk** [comment]
@rmalmain can you take a look?
