### ISSUE TITLE
Guidance on how to update libafl_qemu code

### ISSUE THREAD

**Issue by vringar** [AFLplusplus/LibAFL#2057]
https://github.com/AFLplusplus/LibAFL/pull/883/commits/0df4b76b87b129faa2c9defe02338b394d10ae3e removed the function `pub fn start(&self, cpu: &CPU)` which was used in old code I'm now trying to update to the latest LibAFL.

The function was used when loading from a custom snapshot [here](https://github.com/TeumessianFox/ASPFuzz/blob/6e1cc47c85c7a5ad94a432f7790e636a20f98464/fuzzer/libasp/src/reset_state.rs#L238-L242).

From my understanding of [one of the comments in the PR](https://github.com/AFLplusplus/LibAFL/pull/883#issuecomment-1318917257) is that this should be replaced with a call to `emu.run()` but this doesn't work either because `run`  now requires two additional arguments.

**Comment by domenukk** [comment]
@rmalmain can you give som info?

**Comment by rmalmain** [comment]
Now, `Emulator` is split into 2 different structures:
- `Qemu`: The low-level struct. It is initialized by calling `Qemu::init` like the old `Emulator::new` and mostly consists of native calls to qemu. It resembles a lot the old `Emulator` you used back in the time. An example systemmode fuzzer is available [here](https://github.com/AFLplusplus/LibAFL/blob/main/fuzzers/qemu_systemmode/src/fuzzer_classic.rs). 
- `Emulator`: the high-level struct. It is intended to be used as an abstraction of `Qemu` to avoid writing boilerplate code (like set / unset breakpoint by hand for example). You can find 2 variations of the previous fuzzer using this abstraction [here](https://github.com/AFLplusplus/LibAFL/blob/main/fuzzers/qemu_systemmode/src/fuzzer_breakpoint.rs) and [here](https://github.com/AFLplusplus/LibAFL/blob/main/fuzzers/qemu_systemmode/src/fuzzer_sync_exit.rs).

So, from what I can see in the link you sent, most things should work out of the box if you replace `Emulator` with `Qemu`, modulus some minor changes.

About the `pub fn start(&self, cpu: &CPU)`, it has been replaced with `pub unsafe fn run(&self)` in the `Qemu` struct. You can find more details [there](https://github.com/AFLplusplus/LibAFL/blob/main/libafl_qemu/src/emu/systemmode.rs#L325).

**Comment by vringar** [comment]
@rmalmain Thank you so much for taking a look and writing up this detailed guidance!
