### ISSUE TITLE
Rename AsMutSlice to AsSliceMut for consistency

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2059]
It's all in the name. Let's leave this for someone new who wants to get a foothold into contributing.

**Comment by saliaku** [comment]
Hi , I am interested, can u brief me on how to do this ?

**Comment by addisoncrump** [comment]
You need to change:
- `AsMutSlice` to `AsSliceMut`
- `as_mut_slice` (the associated method) to `as_slice_mut`

**Comment by addisoncrump** [comment]
Was this actually done?

**Comment by tokatoka** [comment]
done
