### ISSUE TITLE
Implement "ObserverRef" to avoid explicitly referring to observer types

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2064]
We saw this here: #1886

Basically, to access an observer, we currently have to explicitly refer to the type of the observer when fetching it with `match_name` and friends. We can sidestep this by defining an ObserverRef type, e.g.:

```rust
#[derive(Copy, Debug, Serialize, Deserialize)]
pub struct ObserverRef<T>(PhantomData<T>);
```

Then defining (default) in Observer:
```rust
pub fn make_reference(&self) -> ObserverRef<Self> {
  ObserverRef(PhantomData)
}
```

And finally defining a `MatchNameRef` blanket:
```rust
pub trait MatchNameRef {
  fn match_name_by_ref<T>(&self, name: &str, ref: ObserverRef<T>) -> Option<&T>;
}

impl<M> MatchNameRef for M where M: MatchName {
  fn match_name_by_ref<T>(&self, name: &str, ref: ObserverRef<T>) -> Option<&T> {
    self.match_name::<T>(name);
  }
}
```

In this way we can avoid ever explicitly referring to type names, since the type will be encoded in the `ObserverRef` wrapper and inferred.

**Comment by domenukk** [comment]
I think if we're doing this, we can have the ref also include the name, then we have a real 1:1 mapping of observer to the match, right? That'd be amazing
