### ISSUE TITLE
Unify constructors accepting names

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2071]
To be applied after #2065

We currently use each of the following in constructors for `Named` types:
- `&'static str`
- `String`
- `Cow<'static, str>`
- `S` with `where S: Into<String>`
- `S` with `where S: Into<Cow<'static, str>>`

We should unify this to a common interface. My vote is personally for the first, since we can enforce that people statically name their observers (which is generally preferable). If there are legitimate reasons we can think of that people might not want to, then we should go with the last (which uses the new Copy-on-Write pattern we're introducing in #2065).

**Comment by addisoncrump** [comment]
cc @tokatoka @domenukk, let's decide on this and then open it up to newcomers after #2065 lands.

**Comment by addisoncrump** [comment]
There is also actually another option here:
- `S` with `where S: AsRef<str>`

This might be the most idiomatic if we allow for non-static names.

**Comment by domenukk** [comment]
I don't think `&'static str` will work for dynamic types (?)

**Comment by domenukk** [comment]
I mean just in general? Like, this guy? https://github.com/AFLplusplus/LibAFL/blob/2df71e7a362cdd33c06755367e3ca710fa14154b/libafl_targets/src/coverage.rs#L190

**Comment by addisoncrump** [comment]
Right, that's how it's stored internally, not how we accept it as a parameter :sweat_smile:

**Comment by domenukk** [comment]
But users may want to pass in names dynamically (maybe?)
