### ISSUE TITLE
Use Reference in place of actual references in constructors

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2073]
To be completed after #2065.

We have a lot of places in the code base where we presently accept `&` references to observers and such. Where possible, we should unify to the use of `TypeRef` or `NamedTypeRef` so we can pass around type data and names when these types have already been consumed. This will ultimately allow us to move away from `match_name` and variants entirely to the unified `Ref` approach.

**Comment by domenukk** [comment]
IMHO the name should just be `Reference` (or similar), it references an Object, who cares how

**Comment by addisoncrump** [comment]
It was named to be consistent with Rust's `RefCell` fwiw

**Comment by addisoncrump** [comment]
I think this change actually might be negative. We can create the `Reference`s ourselves, no need to put undue burden on the user.
