### ISSUE TITLE
libafl_qemu does not support -enable-kvm option.

### ISSUE THREAD

**Issue by fourdim** [AFLplusplus/LibAFL#2087]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch: Yes.

Thank you for making LibAFL better!

**Describe the bug**

libafl_qemu does not support `-enable-kvm` option.

**To Reproduce**
1. change `fuzzers/qemu_systemmode` to support x86_64
```
libafl_qemu = { git = "https://github.com/AFLplusplus/LibAFL.git", features = ["x86_64", "systemmode"] }
libafl_qemu_sys = { git = "https://github.com/AFLplusplus/LibAFL.git", features = ["x86_64", "systemmode"] }
```
```rust
// .map(|cpu| -> Result<u32, String> { cpu.read_reg(Regs::Pc) });
.map(|cpu| -> Result<u64, String> { cpu.read_reg(Regs::Pc) });
```
2. add `-enable-kvm` option to the command line.

**Expected behavior**

Fuzzer can run under kvm mode. The same parameters worked with `qemu-system-x86_64`.

**Screen output/Screenshots**
If applicable, add copy-paste of the screen output or screenshot that shows the issue. Please ensure the output is in **English** and not in Chinese, Russian, German, etc.

<img width="722" alt="image" src="https://github.com/AFLplusplus/LibAFL/assets/59462000/84afc31b-8da5-49f9-9439-b387c02416d3">

**Additional context**

**Comment by rmalmain** [comment]
We do not support KVM in `libafl_qemu` at the moment.
It's a work in progress and requires significant work, so we will need some time before we can make it available.
