### ISSUE TITLE
Delete MOptStage and put the MOpt code from the MOpt stage into mutator.post_exec

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#209]
In hindsight, I can utilize mutator.post_exec instead of putting code into a Stage.
with this change, the implementation would be cleaner

**Comment by tokatoka** [comment]
Furthermore, after removing MOpt stage, we can combine the power schedule with the MOpt mutator pretty easily (PowerMutationalStage + StdMOptMutator).

**Comment by andreafioraldi** [comment]
Great!
