### ISSUE TITLE
in SimpleRestartingEventManager the execution count should be restored after respawn

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#210]
![Screenshot at 2021-07-08 11-55-20](https://user-images.githubusercontent.com/16168186/124902629-66c9bf00-dfe3-11eb-817c-75a042b45252.png)

**Comment by domenukk** [comment]
I guess that's the stats that are not reset, right? The corpus should still be there but the stats don't know about it

**Comment by andreafioraldi** [comment]
Yep

**Comment by domenukk** [comment]
The size is now restored, however I have no idea how to restore the exec count without dirty static variables or something

**Comment by andreafioraldi** [comment]
> The size is now restored, however I have no idea how to restore the exec count without dirty static variables or something

is this still a thing? can you investigate it?

**Comment by domenukk** [comment]
The solution here would probably be to serialize the current stats to a file(?)
However, the crash handler doesn't know about the Monitor, so I still don't really know how it could be done cleanly

**Comment by domenukk** [comment]
I think we fixed this (partly?)
