### ISSUE TITLE
Switch (named) metadata to use Cow instead of String

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2103]
We did a refactor recently that replaces a lot of uses of String with Cow. We should do the same for the metadata maps, since there's a lot of unnecessary coercion into allocations.

**Comment by Nereuxofficial** [comment]
I would love to contribute by fixing this issue, however as i have never worked with the code i may need some help. 

I assume the metadata to wrap in Cow is [the metadata in the Testcase struct](https://github.com/AFLplusplus/LibAFL/blob/602bce446f8087cc49cd56aa323bff9f3db14c0d/libafl/src/corpus/testcase.rs#L54). 

The Cow structure is in std or alloc but as this project also targets no_std so it may be an option to create a trait for the MetaDataMap and implement it for no_std as well as std. Would this be what you imagined?

**Comment by addisoncrump** [comment]
We use `extern crate alloc`, so this shouldn't be an issue. It should be a matter of simply replacing the usage of String with Cow, yes :)

**Comment by addisoncrump** [comment]
Sorry for the confusion here.

We want to replace [this usage of String](https://github.com/AFLplusplus/LibAFL/blob/main/libafl_bolts/src/serdeany.rs#L24) and [this usage of String](https://github.com/AFLplusplus/LibAFL/blob/main/libafl_bolts/src/serdeany.rs#L445) with Cow, since these strings will primarily be static.

**Comment by Nereuxofficial** [comment]
Thanks for the clarification!
