### ISSUE TITLE
Revisit adaptive serialization

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2114]
The adaptive serialization feature (introduced here: #1227) seems untested and potentially unused. We should see if this is being used or should be enabled by default.

**Comment by tokatoka** [comment]
we used / it was written for our paper

**Comment by addisoncrump** [comment]
So, if it's performant and published, why isn't it enabled by default?

**Comment by tokatoka** [comment]
you can make it default
