### ISSUE TITLE
QASAN false positives out-of-bound accesses in mmap'ed regions 

### ISSUE THREAD

**Issue by cube0x8** [AFLplusplus/LibAFL#2116]
**Description**
I'm facing a situation where my QEMU target allocates a big chunk on the heap using `malloc`, then `free`s it and, later in the execution, `mmap` is called and a memory region that overlaps the old big heap region is returned. Due to the last `free`, that memory region results to be _poisoned_ and asan raises a `write_8` error when the target tries to write to it.

This happens because `mmap` and `munmap` are not hooked in `libqasan`. Moreover, `malloc` might call `mmap` to allocate a chunk of memory, so it could happen that a call to `mmap` would return a region that overlaps an old `malloc`ed chunk.

**To Reproduce**
I don't have a toy program to reproduce this issue, but I guess it would be enough to call `mmap` with a specific heap address that has been freed before:
```
void *p = malloc(big_size);
free(p);
void *p2 = mmap(p, ...);
(char *)p2[0] = 'A';
```

**Expected behavior**
`mmap/munmap` are hooked in `libqasan` as `malloc` and `free`. A call to `mmap` should unpoison a region, a call to `munmap` should poison it.

**Additional context**
I'm trying to add the hooks for `mmap` and `munmap` in `libqasan`. Hints and suggestions are very welcome.

**Comment by tokatoka** [comment]
This is fixed already?
I saw your pr with mmap hook merged

**Comment by cube0x8** [comment]
Yes it is!
