### ISSUE TITLE
no_std not working with aarch64-unknown-none

### ISSUE THREAD

**Issue by bitwave** [AFLplusplus/LibAFL#212]
I tried to build LibAfl in no_std mode under the above mentioned targets.

**To Reproduce**
1. `cargo +nightly build -Zbuild-std=core,alloc --target aarch64-unknown-none -v --release`

**Expected behavior**
project builds and links correctly

**Additional context**

I found out, that
- tuple_list
- hostname
- core_affinity

all need the std crate.

Additonally 
- hashbrown
- num
- erased-serde (needs feature `alloc`)
- num_enum
- ashash

need `default-features=false` to compile under `no_std`.

serde_json needs to be replace by serde-json-core

**Example error**
```
error[E0463]: can't find crate for `std`
  |
  = note: the `aarch64-unknown-none` target may not support the standard library
  = note: `std` is required by `num` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

**Comment by s1341** [comment]
I think this is possibly because we (or the crates we depend upon) don't differentiate sufficiently between `aarch64-linux-android` and `aarch64-linux-none`?

**Comment by andreafioraldi** [comment]
For libafl you have to select the features to build for no_std. By default, we assume std https://github.com/AFLplusplus/LibAFL/blob/main/libafl/Cargo.toml#L39

**Comment by andreafioraldi** [comment]
Follow https://github.com/AFLplusplus/LibAFL/pull/214
