### ISSUE TITLE
High level Sugar API

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#213]
We need high level API to create basic fuzzers for basic users without involving the concept of Observer Feedback etc. Ideally just taking an haress closure and some parameters like input output folders etc.

I started working on the libafl_sugar crate in https://github.com/AFLplusplus/LibAFL/tree/high_level

**Comment by domenukk** [comment]
What Sugars do we want?
Each with cmplog, where possible:
- frida instrumentation
- qemu instrumentation
- llvm compiled
Then
- Provide harness, coverage map, no cmplog
...?

**Comment by andreafioraldi** [comment]
TODO add Atheris to sugar and expose a python API to fuzz python from python

**Comment by domenukk** [comment]
We have a high-level sugar API now. It needs some love and documentation, but it's there.
