### ISSUE TITLE
Short stage names for AFLOnDiskCorpus

### ISSUE THREAD

**Issue by R9295** [AFLplusplus/LibAFL#2179]
For the introduction of AFLOnDiskCorpus, stages need a "short name" since AFL++ uses ``stage_short`` when naming the testcase filename.

Currently, many stages implement ``Named`` eg:
https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/stages/concolic.rs#L52-L57
``` rust
impl<EM, TE, Z> Named for ConcolicTracingStage<'_, EM, TE, Z> {
    fn name(&self) -> &Cow<'static, str> {
        static NAME: Cow<'static, str> = Cow::Borrowed("ConcolicTracingStage");
        &NAME
    }
}
```

But have "Stage" prepended and are PascalCase. For ``ColorizationStage``, the name is not hard-coded.
``` rust 
impl<C, E, EM, O, Z> Named for ColorizationStage<C, E, EM, O, Z>
where
    E: UsesState,
{
    fn name(&self) -> &Cow<'static, str> {
        self.map_observer_handle.name()
    }
}
```

Some solutions:
1. Create a ``"afl"`` feature which mandates a ``StageShort`` implementation for all Stages. Puts the AFLOnDiskCorpus as part of the feature too (likely)
2. Do the same as above but without the feature. (unlikely)
3. replace all ``Named`` implementations with the one AFL++ expects (unlikely)

**Comment by domenukk** [comment]
The YOLO solution would be to have a name mapping inside `AFLOnDiskCorpus`, it would keep the changes local, what do you think?

**Comment by R9295** [comment]
I thought of this too but it would break anytime the name of the stage changes, making AFLOnDiskCorpus usage outside of libafl-fuzz difficult.

Also, for ColorizationStage, which uses the ``map_handle``, the name becomes unpredictable.

**Comment by domenukk** [comment]
How about we make all names (optionally) dynamic, and then add the option to manually specify the stage name? Then the aflpp implementation can just pick the "right ones"

**Comment by R9295** [comment]
I'm not sure I understand.
