### ISSUE TITLE
Make CommandExecutorBuilder flexible enough to deal with Input types other than BytesInput

### ISSUE THREAD

**Issue by riesentoaster** [AFLplusplus/LibAFL#2182]
(Follow up to #2158 and #2167)

I like the new Builder Interface, and especially the interaction with `StdoutObserver`/`StderrObserver` makes much more sense now. So: Mission accomplished on that front.

However, this solution is only applicable on `BytesInput`s. For any other input, I'll basically have to rewrite the entire executor, which seems like a lot of duplicate work. Specifically, I need to map my custom `Input` implementation to a combination of (multiple) args and stdin. I'm doing this a bit hacky by forcing my Input to implement this trait ([source](https://github.com/riesentoaster/LibAFL/blob/main/fuzzers/coreutils_coverage/src/generic/executor.rs#L54C1-L59C1)):

```rust
pub trait ExtractsToCommand: Serialize {
    fn get_stdin(&self) -> &Vec<u8>;
    fn get_args<'a>(&self) -> Vec<Cow<'a, OsStr>>;
}
```

I'm not sure on the best solution to this yet, this might not be the right approach in the context of a builder pattern. Instead it could maybe accept a closure to map the input to the stdin and one to map it to args? What do you think?

**Comment by tokatoka** [comment]
yeah your solution looks good to me

**Comment by riesentoaster** [comment]
Actually, on further thought, I'm not sure this makes sense. Just having the trait doesn't work since then `InputLocation` couldn't be used anymore and any logic using closures would require complex code in both the builder and `StdCommandConfigurator`. I think the right way to deal with this would still be to just write a custom `CommandConfigurator`. Let the builder be simple for the simple use cases and if things get more complex, let people have full control directly.

Closing this issue based on my thoughts. Feel free to reopen if you still want to do something about it.
