### ISSUE TITLE
Docs fail to build

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#2187]
Multiple docs don't build with LibAFL 0.12, we really need to fix those!

* https://docs.rs/crate/libafl_frida/latest
* https://docs.rs/crate/libafl_libfuzzer/latest
* https://docs.rs/crate/libafl_qemu/latest
* https://docs.rs/crate/libafl_sugar/latest

**Comment by domenukk** [comment]
LibAFL Sugar error:
```rust
[INFO] [stderr] error: features "arm" and "aarch64" cannot be used together
[INFO] [stderr]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/libafl_qemu_sys-0.12.0/build_linux.rs:11:13
```

**Comment by domenukk** [comment]
LibAFL qemu error (cc @rmalmain ):
```rust
[INFO] [stderr] warning: target filter specified, but no targets matched; this is a no-op
[INFO] [stderr] warning: libafl_qemu@0.12.0: CROSS_CC is not set, default to cc (things can go wrong if the selected cpu target (x86_64) is not the host arch (x86_64))
[INFO] [stderr]  Documenting libafl_qemu v0.12.0 (/opt/rustwide/workdir)
[INFO] [stderr] error: couldn't read /opt/rustwide/target/x86_64-unknown-linux-gnu/debug/build/libafl_qemu-c3eef6624c52b019/out/backdoor_bindings.rs: No such file or directory (os error 2)
[INFO] [stderr]   --> src/command.rs:37:5
[INFO] [stderr]    |
[INFO] [stderr] 37 |     include!(concat!(env!("OUT_DIR"), "/backdoor_bindings.rs"));
[INFO] [stderr]    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr]    |
[INFO] [stderr]    = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)
[INFO] [stderr] 
[INFO] [stderr] The following warnings were emitted during compilation:
[INFO] [stderr] 
[INFO] [stderr] warning: libafl_qemu@0.12.0: CROSS_CC is not set, default to cc (things can go wrong if the selected cpu target (x86_64) is not the host arch (x86_64))
[INFO] [stderr] 
[INFO] [stderr] error: could not document `libafl_qemu`
```

**Comment by domenukk** [comment]
LibAFL frida error (@s1341 we probably need a `clippy` pass that doesn't download anything since it's sandboxed?)
```rust
[INFO] [stderr] warning: frida-gum-sys@0.13.6: Frida gum devkit not found, downloading from https://github.com/frida/frida/releases/download/16.2.1/frida-gum-devkit-16.2.1-linux-x86_64.tar.xz...
[INFO] [stderr] 
[INFO] [stderr] error: failed to run custom build command for `frida-gum-sys v0.13.6`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/frida-gum-sys-7a2021473556c2d5/build-script-build` (exit status: 101)
[INFO] [stderr]   --- stdout
[INFO] [stderr]   cargo:rerun-if-changed=build.rs
[INFO] [stderr]   cargo:rerun-if-changed=event_sink.c
[INFO] [stderr]   cargo:rerun-if-changed=event_sink.h
[INFO] [stderr]   cargo:rerun-if-changed=invocation_listener.c
[INFO] [stderr]   cargo:rerun-if-changed=invocation_listener.h
[INFO] [stderr]   cargo:rerun-if-changed=probe_listener.c
[INFO] [stderr]   cargo:rerun-if-changed=probe_listener.h
[INFO] [stderr]   cargo:rustc-link-search=/opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/frida-gum-sys-0.13.6
[INFO] [stderr]   cargo:warning=Frida gum devkit not found, downloading from https://github.com/frida/frida/releases/download/16.2.1/frida-gum-devkit-16.2.1-linux-x86_64.tar.xz...
[INFO] [stderr] 
[INFO] [stderr]   --- stderr
[INFO] [stderr]   thread 'main' panicked at /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/frida-build-0.13.6/src/lib.rs:59:52:
[INFO] [stderr]   devkit download request failed: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/frida/frida/releases/download/16.2.1/frida-gum-devkit-16.2.1-linux-x86_64.tar.xz", query: None, fragment: None }, source: Error { kind: Connect, source: Some(ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })) } }
```

**Comment by s1341** [comment]
that's going to be difficult... we need to get a devkit *somehow*....

**Comment by domenukk** [comment]
> that's going to be difficult... we need to get a devkit _somehow_....

@s1341 Not really, it doen't need to function properly for the docs to build, right? It just needs to build the rust parts. That's roughly how libafl_qemu does it

**Comment by s1341** [comment]
The rust will not build without the devkit. It generates bindings from a header shipped in the devkit and links with a library shipped in the devkit.

**Comment by rmalmain** [comment]
> LibAFL qemu error (cc @rmalmain ):
> 
> ```rust
> [INFO] [stderr] warning: target filter specified, but no targets matched; this is a no-op
> [INFO] [stderr] warning: libafl_qemu@0.12.0: CROSS_CC is not set, default to cc (things can go wrong if the selected cpu target (x86_64) is not the host arch (x86_64))
> [INFO] [stderr]  Documenting libafl_qemu v0.12.0 (/opt/rustwide/workdir)
> [INFO] [stderr] error: couldn't read /opt/rustwide/target/x86_64-unknown-linux-gnu/debug/build/libafl_qemu-c3eef6624c52b019/out/backdoor_bindings.rs: No such file or directory (os error 2)
> [INFO] [stderr]   --> src/command.rs:37:5
> [INFO] [stderr]    |
> [INFO] [stderr] 37 |     include!(concat!(env!("OUT_DIR"), "/backdoor_bindings.rs"));
> [INFO] [stderr]    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [INFO] [stderr]    |
> [INFO] [stderr]    = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)
> [INFO] [stderr] 
> [INFO] [stderr] The following warnings were emitted during compilation:
> [INFO] [stderr] 
> [INFO] [stderr] warning: libafl_qemu@0.12.0: CROSS_CC is not set, default to cc (things can go wrong if the selected cpu target (x86_64) is not the host arch (x86_64))
> [INFO] [stderr] 
> [INFO] [stderr] error: could not document `libafl_qemu`
> ```

this error should not occur anymore, we are generating the stub for this one.
is there a way to test it without making a new release?

**Comment by tokatoka** [comment]
#2154 fixed libafl_libfuzzer i think

**Comment by domenukk** [comment]
> The rust will not build without the devkit. It generates bindings from a header shipped in the devkit and links with a library shipped in the devkit.

We will need to ship stub bindings like in qemu

**Comment by langston-barrett** [comment]
> is there a way to test it without making a new release?

Could do a pre-release?

**Comment by rmalmain** [comment]
> > is there a way to test it without making a new release?
> 
> Could do a pre-release?

It's a good idea, not sure if this has been done before or if it would be easy to integrate
