### ISSUE TITLE
SIGINT does not stop fuzzing with libafl_libfuzzer_runtime

### ISSUE THREAD

**Issue by maxammann** [AFLplusplus/LibAFL#2191]
**Describe the bug**
I'm using the drop-in replacement to fuzz a C++ program like that:

```
clang++ -DNO_MAIN -g -O2 -fsanitize=fuzzer-no-link libFuzzer.a harness.cc main.cc -o fuzz
```

When I do: `./fuzz -tui=1` or `./fuzz -fork=1 -ignore_crashes=1` I'm no longer able to stop the fuzzing using CTRL+C without killing the processes.

**To Reproduce**
1. Compile libFuzzer.a
2. Compile the program using the above command.
3. Do `./fuzz -tui=1`

**Expected behavior**
SIGINT is handled.

**Comment by maxammann** [comment]
Might be related to https://github.com/AFLplusplus/LibAFL/pull/2124

**Comment by tokatoka** [comment]
for `./fuzz -fork=1 -ignore_crashes=1`
i can stop the fuzzer.

for `./fuzz -tui=1`, 
in order to ctrl+c, you have to press `q` to exit the tui screen first. (but this somehow isn't working)
but considering the fact that non-tui mode works, i guess it's more of a tui issue.

**Comment by maxammann** [comment]
Ah true, actually pressing `q` works for me.

I think my issue is that my target is crashing a lot. So the timeframe when ctrl+c works is probably quite small and that stops me from exiting.

e.g.

```
#include <stdint.h>
#include <stddef.h>

void check_buf(char *buf, size_t buf_len);

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  check_buf((char*) data, size); // Invoke the SUT; in our case that is the check_buf function
  return 0; // Return 0, which means that the test case was processed correctly
}
```

```
#include <stdlib.h>
#include <string.h>

void check_buf(char *buf, size_t buf_len) {
    if(buf_len > 0 && buf[0] == 'a') {
        if(buf_len > 1 && buf[1] == 'b') {
            if(buf_len > 2 && buf[2] == 'c') {
                abort();
            }
        }
    }
}

#ifndef NO_MAIN
int main() {
    char target[] = "123";
    size_t len = strlen(target);
    check_buf(target, len);
    return 0;
}
#endif // NO_MAIN
```

**Comment by tokatoka** [comment]
also for some reason i have to press it long for this specific fuzzer. (idk why 🤷 )
