### ISSUE TITLE
Minimizers

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#221]
We currently don't have anything like `tmin` and `cmin`.
Corpus minimization should be straight forward to implement using an observer and a custom run function.

Tmin will need some additional work.

**Comment by d80ep08th** [comment]
I find this issue interesting but I cant figure out what tmin and cmin are, googling them took me to this [link](https://github.com/google/AFL/blob/master/afl-cmin)  . 

So how exactly does this issue get solved?

**Comment by domenukk** [comment]
Yes, the relevant tools are [tmin](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-tmin.c) and [cmin](https://github.com/AFLplusplus/AFLplusplus/blob/stable/afl-cmin) (traditionally based  on[ afl-showmap](https://github.com/AFLplusplus/AFLplusplus/blob/stable/src/afl-showmap.c)).
On a high-level their idea is simple:
cmin reruns all testcases in the corpus, and keeps a minimal set with that still reaches all edges / produces the same observer state overall
tmin reruns a single testcase, overwriting and leaving out byte regions, in order to create a minimal sized testcase with the same map/observer state.
Hope this clarifies it a bit.

**Comment by d80ep08th** [comment]
Okay , that does give me some clarity.

**Comment by syheliel** [comment]
@d80ep08th do you have any progress on it? I'm also interested in the problem and feel free if you1 have some findings.

**Comment by chinggg** [comment]
I find there has been [MinimizerCorpusScheduler](https://docs.rs/libafl/latest/libafl/corpus/minimizer/struct.MinimizerCorpusScheduler.html), which will compute a subset during fuzzing process. Since LibAFL aims to be a library, I think the expected result of this issue will be something like `CMin::new(&feedback).minimize(corpus)`? Or just a cli tool like `afl-cmin`?

**Comment by syheliel** [comment]
`MinimizerCorpusScheduler` is not avaliable in current code, now it's called `libafl::schedulers::minimizer::MinimizerScheduler`

**Comment by domenukk** [comment]
> I find there has been [MinimizerCorpusScheduler](https://docs.rs/libafl/latest/libafl/corpus/minimizer/struct.MinimizerCorpusScheduler.html), which will compute a subset during fuzzing process. Since LibAFL aims to be a library, I think the expected result of this issue will be something like `CMin::new(&feedback).minimize(corpus)`? Or just a cli tool like `afl-cmin`, which is a bash script wrapping `afl-showmap`?

I think ideally it would be a stage. The cmin stage would ignore the corpus idx and work on the whole corpus, the tmin stage uses the corpus idx.
That way we can mix and match them during fuzzing, too.
What do you think @andreafioraldi

**Comment by andreafioraldi** [comment]
> 

tmin for sure a stage, cmin can be a combination of corpus scheduler and a stage that simply save as objective the testcase taken from the scheduler

A naive version of cmin is simply take any testcase marked as favored by the minimizer scheduler
