### ISSUE TITLE
Switch to anyhow errors

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#222]
Dunno if it is a good idea, but anyhow https://github.com/dtolnay/anyhow is no_std

**Comment by domenukk** [comment]
The docs say 
> `no_std` mode will require an explicit `.map_err(Error::msg)` when working with a non-Anyhow error type inside a function that returns Anyhow's error type.
So there's definitely going to be some code changes needed to use anyhow.
Anyhow, it could be useful, I've heared good things

**Comment by f0rki** [comment]
(I'm just randomly dropping by) anyhow is nice, but I read [on the internet](https://nick.groenen.me/posts/rust-error-handling/#libraries-versus-applications) that it is not recommended for libraries and instead the [thiserror](https://crates.io/crates/thiserror) crate provides an easy way to create meaningful error types.

**Comment by domenukk** [comment]
I stumbled over this comment, too, however `thiserror` is closely tied to `std::io::Error`, so not an option for `no_std`...

**Comment by maxammann** [comment]
Is there a major issue with the current error handling? I think the error handing in LibAFL is the most common/default way of doing things.

There are also changes coming from Rust side: https://blog.rust-lang.org/inside-rust/2021/07/01/What-the-error-handling-project-group-is-working-towards.html

**Comment by domenukk** [comment]
I don't think we need to switch atm, let's wait for what future rust brings
