### ISSUE TITLE
GNU assembler does not recognize `.dword` in `libafl_qemu.h`

### ISSUE THREAD

**Issue by nine-point-eight-p** [AFLplusplus/LibAFL#2249]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch

Thank you for making LibAFL better!

**Describe the bug**
I'm working on a fuzzer under x86-64 using sync exits provided by qemu system mode. I use GCC 11.4.0 to compile the target. It seems that GNU assembler does not recognize the directive `.dword` in the header `libafl_qemu.h`. It can be easily fixed by replacing `.dword` with `.4byte` or `.long`.

**To Reproduce**
1. Include `libafl_qemu.h` in some source files and compile with GCC.

**Expected behavior**
The output is like:
```
test.c: Assembler messages:
test.c:10: Error: unknown pseudo-op: `.dword'
```

**Comment by domenukk** [comment]
It's a bit surprising... but anyway sounds we can change it without anything breaking @rmalmain ?

**Comment by rmalmain** [comment]
> It's a bit surprising... but anyway sounds we can change it without anything breaking @rmalmain ?

the header file is undertested on linux full-system targets for now, we used it mostly for windows and arm atm.
I added a small test to catch future problems like this one, thanks for the report.
