### ISSUE TITLE
`Launcher` does not work with `MmapShMemProvider`

### ISSUE THREAD

**Issue by momvart** [AFLplusplus/LibAFL#2277]
**Describe the bug**
When using `MmapShMemProvider` as the shared memory provider for `Launcher`, errors get thrown because of bad file descriptors.

**To Reproduce**
1. Build an instance of `events::launcher::Launcher` with an instance of `MmapShMemProvider` as the shared memory provider.
2. Launch it and receive errors.
3. Use an instance of `StdShMemProvider` instead.
4. Launch it and see it works.

**Expected behavior**
All shared memory providers to be consumable for the launcher.

**Screen output/Screenshots**
```log
Failed to run launcher: OsError(Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }, "mmap() failed for map with fd 4", ErrorBacktrace)
```

**Comment by tokatoka** [comment]
@domenukk 
can you take a look?

**Comment by domenukk** [comment]
What OS? I don't think all shmem providers can work on all operating systems in all setups, just because for example shared memory on MacOS is very broken. What's your use case?
As a simple "fix", could you try if it works without the "fork" feature(?)

**Comment by riesentoaster** [comment]
I've run into the same issue before on Ubuntu 22.04.04. Working with `MmapShMem`/`MmapShMemProvider` works in other contexts on the same OS.

**Comment by momvart** [comment]
> What OS?

I tested in Fedora 40. I'm not sure if I also tested it in Ubuntu. But `MmapShMemProvider` is working fine with other parts of our fuzzer. `Launcher` is the first one throwing this error.

**Comment by tokatoka** [comment]
@momvart 
can you run again with libafl_bolts's `errors_backtrace` feature and RUST_BACKTRACE=full ?

**Comment by tokatoka** [comment]
The problem is that;
when you use MmapShMemProvider, you use file descriptor to connecto to another process.
However when you use `Launcher`, the broker spawns (whether fork() or not does not matter) the clients, then after that, initialize the shared memory (to create the broker).
This means that the clients are not inherited with the fd that is need to connect to the shmem.

**Comment by tokatoka** [comment]
I fixed it.

**Comment by tokatoka** [comment]
i fixed but there's one limitation. whenver the fuzzing is over it's the user's responsibility to delete the files used to back shmem lying in /dev/shm

**Comment by momvart** [comment]
Thanks for your quick check and fix!
