### ISSUE TITLE
Executors which wrap other executors double count executions

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2288]
This is because of a lack of clarity on who is responsible for counting. We should clarify this in documentation and clean up the double counts.

TBD after #2283

**Comment by domenukk** [comment]
Should always be the inner most, right?

**Comment by addisoncrump** [comment]
What if there are multiple innermost? (e.g., differential)

**Comment by tokatoka** [comment]
#2330 fixes it. 
now it only increments only if it really runs it. (e.g. call to harness_fn)
