### ISSUE TITLE
Find a mechanism to enforce Metadata dependencies

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#23]
At the current state, we don't have any mechanism to enforce the presence of some testcase or state metadata apart from returning errors at runtime when one component that needs such metadata want to use it without success.

Can we enforce this earlier in the code, e.g. when the component is created? Or even at compile time maybe?

**Comment by evanrichter** [comment]
the presence of a testcase could be done at compile time perhaps with `include_bytes!("../corpus/testcase1")` but then compile-time and runtime could potentially diverge if that file changes or disappears

**Comment by domenukk** [comment]
Feedbackstate has been refactored so this isn't really needed anymore, I think. Closing
