### ISSUE TITLE
Documentation for libdesyscall

### ISSUE THREAD

**Issue by langston-barrett** [AFLplusplus/LibAFL#2306]
#1221 was recently merged. Looks very interesting, but I'm not sure how I would begin to use it. Could use some documentation!

**Comment by tokatoka** [comment]
this is the a module for a paper we are working right now.
we'll add examples once it is accepted 😉

**Comment by langston-barrett** [comment]
Was there ever a paper about this?

**Comment by tokatoka** [comment]
sure, remove
