### ISSUE TITLE
Fuzzer should have init_state() method

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#2431]
todo for after generic refactor

fuzzer should have a simple init_state() method that calls feedback.init_state and objectives.init_state()
currently we do it in side state::new(), but this feels odd

**Comment by domenukk** [comment]
Why is it odd to initialize the state in State::new()? Feels somewhat correct to me

**Comment by tokatoka** [comment]
state::new() is a constructor for the `StdState`. it has nothing to do with the metadata initialization

**Comment by domenukk** [comment]
Shouldn't the state be returned fully initialized?
Or do you want to move the init method to the State trait?

**Comment by tokatoka** [comment]
> Or do you want to move the init method to the State trait?

yes this is more correct.
