### ISSUE TITLE
Deduplicate code in map observers

### ISSUE THREAD

**Issue by addisoncrump** [AFLplusplus/LibAFL#2446]
Nearly all of the `MapObserver` implementations seem to be copy/pasted, and there is a lot of old code that is no longer needed. Duplicated code should be extracted to common methods where >5 lines.

**Comment by sarthakvyas16** [comment]
i will work on this issue please assign me this issue.

**Comment by domenukk** [comment]
We don't really assign issues, but feel free to work on it. Thanks! :)

**Comment by domenukk** [comment]
Depends on the quality of your PRs and you proposal

**Comment by tokatoka** [comment]
this turned out to be impossible because Deref didn't work?
