### ISSUE TITLE
[Question] Is libfuzzer-best still the recommended branch for libfuzzer targets? 

### ISSUE THREAD

**Issue by 0xddom** [AFLplusplus/LibAFL#2464]
As the title says, is it still the recommended one? Considering that:
1. It hasn't been updated in 4 months
2. [#2372](https://github.com/AFLplusplus/LibAFL/issues/2372) was closed a couple weeks ago

I'm not sure if it still is. If not, can you update the documentation to reflect the current status of libfuzzer support in LibAFL?

**Comment by addisoncrump** [comment]
It is not! I'll remove the branch update the info to point to main.
