### ISSUE TITLE
Is there a more detailed readme about qemu mode here?

### ISSUE THREAD

**Issue by DelCoding** [AFLplusplus/LibAFL#247]
strongly recommended to improve the documentation!

**Comment by domenukk** [comment]
Yes you are right, so far the documentation is minimal / the code.
That's how you could use it:
https://github.com/AFLplusplus/LibAFL/blob/2282b09ef5a5a1df28daaba94b76344a56e63a83/fuzzers/fuzzbench_qemu/src/fuzzer.rs#L146

**Comment by DelCoding** [comment]
there are my steps:
1. in `LibAFL` root src dir, do `cargo build --release`
2. cd `fuzzer/fuzzbench_qemu`, do `cargo build --release`
3. also in fuzzbench_qemu, do `make`, this can make `qemu-libafl-bridge`, and output qemu-x86_64
4. compile a simple fuzz.c with clang/gcc
5. run
```
❯ ./build/qemu-x86_64 ./fuzzer --libafl-in ./src --libafl-out ./out
Workdir: "/home/fuzz/LibAFL/fuzzers/fuzzbench_qemu"
Out dir at "./out" already exists.
LLVMFuzzerTestOneInput @ 0x4004d0

```
6. fuzzer exit
but seem like i can't entry `fuzz_loop`?

**Comment by tokatoka** [comment]
You should pass both fuzz.c *and* target/release/libfuzzbench_qemu.a to the compiler, I guess :>

**Comment by tokatoka** [comment]
It works for me with clang
What do you mean by `fuzzer exit`, does it hang or die with an error?

**Comment by DelCoding** [comment]
that is say fuzzer seem like normal exit, not hang or error message, also not entry fuzzing lop. just like run one time, and all of output is above.

**Comment by domenukk** [comment]
Is there anything else we can do here, apart from improving the overall docs (which is an onging project)?
Qemu mode works for us, please reopen the issue if needed (and be more precise)
