### ISSUE TITLE
How to add custom metadata for solution?

### ISSUE THREAD

**Issue by Slava0135** [AFLplusplus/LibAFL#2556]
I have a differential fuzzer that reads output from stdout and compares it.
I want to save the stdout in metadata so I can check the output of programs without rerunning them, but unable to figure out how to do so.

**Comment by domenukk** [comment]
You can `eager_or` an extra ToMetadata feedback that will do nothing but append metadata. Specifically, this one: `StdOutToMetadataFeedback` 
https://github.com/AFLplusplus/LibAFL/blob/4e54182b357403474edeaf36774502e7bf988e6a/libafl/src/feedbacks/stdio.rs#L107

**Comment by Slava0135** [comment]
I decided save data to `Feedback` struct and then use it in `append_metadata`, maybe this should be put in function description (unless this is not intentional way of doing things). I first thought it wouldn't be called for solution (only for corpus).

**Comment by domenukk** [comment]
Feel free to open a PR to add documentation :)
