### ISSUE TITLE
DrCovModule is exclusive to user-mode

### ISSUE THREAD

**Issue by vringar** [AFLplusplus/LibAFL#2572]
The issue exists in 17def039

**Describe the bug**

Previously the `QemuDrCovHelper`  could be used in Systemmode and was critical to the way we worked.
#2267 moved the `DrCovModule` into the `usermode`  module making it inaccessible for our usecase.

**To Reproduce**
1. Look where [drcov.rs](https://github.com/AFLplusplus/LibAFL/blob/main/libafl_qemu/src/modules/usermode/drcov.rs) is in the tree
2. See [the conditional inclusion of this module](https://github.com/AFLplusplus/LibAFL/blob/main/libafl_qemu/src/modules/mod.rs#L9-L12)

**Expected behavior**

I expect this module to be available in systemmode as well.

**Additional context**

I'm sorry if there is a technical reason why this only works in usermode, I'll move the `DrCovModule`  to the generic `modules` and see what happens. However, I still wanted to open the issue, so maybe you can tell me, why I shouldn't do this.

**Comment by rmalmain** [comment]
no worries, thanks for pointing out the issue! once the ci is happy i'll merge the patch
