### ISSUE TITLE
missing the linux builder repository

### ISSUE THREAD

**Issue by juniorprincewang** [AFLplusplus/LibAFL#2590]
The linux builder repository (https://github.com/AFLplusplus/linux-qemu-image-builder) in LibAFL QEMU Systemmode for Linux process fuzzing is missing.

**Comment by rmalmain** [comment]
yes we are aware of this, we wanted to make this public a bit later.
for now we only made the fuzzer available.
thank you for the report, i'll make it explicit in the READMEs
