### ISSUE TITLE
Are libafl_bolts Cargo.toml fetures dependencies upside-down?

### ISSUE THREAD

**Issue by Marcondiro** [AFLplusplus/LibAFL#2638]
Looks like that the dependency between feature flags is flipped in libafl_bolts.
For instance:
https://github.com/AFLplusplus/LibAFL/blob/0f744a3abbf35834e66bd369ebad7fa91ca61bee/libafl_bolts/Cargo.toml#L45-L57

Shouldn't it be the opposite? like:
```toml
serde_json = ["std"]
```

So that the features that need `std` enable `std` and not like enabling `std` enables all the features requiring it.

**Comment by domenukk** [comment]
It's correct, this specifies our feature (or I'm missing something ?)

Like: `std` is the feature of libafl_bolts, so you can do `--features=std` when building libafl_bolts - and that will, in turn, enable `serde_json` and `serde_json/std` support.
Likely in this special case we could enable serde_json no-std for `alloc`

**Comment by domenukk** [comment]
Ah, do you  want to have a libafl_bolts with `std` but without serde_json?

**Comment by Marcondiro** [comment]
Yeah usually std has no dependencies and has a lot of dependents

**Comment by domenukk** [comment]
Well we don't really have a serde_json feature right now, it's just a dependency that's enabled in std.

That being said, looks like it's not even used anymore :D https://github.com/AFLplusplus/LibAFL/blob/0f744a3abbf35834e66bd369ebad7fa91ca61bee/libafl_bolts/src/serdeany.rs#L273

**Comment by Marcondiro** [comment]
Oh ok 😄
Actually when a dependency is marked as optional, Cargo creates a feature having its same name by default

**Comment by Marcondiro** [comment]
By the way I was not really interested in the json thing but more in general my question is: why do I have to enable all these feature if I just want std 😄

**Comment by domenukk** [comment]
What do you hope to get from std? What don't you want to get? We can introduce more features of course

**Comment by domenukk** [comment]
Just removing the existing dependencies from std won't work, though - they are being used in code

**Comment by Marcondiro** [comment]
> Just removing the existing dependencies from std won't work, though - they are being used in code

Oh, I see, the change would require a bit of work

> What do you hope to get from std? What don't you want to get?

When adding a new feature that requires std I'd like to add `my_feature = ["std"]` without being forced to bring in all the other deps/flags

**Comment by domenukk** [comment]
Initially we didn't have any features, then we made this `no_std` by hiding everything behind `std` that wasn't compatible with std.
I think it's pretty small still but of course having even less stuff in std and adding feature flags for other things could be a god idea.
PRs welcome :D

Closing this for now :)
