### ISSUE TITLE
libafl_bolts tuples relies on standard library implementation details

### ISSUE THREAD

**Issue by Noratrieb** [AFLplusplus/LibAFL#2648]
https://github.com/AFLplusplus/LibAFL/blob/89cff637025c1652c24e8d97a30a2e3d01f187a4/libafl_bolts/src/tuples.rs#L27-L58

this code here relies on the (unsound) specialization of Copy for cloning of arrays. I hope I don't have to explain why that's a problem^^. this will probably break in the future (since it's unsound), either with the specialization being removed, the lifetime-dependent Copy implementation being an error or both.

how else should it be implemented then? not. this operation cannot be implemented correctly and a different way to do the stuff that uses it today needs to be found.

**Comment by domenukk** [comment]
Feel free to propose a better / sound way. I sadly don't know of any.

FWIW we do run tests in CI and would catch future breakage:
https://github.com/AFLplusplus/LibAFL/blob/89cff637025c1652c24e8d97a30a2e3d01f187a4/libafl_bolts/src/tuples.rs#L890
I agree it's not a good solution, but it'll be pretty hard to come up with a better one..

**Comment by Noratrieb** [comment]
There is indeed not really a better way. As I said, this is not an operation that *can* be implemented correctly. I recommend just deleting the functions. This repo doesn't seem to use it, and users of the crate need to find a different way.

**Comment by domenukk** [comment]
It's used here:
https://github.com/AFLplusplus/LibAFL/blob/89cff637025c1652c24e8d97a30a2e3d01f187a4/libafl_bolts/src/tuples.rs#L495

And that's a pretty important piece, if we just leave it out we can run into type confusions everywhere..

**Comment by workingjubilee** [comment]
Then we can remove this from the standard library, and your code that has renounced stability guarantees by deliberately bypassing them will fail to compile.
