### ISSUE TITLE
Introduce `LengthTaggedMapObserver`

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#2651]
For shared maps, afl++ puts the length of the shmem as the first variable on the map.
In general, the type system should be able to differentiate between MapObservers with and without length tag, so users can't put the wrong one into the wrong thing.
CC @tokatoka @R9295

_Originally posted by @domenukk in https://github.com/AFLplusplus/LibAFL/pull/2592#discussion_r1827661429_

**Comment by tokatoka** [comment]
what do you want to achieve?
the length of the input has nothing to do with the map size. it's not the allowed max size of the input, it's 'the length' of the current input which can grow or shrink at every execution.

**Comment by tokatoka** [comment]
and as far as i know you can't grow the map observer's size right?

**Comment by domenukk** [comment]
Well there's a difference between an observer that takes _exactly_ the size of the map and an observer that takes _up to_ the size of the map, with the size being set in the first `n` bytes (usually 32 bit).
Right now we don't differentiate between the two, but we really need to.

**Comment by domenukk** [comment]
The observer doesn't contain the length right now
