### ISSUE TITLE
[Question] How to fuzz shared library?

### ISSUE THREAD

**Issue by famasoon** [AFLplusplus/LibAFL#2675]
Hello,

I try to fuzz to shared library?
Do you have a fuzzing sample for a shared library?

**Comment by domenukk** [comment]
Any reason not to link the library statically? What OS? Really any of the inprocess fuzzers schould work, such as https://github.com/AFLplusplus/LibAFL/tree/main/fuzzers/inprocess/fuzzbench

**Comment by famasoon** [comment]
>Any reason not to link the library statically?

Oh, sorry, I just looked for a way to make it a static library and found it!

>What OS?

Ubuntu 22.04

Sorry, my lack of research.
I'll take a look at the implementation you shared and give it a try.
