### ISSUE TITLE
The build_all_fuzzers.sh script is broken

### ISSUE THREAD

**Issue by riesentoaster** [AFLplusplus/LibAFL#2683]
`scripts/build_all_fuzzers.sh` is broken, and a quick look seems to indicate that it wasn't changed when the example fuzzers were restructured:

```rust
if [[ -z "${RUN_ON_CI}" ]]; then
    fuzzers=$(find ./fuzzers -mindepth 1 -maxdepth 1 -type d)
    backtrace_fuzzers=$(find ./fuzzers/backtrace_baby_fuzzers -mindepth 1 -maxdepth 1 -type d)
else
```

The script seems to exit successfully, but does not actually build anything.

This would be really handy to have, to find compiler errors without relying on the CI or manually having to go through all of them.

`scripts/build_all_fuzzers.sh` seems to have similar issues.

**Comment by tokatoka** [comment]
#2686 should fix
