### ISSUE TITLE
Create a MIGRATION.md

### ISSUE THREAD

**Issue by golem9247** [AFLplusplus/LibAFL#2725]
Hello a lot of libafl example code on internet, or on this repo is below 0.11. A lot has changed and for a developer it's quite a loss of time to search all refactor.

If possible, can we have a MIGRATION.md file for future refactor ? We can see all functions refactored/moved or the equivalence. 
good day

**Comment by golem9247** [comment]
It will be cool to also Update the examples in fuzzers/ with the 0.14 version

**Comment by tokatoka** [comment]
yeah good idea.
i'll create one
