### ISSUE TITLE
CI: custom base image instead of installation scripts/actions

### ISSUE THREAD

**Issue by riesentoaster** [AFLplusplus/LibAFL#2736]
For many of the CI runs, a significant fraction of runtime is used by the prepare actions (`fuzzer-tester-prepare`, `qemu-fuzzer-tester-prepare`, `ubuntu-prepare`, `windows-tester-prepare`).

Has anyone ever looked into creating custom docker images that could then be used as the base image for the CI runs instead of running the installations each time? This would save some time, even though the image pull times would increase. I don't have enough experience to say how much time would be saved, but it may be worth it?

I would then suggest setting up the CI to re-build the testing base images when something changes in their config (i.e. `Dockerfile`), and maybe once weekly to account for dependency updates.

Thoughts?

**Comment by tokatoka** [comment]
your suggestion is to our custom-built image instead of current ubuntu 22.04 right?

i think it's worth it

**Comment by tokatoka** [comment]
wait i don't think it's possible https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

if you mean,
1. build our docker image with every deps included
2. docker pull in the ci
3. and run stuff.

then i don't know if it's efficient or not.
because then it's still building the same things and the workload is the same no?

**Comment by tokatoka** [comment]
i'm still searching for how this could be done so maybe i'm wrong

**Comment by tokatoka** [comment]
https://github.com/addnab/docker-run-action
this guy looks working. i just need to prepare libafl docker image that includes all the stuff from ci script

**Comment by tokatoka** [comment]
i think we simply don't have place to host the docker image.
dockerhub can do it free but only 200 pulls per 6 hours
whereas our ci triggers 100+ instances per single ci run

**Comment by riesentoaster** [comment]
> wait i don't think it's possible https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

You're right, that kind of kills the idea.

> https://github.com/addnab/docker-run-action
this guy looks working. i just need to prepare and publish libafl docker image that includes all the stuff from ci script

This is just running docker within docker, but that adds a lot of complexity, and I doubt that the speed improvements (if there even are any at that point!) are worth it.

> dockerhub can do it free but only 200 pulls per 6 hours

We may be able to use GitHub's Container Registry, I haven't found anything about pull limits, just push (10min interval) and size (10GB): https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#troubleshooting

So, IMO: as long as we don't have any self-hosted runners, don't do it. If we do want to optimise some things, that may still be possible, but we'd have to take a look at other caching mechanisms.

**Comment by tokatoka** [comment]
> as long as we don't have any self-hosted runners,

we have, but just 4. and we need 100+
