### ISSUE TITLE
MutationResult::Mutated does not necessarily mean something changed for certain havoc_mutations

### ISSUE THREAD

**Issue by riesentoaster** [AFLplusplus/LibAFL#2759]
**Describe the bug**
Certain mutators in `havoc_mutations` (e.g. `BytesSetMutator`, which randomly chooses an element of the list and `memset`s a random range of elements to that value) may potentially not change anything about the input yet report `MutationResult::Mutated`.

**To Reproduce**
The second assertion here breaks:

```rust
let mut input = BytesInput::new(vec![1, 1, 1, 1, 1]);
let mut state: NopState<BytesInput> = NopState::new();
assert_eq!(
    MutationResult::Mutated,
    BytesSetMutator::new()
        .mutate(&mut state, &mut input)
        .unwrap()
);
assert_ne!(vec![1, 1, 1, 1, 1], input.bytes);
```

**Expected behavior**
If `MutationResult::Mutated` is reported, one would expect the input to change.

**Additional context**
To fix this, additional checks would be required, which would introduce a performance penalty. So I'm not sure if this is a classic `wontfix` and we just add a note to `MutationResult`, on the other hand, misses here lead to unnecessary executions of the target, which may be way more expensive than the checks.

**Comment by tokatoka** [comment]
i think this is a `wontfix`. 
we don't want to scan the input for every generated input.
if you want to make a note to mutationresult, it's ok.

**Comment by domenukk** [comment]
In theory you can wrap the mutator in a HashMutator that hashes the inputs pre and post mutations to make sure they are different - but that only makes sense for very slow targets.
For those it might even be beneficial to sort out all previously tried inputs...
