### ISSUE TITLE
Race condition in ServedShMemServiceWorker::handle_request

### ISSUE THREAD

**Issue by sitay1** [AFLplusplus/LibAFL#276]
The Bug:
When multiple threads reach ServedShMemRequest::Hello simultaneously, there's race condition on `remove()`ing from the HashMap holding the clients:
https://github.com/AFLplusplus/LibAFL/blob/7d249dd306593c92c9c7cce3037a17d5e15ff93f/libafl/src/bolts/os/unix_shmem_server.rs#L453
    let other_client = self.clients.**remove**(&other_id);

In one (or more) of the threads, `remove()` returns None (though the client is still in the map). This causes the following operations to fail.

**To Reproduce**
1. lower the timeout threshold to 1-5 seconds to reproduce the issue faster.
2. Execute the fuzzer (I used frida_libpng) on multiple cores & use a corpus that triggers timeouts/crashes often.
3. It won't take long to trigger the race once multiple clients stop & re-start simultaneously. 

**Expected behavior**
This code (& all the ServedShMemRequest/Response flows) needs to be thread safe.

**Comment by sitay1** [comment]
as a workaround for now, I skipped the pop in the following case:

ServedShMemRequest::Deregister(map_id) => {
                let client = self.clients.get_mut(&client_id).unwrap();
                let maps = client.maps.entry(map_id).or_default();
                if maps.is_empty() {
                    Ok(ServedShMemResponse::RefCount(0u32))
                } else {
                    Ok(ServedShMemResponse::RefCount(
                        //Rc::strong_count(&maps.pop().unwrap()) as u32, // <<<<
                        **Rc::strong_count(&maps.last().unwrap()) as u32,**
                    ))
                }
            }

**Comment by domenukk** [comment]
Think I found the issue, after reducing the map count in a client to 0 (which happens in the Launcher for $reasons), it could never be increased again. Should™ work now with 7441ce8dbac147f587657e39e5cda3d7ef45e0b9

**Comment by domenukk** [comment]
Reopen if the issue persists ;)

**Comment by sitay1** [comment]
seems to resolve the initial issue.
