### ISSUE TITLE
Add max queue cycles for queue schedulers

### ISSUE THREAD

**Issue by momvart** [AFLplusplus/LibAFL#2763]
**Is your feature request related to a problem? Please describe.**
If the mutators are deterministic, going over the corpus again is not helpful (right?).

**Describe the solution you'd like**
Adding a limit for any scheduler implementing `HasQueueCycles` for the number of cycles. While a generic solution might add new functions to `Scheduler`, the support can be added as a wrapper around schedulers like the below, or merely for some concrete ones like `QueueScheduler`. 
```rust

struct CappedCycleScheduler<CS> {
    base: CS,
    max_cycles: u64,
}

impl<CS, I, S> Scheduler<I, S> for CappedCycleScheduler<CS>
where
    CS: Scheduler<I, S> + HasQueueCycles,
{
    fn next(&mut self, state: &mut S) -> Result<libafl::corpus::CorpusId, Error> {
        if self.base.queue_cycles() > self.max_cycles {
            Err(Error::empty("Finished a full cycle"))
        } else {
            self.base.next(state)
        }
    }

    // ...
}
```

**Describe alternatives you've considered**
- Add a stage to disable the current test case.

**Comment by tokatoka** [comment]
There's a lot of ways to achieve what you want: "If the mutators are deterministic, going over the corpus again is not helpful (right?).".

The first thing that came to my mind is that wrap your Stage that does deterministic mutation inside a IfStage and pass a closure to check if it has been fuzzed or not.
I don't think max_cycles is generic enough to add to queue schedulers. and in addition, I don't want any more ramification in scheduler module. In my opnion `Stage` should be the place where developer adds their customized logic for fuzzing. So if you can implement your needs with customized stage then it's better

**Comment by tokatoka** [comment]
For example,
https://github.com/AFLplusplus/LibAFL/blob/main/fuzzers/forkserver/fuzzbench_forkserver_cmplog/src/main.rs#L377
In this fuzzer example, we only run a specific mutation stage on the 2nd time a seed input is fuzzed

**Comment by momvart** [comment]
Thanks for pointing to the example. `IfStage` fits well in our use case.

However, I'm still wondering if cycling the corpus is a correct default behavior.
