### ISSUE TITLE
When fuzzing on multiple cores using `OnDiskCorpus`, a filename collision may occur where different fuzzers are trying to write the same corpus entry (with potentially different data), resulting in a corrupted corpus entry

### ISSUE THREAD

**Issue by s1341** [AFLplusplus/LibAFL#289]
This is only really reproducible when running on many cores. 

We need to make the file changes atomic.

**Comment by s1341** [comment]
This appears to have resolved the issue.

**Comment by s1341** [comment]
Ok. The problem now is that multiple cores find the same objective, try to write it and now you get a bunch of copies of the objective in crashes, so the 'automatic' dedup we had before is gone.

Maybe what we really need is REAL dedup?

**Comment by domenukk** [comment]
I mean, we can alternatively also ignore the second write, instead of renaming it. Do you think that would be better?
You can also just ignore or remove all files starting with a number and a minus

**Comment by s1341** [comment]
what if you have a hash-collision?

**Comment by domenukk** [comment]
That's why I chose not to deduplicate. Not sure what would be better here

**Comment by s1341** [comment]
yeah. I'm not sure either... I guess a real crash-info based deduplicator would really be the answer.
