### ISSUE TITLE
DeleteTimerQueueTimer fails of ERROR_EXCL_SEM_ALREADY_OWNED

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#361]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch
yes

**Describe the bug**
Reported by @expend20 
DeleteTimerQueueTimer fails of error code 101 (ERROR_EXCL_SEM_ALREADY_OWNED)
at this line
https://github.com/AFLplusplus/LibAFL/blob/32b8f838ae0e327fd9313401b7fa565ac4546143/libafl/src/executors/timeout.rs#L131

maybe we can just retry calling it as suggested here, which would wait for the semaphore owned by other thread to be released

https://docs.microsoft.com/en-us/windows/win32/api/threadpoollegacyapiset/nf-threadpoollegacyapiset-deletetimerqueuetimer

> If the error code is ERROR_IO_PENDING, it is not necessary to call this function again. For any other error, you should retry the call.

I remember libfuzzer uses similar WinAPI but they never reset the timer ??
https://github.com/llvm-mirror/compiler-rt/blob/69445f095c22aac2388f939bedebf224a6efcdaf/lib/fuzzer/FuzzerUtilWindows.cpp#L85

**Comment by tokatoka** [comment]
I think another (better) solution is to remove DeleteTimerQueueTimer and use ChangeTimerQueueTimer instead to reset the timer expiration time.
https://docs.microsoft.com/en-us/windows/win32/api/threadpoollegacyapiset/nf-threadpoollegacyapiset-changetimerqueuetimer

**Comment by domenukk** [comment]
> 
> I remember libfuzzer uses similar WinAPI but they never reset the timer ?? https://github.com/llvm-mirror/compiler-rt/blob/69445f095c22aac2388f939bedebf224a6efcdaf/lib/fuzzer/FuzzerUtilWindows.cpp#L85

Seems like they just ignore the alarm, if it goes off too early...
https://github.com/llvm-mirror/compiler-rt/blob/69445f095c22aac2388f939bedebf224a6efcdaf/lib/fuzzer/FuzzerLoop.cpp#L290

I guess we could also do both:
use `DeleteTimerQueueTimer`, but ignore it's result, and then ignore alarms that arrive too early

> hmm, these APIs seem to be from windows 2000 and a bit outdated, and ChangeTimerQueueTimer does not fit in our use-case, I guess instead we can just use another API described here https://devblogs.microsoft.com/oldnewthing/20151230-00/?p=92741

This seems to be spawning a threadpool, I guess threading may slow the fuzzer down? But who knows, it's windows...

**Comment by tokatoka** [comment]
Current CreateTimerQueueTimer seems to spawn threadpool also, I guess.
and these old calls are wrappers around the new api, says the devblog.

**Comment by domenukk** [comment]
Fair, but for now a simple fix could be enough
