### ISSUE TITLE
Feature to Ignore Unstable Edges

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#366]
**Is your feature request related to a problem? Please describe.**
For real-world targets, we save a lot of useless testcases, leading to an explosion of the corpus.

**Describe the solution you'd like**
Rerun the input, tracking edges that are unstable, and ignore them for future exeuctions.
Also keep track of stability for the monitor in the state Metadata

**Comment by andreafioraldi** [comment]
Must be in the CalibrationStage https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/stages/calibrate.rs#L80

**Comment by domenukk** [comment]
This is done with #398
