### ISSUE TITLE
frida_libpng crashes on Windows with pageheap enabled instead of reporting a crash

### ISSUE THREAD

**Issue by expend20** [AFLplusplus/LibAFL#372]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch

yep, I'm using a42a3a9ccf41389bea41302c079eaa853187549e rev

**Describe the bug**

Here is baby OOBR harness (oobr.cpp):

```c++
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

extern "C" __declspec(dllexport) size_t
    FuzzMeOOBR(const char *data, unsigned int len)
{

    char sdata[1024];
    memcpy(sdata, data, sizeof(sdata) < len ? sizeof(sdata) : len);

    if (len >= 8 
            && *(uint8_t *)(data + 0) == '1'
            && *(uint8_t *)(data + 1) == '3'
            && *(uint8_t *)(data + 2) == '3'
            && *(uint8_t *)(data + 3) == '7'
            ) {
        auto ptr = (char*)malloc(0x10);
        auto x = ptr[0x10];
        return (size_t)x;
    }
    return 0;
}
```

With pageheap enabled, instead of reporting the crash, LibAFL crashes itself. I have post mortem debugger which pops up when fuzzer discovers the OOBR branch in the code:

```
(26ec.1038): Access violation - code c0000005 (!!! second chance !!!)
000002bb`2300a141 0fb60401        movzx   eax,byte ptr [rcx+rax] ds:000002bb`7e6cd000=??
0:000> k
 # Child-SP          RetAddr           Call Site
00 000000f1`92eed670 00000000`00000000 0x000002bb`2300a141
0:000> db 000002bb`7e6cd000 - 10
000002bb`7e6ccff0  c0 c0 c0 c0 c0 c0 c0 c0-c0 c0 c0 c0 c0 c0 c0 c0  ................
000002bb`7e6cd000  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
000002bb`7e6cd010  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
000002bb`7e6cd020  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
```

**To Reproduce**

1. Compile the harness oobr.cpp -> obbr.dll:
```
cl /c oobr.cpp && link oobr.obj /dll
```

2. Compile LibAFL\fuzzers\frida_libpng 
```
cargo build --release
```

3. Enable pageheap for frida_libpng.exe (run with admin):

```
C:\Windows\system32>"c:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" /p /enable frida_libpng.exe
    frida_libpng.exe: page heap enabled
```
4. Run fuzzing session and wait a bit
```
frida_libpng.exe oobr.dll FuzzMeOOBR oobr.dll --cores 0
```

**Expected behavior**

Fuzzing session should continue after discovering OOBR branch, crashing sample should be saved in `crashes` directory

**Additional context**

Interesting thing is, if instead of OOBR code you place `*(char*)0 = 0;` which is basically same access violation exception, everything is going smoothly.

 Feels like could be related to #360

**Comment by tokatoka** [comment]
thank you!
yes, it seems again libafl couldn't catch the exception...

**Comment by tokatoka** [comment]
I can reproduce this

**Comment by tokatoka** [comment]
There's a access violation example in baby_fuzzer for windows, which does the same thing as writing 0 to 0x00000000 but that one works fine.. 🤔 (even with pageheap enabled)

**Comment by expend20** [comment]
baby_fuzzer doesn't use frida, could be related

**Comment by tokatoka** [comment]
yes... it seems to be frida related issue, another windows-compatible fuzzer example libfuzzer_stb_images does work with these exceptions.
anyways, thanks for reporting

**Comment by tokatoka** [comment]
Removing this if clause fixes the issue.
https://github.com/AFLplusplus/LibAFL/blob/a42a3a9ccf41389bea41302c079eaa853187549e/fuzzers/frida_libpng/src/fuzzer.rs#L98

I am beginning to feel that frida's exception handler mechanism is interfering with ours on windows....

**Comment by tokatoka** [comment]
Maybe we can make use of frida's `Process.setExceptionHandler(callback)` API...
but I'm not very sure.
