### ISSUE TITLE
GSoC 2022

### ISSUE THREAD

**Issue by vanhauser-thc** [AFLplusplus/LibAFL#390]
We will likely apply for libafl for GSoC.
For every interested student that means you must already have a strong background in Rust - otherwise you will not be able to help the project.

If you are interested, and are a good Rust developer, have a look at our issues that have are marked [good first issue](https://github.com/AFLplusplus/LibAFL/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) to start contributing.

We will not select anyone for GSoC who has not proven himself/herself by contributing to libafl.
Do not worry, you will have our support if you need a helping hand.

**Comment by navjot-rsa** [comment]
I want to

**Comment by syheliel** [comment]
Hi, what's the GSOC project this year? Are the projects in #119 avaliable now?

**Comment by vanhauser-thc** [comment]
@syheliel yes these are the gsoc projects.
Please don’t just apply for a project as the chance for being selected is at 0% then :)
We need applicants to work with libafl beforehand, working on a few PRs etc to see if communication, skill etc fits .

**Comment by syheliel** [comment]
@vanhauser-thc thanks, that clarifies a lot.
#119 are published in May 2021, Does the project list have some changes? Some projects might be solved in the past.

**Comment by vanhauser-thc** [comment]
the title clearly says 2022. if you click the "edited" column on the post it says last modified 28 days ago. so .... all current.

**Comment by syheliel** [comment]
Hi, I have written a draft proposal, can I send it to a mentor for a pre-review?

**Comment by tokatoka** [comment]
Can you send it to gsoc@aflplus.plus?

**Comment by syheliel** [comment]
OK. Thanks!
