### ISSUE TITLE
I can't compile libafl_derive

### ISSUE THREAD

**Issue by VinadiakT** [AFLplusplus/LibAFL#406]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch

Thank you for making LibAFL better!

**Describe the bug**

**To Reproduce**
1. I run the command "cargo build --release" in my Mac and it say "error: could not compile `libafl_derive`"

**Expected behavior**
error: could not compile `libafl_derive`

**Screen output/Screenshots**
![截屏2021-12-06 上午11 33 33](https://user-images.githubusercontent.com/39263234/144782969-cacfcb16-e362-4972-9507-71bfe3e137cb.png)

**Additional context**
version:
cargo 1.51.0
rustc 1.51.0

**Comment by tokatoka** [comment]
Hello 🙂 
Can you run `rustup update` and try it again?

**Comment by VinadiakT** [comment]
oh!! I solved this problem by your method
Thank you for your quick answer to solve my problem

**Comment by tokatoka** [comment]
yeah we need the latest rust toolchains
