### ISSUE TITLE
Replace Capstone with yaxpeax

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#410]
For some parts of libafl we use capstone, however it's slow to build and, according to:
https://github.com/athre0z/disas-bench
also slow to run.
Instead we should look at yaxpeax which is fast and written in rust
https://github.com/iximeow/yaxpeax-core

**Comment by domenukk** [comment]
Checked the usages and it seems our usages are all, more or less, independent of frida. I'm not even sure the toolchain is smart enough to not place two capstone object files into the final binary, even for frida mode...

**Comment by s1341** [comment]
Here https://github.com/AFLplusplus/LibAFL/blob/4a23489acb1101aee2ddde27592bd50b8e8aac76/libafl_frida/src/helper.rs#L301 we get the capstone instruction from frida.

**Comment by domenukk** [comment]
Ow :(
Guess adding another decompiler is not helping much, in this case
