### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#431]
https://github.com/AFLplusplus/LibAFL/blob/d697554810b13e9634ca5dd9bd1b36f443c85409/libafl_qemu/build.rs#L52

@domenukk this breaks, what's the specific reason, I removed it during the refactor

**Comment by domenukk** [comment]
Cargo runs with `--all` so this feature allows us to build multiple architectures together

**Comment by andreafioraldi** [comment]
but then a fuzzer using let's say arm cannot use clippy

**Comment by domenukk** [comment]
Partly correct: you can still use clippy for only `arm`, or clippy for `--all` but never for `arm` and `--all` at the same time
