### ISSUE TITLE
Use another allocator for the fuzzer in fuzzer/fuzzbench

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#437]
Remainder for us so that we don't forget this ;)

When the PUT corrupts the heap, the fuzzer dies because the fuzzer and the PUT uses the same allocator.
(like libxml2, re...)
We should use another allocator for the fuzzer (possibly with `#![feature(alloc_jemalloc)]`?)

**Comment by domenukk** [comment]
https://github.com/gnzlbg/jemallocator#documentation

this seems to be the current way to do this

**Comment by tokatoka** [comment]
it says it's not ready for aarch64/android target... :/

**Comment by tokatoka** [comment]
can we make use of this?
https://github.com/AFLplusplus/AFLplusplus/tree/stable/utils/libdislocator

**Comment by domenukk** [comment]
We need allocators that are as fast as possible.
There are also a buch of other custom mutators around, for example https://github.com/ezrosent/allocators-rs/tree/master/elfmalloc maybe some of them work for Android, too
