### ISSUE TITLE
Move LLVM passes to new pass manager

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#476]
LLVM 14 deprecates the old that we use

**Comment by andreafioraldi** [comment]
https://github.com/AFLplusplus/AFLplusplus/pull/1353

**Comment by tokatoka** [comment]
autotokens in #605

**Comment by tokatoka** [comment]
I'm trying llvm14 right now.
we need these fixes in addition to the new PM https://github.com/AFLplusplus/AFLplusplus/pull/1334

**Comment by tokatoka** [comment]
We can close this now?
