### ISSUE TITLE
Use stdsimd for MapFeedbacks

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#481]
Now that [stdsimd](https://docs.rs/stdsimd/latest/stdsimd/) is mature, and we can enable code only in nightly using rustversion, we should implement simd map processing

**Comment by syheliel** [comment]
The vector for `simd` usually has a fixed length(like `126 bits` or `512 bits`), would this feature conflict with the arbitrary length? like
`pub fn new(name: &'static str, map_size: usize)` in `MapFeedbackState`

**Comment by andreafioraldi** [comment]
No, you can simply process the remaining bytes like it is now without simd
