### ISSUE TITLE
Forkserver AutoTokens

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#504]
Now we have AutoTokens (autodict) feature for inprocess fuzzer, we also want it for the forkserver executor

**Comment by andreafioraldi** [comment]
it makes sense to be compatible with afl++, but we need the afl++ forkserver options.
We can even subclass ForkserverExecutor to AFLppForkserverExecutor or something similar using that afl++ specific convention convention

**Comment by tokatoka** [comment]
I already made it to have shmem fuzzing feature months ago, it should be easy to adapt for aflpp's autodict options too.
