### ISSUE TITLE
Object-achieving results should be accompanied by machine- and human-readable metadata

### ISSUE THREAD

**Issue by s1341** [AFLplusplus/LibAFL#52]
When objective-achieving results are saved, they should include all the metadata, mutator and observer data that is available related to this test-case. 

Perhaps this can be achieved by storing a json/toml/yaml file next to the test-case input, with the same base name.

At a minimum the following information should be present:
- the test-case's unique name
- the date/time at which it was encountered/produced
- the type of objective-achievement
- the arguments/cmd-line which was used to generate the test-case
- a cmd-line which can be used to reproduce the test-case
- mutations that were applied to generate the test-case
- the parent test-case which was mutated
- observer output

**Comment by domenukk** [comment]
We have a good amount of metadata now. We could add more like mutations applied, parent case, cmd-line, but for now I'm closing this issue
