### ISSUE TITLE
Implement frida-based cmplog

### ISSUE THREAD

**Issue by s1341** [AFLplusplus/LibAFL#53]
Implement cmplog using frida.

- [ ] aarch64 instrumentation
  - [ ] cmp support
  - [ ] tbnz/tbz support
  - [ ] .s instruction support
  - [ ] switch detection and support
- [ ]  x86_64 instrumentation

**Comment by domenukk** [comment]
Apart from x86, this is done, right?

**Comment by s1341** [comment]
I think so. Except for switch detection... Not sure how to do that at this stage.

**Comment by domenukk** [comment]
Closing this issue for now, since it's somewhat done. Open issues for sub-parts if needed
