### ISSUE TITLE
Libafl run in  Run_Client something question

### ISSUE THREAD

**Issue by VinadiakT** [AFLplusplus/LibAFL#550]
I simulated this article（https://epi052.gitlab.io/notes-to-self/blog/2021-11-26-fuzzing-101-with-libafl-part-4/）and wrote a similar fuzzer, but the fuzzer I wrote encountered the following error, I don't understand it very well, I looked at my code and this article is not much different, but I don't know what the error is what happened. The LIbafl version is 0.7

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/parallels/AFLHome/LibAFL/libafl/src/feedbacks/map.rs:384:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtracethread 'main' panicked at 'Fuzzer-respawner: Storing state in crashed fuzzer instance did not work, no point to spawn the next client! This can happen if the child calls `exit()`, in that case make sure it uses `abort()`, if it got killed unrecoverable (OOM), or if there is a bug in the fuzzer itself. (Child exited with: 25856)

**Comment by VinadiakT** [comment]
I found that when I created state::new, I only gave feedback_state and not objective_state to cause this error to occur. It took 7 hours from the error to my resolution. I'm too stupid. I discovered my mistake after comparing the source code of the article in detail. Is it easier for Libafl to remind users where the error is, instead of blindly taking pictures. Hope this is a useful suggestion😂

**Comment by domenukk** [comment]
We may make the states easier in this PR:
https://github.com/AFLplusplus/LibAFL/pull/524
