### ISSUE TITLE
speed up CI

### ISSUE THREAD

**Issue by syheliel** [AFLplusplus/LibAFL#565]
command `Run ./scripts/test_all_fuzzers.sh` takes almost 99% of CI running time, is it possible to use some test frameworks to support multi-thread?

**Comment by domenukk** [comment]
I don't think threading would help:
Afaik Gh runners only have two(?) cores.
Also, it spends most of its time is building rust code which is multi threaded at times.

The real way to decrease build times would be to figure out rust build artifact caching between runs.

**Comment by syheliel** [comment]
The logic in `scripts/test_all_fuzzers.sh` is to select between `cargo build` or `cargo make test` according to the existence of `Makefile.toml`:
```
    if [ -e ./Makefile.toml ]; then
        echo "[*] Testing $fuzzer"
        cargo make test || exit 1
	    echo "[+] Done testing $fuzzer"
    else
        echo "[*] Building $fuzzer"
        cargo build || exit 1
        echo "[+] Done building $fuzzer"
    fi
```
Is it possible to modify the `Makefile.toml` and use `cargo make` in the root directory? It seems that `cargo build` is the default behavior of `cargo make` and `cargo make` will apply to sub-crates, see https://github.com/sagiegurari/cargo-make/issues/431.

**Comment by tokatoka** [comment]
for those with Makefile.coml, yes, maybe it's possible to use cargo make in the root (i.e. fuzzers dir).
I have not tried that feature yet though :)

**Comment by syheliel** [comment]
@tokatoka Are you working on the `Makefile.toml` in `./fuzzer`? I notice that every fuzzer example will download and build `libpng` again, there may exist a better way to do that:
we can store `libpng-1.6.37` as the submodule in directory like `./fuzzer/vul_program`, and recompile them once needed. Here are the advantages:
- fuzzer can reuse the compile result
- `git submodule` can help us manage the line break difference between Windows(`\r\n`) and Linux(`\n`). In Sourceforge, `.tar.gz` file is used for Linux and `.zip` is used for Windows. Additional code is needed to support Windows.
- simplify `Makefile.toml` logic

**Comment by tokatoka** [comment]
> Are you working on the Makefile.toml in ./fuzzer?
Currently, no. 
True, it is wasteful to build libpng again and again. 

You can work on it
I think we spend most of the build time in `cargo build --release` where ci builds the same rust dependencies for every fuzzer though.

**Comment by domenukk** [comment]
Libpng will be rebuilt for every fuzzer anyway, the only thing we save is probably the download and checkout.
It's a better time investment to fix GitHub build caching I think

**Comment by domenukk** [comment]
Closing this for now, we done a lot of changes since
