### ISSUE TITLE
Missing `libafl::schedulers`?

### ISSUE THREAD

**Issue by syheliel** [AFLplusplus/LibAFL#569]
I'm trying to reproduce the example fuzzer outside of LibAFL directory (to gain a more clear project view). 
1. `cp LibAFL/fuzzers/libfuzzer_libpng ~/my_fuzzer -r`
2. change `dependencies` from relative path to crate version.
Then error pops out.
![image](https://user-images.githubusercontent.com/45957390/158809359-1f73e0cf-0b3a-41d8-9a19-2a87afe71c05.png)

`schedulers` has been made `pub` in https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/lib.rs, but in [`docs.rs`](https://docs.rs/libafl/0.7.1/libafl/?search=schedulers#modules) , `libafl::schedulers` also was not found.

**Comment by domenukk** [comment]
We moved the schedulers very recently (finalized in a56f4af7da8df94593c7ff8169d4125a1e9ca435 ) and have not yet pushed the new version to cargo yet.
For the current release version they should still be in corpus.

**Comment by syheliel** [comment]
OK, thanks for the explanation :)
