### ISSUE TITLE
Support for error backtrace

### ISSUE THREAD

**Issue by syheliel** [AFLplusplus/LibAFL#571]
HI, I have found some problems when trying to implement `afl-cmin`, I'm trying to create an executor is like this:
```
let mut executor = ForkserverExecutor::builder()
    .program(binary_path.to_str().unwrap())
    .arg_input_file(input_path)
    .shmem_provider(&mut shmem_provider)
    .build(tuple_list!(edges_observer)).expect("Failed to create ForkserverExecutor");
```
If it fails to ForkserverExecutor, it will throw following error(with `RUST_BACKTRACE=1`):
```
thread 'test_run_target' panicked at 'Failed to create ForkserverExecutor: Forkserver("Failed to start a forkserver")', cli-tools/src/libafl-cmin.rs:69:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5f4e0677190b82e61dc507e3e72caf89da8e5e28/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/5f4e0677190b82e61dc507e3e72caf89da8e5e28/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/5f4e0677190b82e61dc507e3e72caf89da8e5e28/library/core/src/result.rs:1784:5
   3: core::result::Result<T,E>::expect
             at /rustc/5f4e0677190b82e61dc507e3e72caf89da8e5e28/library/core/src/result.rs:1034:23
   4: libafl_cmin::run_target
             at ./src/libafl-cmin.rs:65:24
   5: libafl_cmin::test_run_target
             at ./src/libafl-cmin.rs:103:5
   6: libafl_cmin::test_run_target::{{closure}}
             at ./src/libafl-cmin.rs:100:1
   7: core::ops::function::FnOnce::call_once
             at /rustc/5f4e0677190b82e61dc507e3e72caf89da8e5e28/library/core/src/ops/function.rs:227:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/5f4e0677190b82e61dc507e3e72caf89da8e5e28/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test_run_target ... FAILED
```
But I can't figure out what goes wrong, because `Result` doesn't have any information about the error backtrace and all the output is about the code `.expect("Failed to create ForkserverExecutor")` even with `RUST_BACKTRACE=full`. I have noticed that only a few errors has been made in a specific struct like `AsanError` in `libafl_frida`. Maybe some error propagation crates,like `eyre` or `error-chain`, can be introduced to avoid big change in the codebase and provide a more meaningful error message.

**Comment by tokatoka** [comment]
Hi,

> But I can't figure out what goes wrong,
Did you instrument your binary? (with afl-cc?)

**Comment by syheliel** [comment]
Actually, I have got that point by reading the source 😃 But I think that error backtrace may make the project more friendly for debugging and for normal users.

**Comment by tokatoka** [comment]
I agree. It's hard to find out the root cause of the error with the current error msg unless you look it up in the source code

**Comment by tokatoka** [comment]
Now I got it, ..
The reason you get the "Failed to start a forkserver" message, which virually tells nothing, is because you call expect() that overwrites the original Err I guess

**Comment by syheliel** [comment]
> The reason of getting "Failed to start a forkserver" message, which virually tells nothing, is because calling expect() that overwrites the original Err

Yes. Actually, I'm still wondering if there exists another best practice for this issue, see https://www.reddit.com/r/rust/comments/lql8ib/what_kinds_of_backtraces_can_i_actually_get_using/

There is no hurry to make a decision until we find an elegant answer.

**Comment by domenukk** [comment]
Adding a backtrace at the time of error creation should be possible, but comes at a non-neglible runtime overhead. It should be a feature flag and be enabled by default for debug builds

**Comment by andreafioraldi** [comment]
> 

There are crates to do it automatically, should be easy.
Unfortunately, you know, I don't have much time this month.
@syheliel if you want to pick up this issue feel free to DM us on discord with questions

**Comment by tokatoka** [comment]
You can stop using expect() and just swap it with unwrap() to see what the actual error was.
If the backtracing feature costs additional runtime overhead, then IMO it's not helpful.
