### ISSUE TITLE
file is removed when pass into ForkserverExecutor

### ISSUE THREAD

**Issue by syheliel** [AFLplusplus/LibAFL#573]
I want to use a file as the stdin for the program, but the following code will remove the file of `input_path` after executing, is it a desired behavior?
```
let mut executor = ForkserverExecutor::builder()
.program(binary_path.to_str().unwrap())
.arg_input_file(input_path)
.shmem_provider(&mut shmem_provider)
.build(tuple_list!(edges_observer)).expect("Failed to create ForkserverExecutor");
```

**Comment by domenukk** [comment]
`arg_input_file` will deliver the input to the target via a file.
Hence the file there will be overwritten during fuzzing and cleaned up later.
What exactly do you try to achieve?
If you want to pass input via stdin, don't specify a file

**Comment by syheliel** [comment]
I'm trying to feed the program with different corpus stored as files. 
> `arg_input_file` will deliver the input to the target via a file.
Hence the file there will be overwritten during fuzzing and cleaned up later.

Do you mean that mutation stage will operate on the file so the file will be cleaned up sooner? I'm just what to get information   about `observer` under specific input(corpus).  There's no need to mutate the input.

**Comment by tokatoka** [comment]
That file is mere a temporary file made by the fuzzer to pass the input to the child process

and the file is present there only if you are using the `ForkserverExecutor` and you did not configure it to use shared memory fuzzing.

> I'm just what to get information about observer under specific input(corpus)
You can do that with `executor.observers().match_name` if you have the `executor`.

**Comment by syheliel** [comment]
@domenukk I'm trying to implement the function like `afl-showmap` as part of `cmin`, code is in `fn run_single_target(binary_path:&Path,input_path:&Path) ` of my [repo](https://github.com/syheliel/LibAFL/blob/main/cli-tools/src/libafl-cmin.rs). By the way, what observer should I use?

**Comment by tokatoka** [comment]
IMO cmin/tmin could be a `Stage` rather than a cli-tool.
(cuz afl-cmin/tmin are already cli-tools)

**Comment by syheliel** [comment]
@tokatoka that sounds reasonable
