### ISSUE TITLE
Add a debug env var to Launcher to behave like SimpleEventManager

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#604]
This will disable any fork and make debugging easier.

**Comment by kritgpt** [comment]
I would like to work on this issue. Can you please elaborate further as I'm a new contributor :)

**Comment by domenukk** [comment]
The launcher starts / forks off multiple child processes here
https://github.com/AFLplusplus/LibAFL/blob/af3d321213973189dfbef864d4035974326d095e/libafl/src/bolts/launcher.rs#L141
And uses the `RestartingEventMgr` which forks off one additional time internally, to be able to restart.
In contrast, `SimpleEventMgr` simply starts and runs the fuzzer until the first crash occurs.
Making this as simple as possible with Launcher without the need to rewrite the fuzzer will make debugging easier (just attach gdb and go)

**Comment by andreafioraldi** [comment]
you find fuzzer as examples using both in the fuzzers/ folder

**Comment by andreafioraldi** [comment]
It can be a compile-time env var (prob easier) or a runtime env var, at your choice

**Comment by kritgpt** [comment]
Okay, I'd like to take up this issue. Could you please assign it to me?
