### ISSUE TITLE
Integrate the fuzzers in libafl_fuzzbench as libafl_sugar modules

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#609]
libafl_sugar it is a crate that should provide ready-to-use fuzzers configurable with a builder pattern.
We have a collection of fuzzers in https://github.com/AFLplusplus/libafl_fuzzbench, would be cool to have them (or ast least the most importants, like generic or nautilus) integrated into libafl_sugar replacing the restarter events manager with a Launcher (like the fuzzers already in libafl_sugar) and creates binary only variants with QEMU and Frida

**Comment by luke9kim8** [comment]
I noticed that some fuzzers in `libafl_fuzzbench` have comments that says [`"In this example, you will see the use of the launcher feature"`](https://github.com/AFLplusplus/libafl_fuzzbench/blob/9097911fe37526e36ee25a9f958deb924cc7032d/nautilus/src/lib.rs#L3) but doesn't use launchers as shown in [`libafl_sugar`](https://github.com/AFLplusplus/LibAFL/blob/95004aab7e78a0fa60b32928297efcbea8733aad/libafl_sugar/src/qemu.rs#L422). Just double checking, is the goal to rewrite the fuzzers in `libafl_fuzzbench` to use the `launcher`?

**Comment by Srg213** [comment]
Hello. I wish to contribute to this issue.
I understood the task- to integrate individual fuzzers with libafl_sugar so as to create common fuzzers.
Right now, I am trying for the nautilus and generic fuzzer but facing various errors while building it. Should I ignore them for now and continue ?

**Comment by domenukk** [comment]
Suger needs a major overhaul at some point. Closing for now.
