### ISSUE TITLE
Forkserver Simple Fails With Shmem Error On Mac

### ISSUE THREAD

**Issue by WilliamParks** [AFLplusplus/LibAFL#611]
**IMPORTANT**
1. This fails on the current `main` branch, commit 1690dbb2cce727b66b6ae9a77b64d88e7db2af80.  Tests done on a up to date x64 Mac.

**Describe the bug**
The example fuzzer "ForkserverSimple" fails to run, with the error listed below

**To Reproduce**
1. Compile and run the sample according to the Readme:
```
cargo build --release
cp ./target/release/forkserver_simple .
./forkserver_simple ./target/release/program ./corpus/ -t 1000
```

**Expected behavior**
Successful execution

**Screen output/Screenshots**
```
Started ShMem Service
Recieved connection from UnixSocketAddr("Unnamed")
All right - fork server is up.
Using AUTODICT feature
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Forkserver("Reading from forkserver failed.")', src/main.rs:161:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Additional context**
Using `afl-fuzz` from the `stable` branch of AFL++ works fine on the same compilation of the sample target.  My unconfirmed theory is that LibAFL and AFL++ have a mismatch in which shared memory implementation they select.

**Comment by tokatoka** [comment]
Hi, thank you for reporting this.
Does using UnixShMemProvider instead solve the problem? 👀

**Comment by tokatoka** [comment]
It's a bit weird to see 
```
Using AUTODICT feature
```
there if you didn't change build.rs to use afl-clang-lto instead.
compiling afl-cc won't enable that option..

**Comment by WilliamParks** [comment]
@tokatoka: On the `Audodict` issue, that struck me as odd as well.  I did a clean download of LibAFL, and rebuilt, and still received the same output. FWIW, I don't have access to afl-clang-lto, being on a mac.

Switching to UnixShMemProvider does work.  Per discussion with @domenukk on Discord, there's an issue using that particular shmem implementation on Mac, as one program closing the shmem object closes it for everyone.

**Comment by domenukk** [comment]
As the target never closes the map in this case, and the implementation has to play nicely with afl++, I guess we could hard-code unix shmem for the forkserver?
The other option might be to get the original map id from the ShMem Service somehow

**Comment by tokatoka** [comment]
Does removing these if-else clause fix the issue?
https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/executors/forkserver.rs#L619-L669

**Comment by domenukk** [comment]
I don't think this will help.
I assume the issue is that here, the serialized value is the internal map id, not the OS map id:
https://github.com/AFLplusplus/LibAFL/blob/1690dbb2cce727b66b6ae9a77b64d88e7db2af80/libafl/src/executors/forkserver.rs#L581

We either need an extra method to get the raw ID or change all `StdShMemProvider` to the Unix one in this file
