### ISSUE TITLE
TuiMonitor eats up wrong configuration

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL#615]
When using the fancy TuiMonitor together with Launcher, it's hard/impossible to find misconfigurations like a missing `in` directory.
The UI comes up, but the actual fuzzers die immediately. Their output, however, is eaten up by the Launcher and GUI.
It would be cool to add an emergency mode when no nodes come up that reruns the client but does not Dup to /dev/null

**Comment by s1341** [comment]
I think we need to use proper logging crate etc.

**Comment by domenukk** [comment]
I think debugability got a bit better so I'm closing this (even though it will still not run properly when misconfigured...)
