### ISSUE TITLE
Objective deduplification

### ISSUE THREAD

**Issue by s1341** [AFLplusplus/LibAFL#63]
There should be support in either the core library or `libafl_targets` for objective deduplification, which will allow us to produce 'unique' objectives.

The deduplification mechanism should be configurable, to allow for e.g. dedup using backtraces, crash address/offset and other metadata.

**Comment by andreafioraldi** [comment]
You can define a feedback for that and set as objective `feedback_and!(CrashFeedback::new(), YouDedupFeedback::new())`. For an example see forkserver_simple in which I dedup crashes in the AFL way using the coverage.

**Comment by s1341** [comment]
Should we not provide some commond deduping `Feedback`s as part of the library? I think it'd be super useful...

**Comment by domenukk** [comment]
I agree that the crash dedup feedback, for example, could just be moved to the lib, what do you think @andreafioraldi
