### ISSUE TITLE
[frida] Windows VM with more then 64 cores is not handled correctly

### ISSUE THREAD

**Issue by wizche** [AFLplusplus/LibAFL#633]
**Describe the bug**
On Windows 10 if the VM has more then 64 cores the OS is splitting the CPUs on multiple groups (see https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups)

Now if I run with `--cores=all` on a VM with 100 cores it will either pick the group with 64 cores or the one with 36... not all together.

**To Reproduce**
1. Create a VM with more then 64 cores
2. Run the frida fuzzer with `--cores=all`

**Expected behavior**
All CPUs are used

**Screen output/Screenshots**
![cpu_usage](https://user-images.githubusercontent.com/1062939/168640155-1c2c301d-9817-4f35-b06f-bee05abcb600.png)

**Additional context**
I had a similar issue when developing [cpu painter](https://github.com/wizche/cpu-painter) I ended up calling myself the `SetThreadGroupAffinity` since the cpu affinity library (crates?) I found were having the exact same issue.

**Comment by tokatoka** [comment]
thank you
We also use core_affinity crate (I think the crate is causing this windows problem)
https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/events/llmp.rs#L826

maybe we can just call SetThreadGroupAffinity here as you suggest

**Comment by domenukk** [comment]
The `core_affinity` crate we're using is already a fork by @s1341 so at this point it might make sense to move the code into LibAFL bolts altogether, and fix it along the way? Or create a proper fork

**Comment by tokatoka** [comment]
> it might make sense to move the code into LibAFL bolts altogether

I agree.

**Comment by s1341** [comment]
I agree too.

**Comment by wizche** [comment]
Of course you can, most of it is copy paste as well :smile:
Btw in not sure if its always safe to just use the modulo for the cpu group... I'm just implying that groups are always sequential but didn't verify it...

**Comment by tokatoka** [comment]
I made the change to use the new API in #655

**Comment by domenukk** [comment]
Still doesn't work, according to @wizche on discord
