### ISSUE TITLE
[BUG] child_crash_handler doesn't terminate child process causing infinite loop

### ISSUE THREAD

**Issue by zuypt** [AFLplusplus/LibAFL#662]
**Describe the bug**
in `inprocess.rs` the function `child_crash_handler` has the 
 line commented out causing it to  repeatedly calling `child_crash_handler` result in an infinite loop. I tried to added the line back
~~~c
libc::_exit(128 + (_signal as i32));
~~~
doesn't seem to work. `waitpid` would just return process exit normally
so I changed it to 
~~~c
libc::abort()
~~~

which seems to work fine. But I'm not sure this is a correct fix

**To Reproduce**
use an InProcessForkExecutor to fuzz a test binary

**Expected behavior**
Fuzzer can detect crash

**Comment by tokatoka** [comment]
We don't read out the signal, so abort(); is the right here? @andreafioraldi 
(i.e. any signal is ok, as long as it results in ExitKind::Crash)
https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/executors/inprocess.rs#L1476

**Comment by domenukk** [comment]
I'm wondering why the crash handled should be called over and over again, instead of simply exiting afterwards?
Also, do we even need signal handlers in the forking child?

**Comment by andreafioraldi** [comment]
> I'm wondering why the crash handled should be called over and over again, instead of simply exiting afterwards? Also, do we even need signal handlers in the forking child?

yes we need to run post exec hooks

**Comment by domenukk** [comment]
Shouldn't they be in the parent?

**Comment by andreafioraldi** [comment]
> Shouldn't they be in the parent?

do you want to collect stacktraces in the parent? 😅

**Comment by domenukk** [comment]
Might be hard, but for example AFL does all post processing in the parent, maybe we need two independent hooks?

**Comment by domenukk** [comment]
Guess can be done in the feedback, too. Nevermind

**Comment by andreafioraldi** [comment]
This is strange as our fuzzers in the CI with inprocess fork executor were working fine. Anyway, I removed any ambiguity and now it should work in any possible case.
