### ISSUE TITLE
ByteFlipMutator vs. ByteNegMutator working as intended?

### ISSUE THREAD

**Issue by Scepticz** [AFLplusplus/LibAFL#674]
**Describe the bug**
I am not sure if things are working as intended here, but the two mutators **ByteFlipMutator** and **ByteNegMutator** look like they are doing exactly the same thing, which may not be the intended behavior.

ByteFlipMutator logic:
`*state.rand_mut().choose(input.bytes_mut()) ^= 0xff;`

ByteNegMutator logic (implements a Bitwise NOT):
`*byte = !*byte;`

Here is a link to a rust playground example which shows that the two are equal: [rust playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d2603e895b005ba1274243e669ea7365)

**Expected behavior**
**ByteFlipMutator** and **ByteNegMutator** have different behavior.

Possibly, the logic of ByteNegMutator is meant to be a Negation instead:
`*byte = -*byte;`

I created a PR for this as well here: https://github.com/AFLplusplus/LibAFL/pull/675

**Additional context**
[ByteFlipMutator source](https://github.com/AFLplusplus/LibAFL/blob/da537aae83f1decc3ee58ea1e0648c316624f118/libafl/src/mutators/mutations.rs#L157)
[ByteNegMutator source](https://github.com/AFLplusplus/LibAFL/blob/da537aae83f1decc3ee58ea1e0648c316624f118/libafl/src/mutators/mutations.rs#L274)
[Rustlang description of negation operators](https://doc.rust-lang.org/reference/expressions/operator-expr.html#negation-operators)

**Comment by tokatoka** [comment]
Closing as #675 is merged
