### ISSUE TITLE
Unused `factor` in `CorpusPowerTestcaseScore::compute` for most of powerschedules

### ISSUE THREAD

**Issue by z2-2z** [AFLplusplus/LibAFL#687]
**Describe the bug**
In `schedulers/testcase_score.rs` in `CorpusPowerTestcaseScore::compute`, a variable `factor` is
computed based on which powerschedule is in use but the variable has no effect on the final
`perf_score` in any powerschedules other than `EXPLORE`.

I think the critical code section is in lines 268-276:
```rust
if let Some(strat) = psmeta.strat() {
    if strat == PowerSchedule::EXPLORE {
        if factor > MAX_FACTOR {
            factor = MAX_FACTOR;
        }

        perf_score *= factor / POWER_BETA;
    }
}
```

**Expected behavior**
Maybe it was supposed to be
```rust
if let Some(strat) = psmeta.strat() {
    if strat == PowerSchedule::EXPLORE {
        if factor > MAX_FACTOR {
            factor = MAX_FACTOR;
        }
    }
    perf_score *= factor / POWER_BETA;
}
```
unless I'm misunderstanding the code.

**Comment by tokatoka** [comment]
yes thank you!
this was my mistake when I was refactoring this part back in May #599 

it is supposed to be
```
if let Some(strat) = psmeta.strat() {
    if strat != PowerSchedule::EXPLORE {
        if factor > MAX_FACTOR {
            factor = MAX_FACTOR;
        }
        perf_score *= factor / POWER_BETA;
    }
}
```
