### ISSUE TITLE
`clippy.toml` support

### ISSUE THREAD

**Issue by syheliel** [AFLplusplus/LibAFL#690]
There are too many `#[allow(clippy::xxx)]` in code(about 400+). `clippy.toml` allows to apply clippy rules globally. That may help to improve quality of code and doc.

**Comment by domenukk** [comment]
We already specify clippy options for our crates in lib.rs of each crate, see here:
https://github.com/AFLplusplus/LibAFL/blob/d9a0948377d5d41291ba6984a7322f953b81d273/libafl/src/lib.rs#L18
