### ISSUE TITLE
TuiMonitor with SimpleRestartingEventManager breaks the fuzzer

### ISSUE THREAD

**Issue by TeumessianFox** [AFLplusplus/LibAFL#701]
When using the TuiMonitor with the SimpleRestartingEventManager the fuzzer breaks. The TuiMonitor only updates the "run time" and nothing else. Also, the queue only fills up but never gets consumed. No crashes are found even for a dummy example. As the TuiMonitor eats up all the output (related to issue #615) it is hard to find the origin of the bug. 

Quitting the TuiMonitor with 'q', but not stopping the fuzzer with 'Control-C' changes things tho. Suddenly the queue gets consumed and crashes are found. Furthermore, new children are successfully spawned when the qemu fuzzer crashes.

Reproduce:
- Example fuzzer: fuzzbench_qemu
- Replace `SimpleMonitor` with `TuiMonitor`
- Run fuzzer

**Comment by tokatoka** [comment]
> No crashes are found even for a dummy example.

I guess they are found but not updated with the TuiMonitor
On my PC, the tui is also broken but I can see faulty inputs filling out/crashes folder when I check it from another terminal. (but still the UI is broken.. yeah)

**Comment by soumya-78** [comment]
Hello @tokatoka I will try my best to fix it. Please assign this issue to me

**Comment by soumya-78** [comment]
Can you please confirm are there any pr pushed for any of the issue #1084 #609 and #424. As they are marked as good first issue i will try to solve them and add a pr.

**Comment by domenukk** [comment]
Closing this for now, TuiMonitor changed quite a bit
