### ISSUE TITLE
TinyInst Backend

### ISSUE THREAD

**Issue by tokatoka** [AFLplusplus/LibAFL#727]
Integrating TinyInst https://github.com/googleprojectzero/TinyInst into LibAFL would be nice.

I have a semi-working TinyInst `Executor` in a old branch `tinyinst` already. https://github.com/AFLplusplus/LibAFL/tree/tinyinst
but due to the C++ bindings the APIs are super ugly.

**Comment by domenukk** [comment]
What doesn't/didn't work?

**Comment by tokatoka** [comment]
everything worked but the code looks ugly and no observer & feedback yet
