### ISSUE TITLE
Faild to build LibAFL on Windows

### ISSUE THREAD

**Issue by lentikr** [AFLplusplus/LibAFL#740]
I can't build LibAFL on Windows. Has anyone ever encountered such a problem?
```bash
error: failed to run custom build command for `libafl_cc v0.8.1 (C:\fuzz\LibAFL\libafl_cc)`

Caused by:
  process didn't exit successfully: `C:\fuzz\LibAFL\target\release\build\libafl_cc-020b721137e7b3e0\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_CONFIG
  cargo:rerun-if-env-changed=LIBAFL_EDGES_MAP_SIZE
  cargo:rerun-if-env-changed=LIBAFL_ACCOUNTING_MAP_SIZE
  cargo:rerun-if-changed=src/common-llvm.h
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/cmplog-routines-pass.cc
  ["-IC:/msys64/clang64/include", "-std=c++14", "-stdlib=libc++", "-fno-exceptions", "-fno-rtti", "-D_FILE_OFFSET_BITS=64", "-D__STDC_CONSTANT_MACROS", "-D__STDC_FORMAT_MACROS", "-D__STDC_LIMIT_MACROS", "-DLIBAFL_EDGES_MAP_SIZE=65536", "-DLIBAFL_ACCOUNTING_MAP_SIZE=65536", "-DUSE_NEW_PM", "-fuse-ld=lld", "/LD", "/MD"]

  --- stderr
  thread 'main' panicked at 'Failed to compile cmplog-routines-pass.cc', libafl_cc\build.rs:152:33
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

I got llvm14.0.6 and clang14 from msys2 using command like this: `pacman -S mingw-w64-clang-x86_64-toolchain mingw-w64-clang-x86_64-cninja mingw-w64-clang-x86_64-python-six mingw-w64-clang-x86_64-python-pip`

Thanks for help!

**Comment by tokatoka** [comment]
Hi, I think our libafl_cc/build.rs does not support msys2 env for now

**Comment by lentikr** [comment]
> Hi, I think probably our libafl_cc/build.rs does not support msys2 env (and haven't been tested) for now

Thanks for your reply.
But I also tried LLVM [pre-build binaries](https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/LLVM-14.0.6-win64.exe), and it didn't work too. But I forget whether the problem is the same as the above.
Can you tell me how did you deal with the dependencies of LibAFL on Windows?

**Comment by tokatoka** [comment]
that pre-built binary should work if you have visual studio and rust installed. and use cmd.exe or powershell
> whether the problem is the same as the above
could you tell me what the error say

**Comment by lentikr** [comment]
> that pre-built binary should work if you have visual studio and rust installed. and then you can use cmd.exe or powershell to build
> 
> > whether the problem is the same as the above
> 
> could you tell me what the error say

I'll try it then. But I remember the pre-built binary don't provide llvm-config.exe. Is that a serious fault?

**Comment by tokatoka** [comment]
> I'll try it then. But I remember the pre-built binary don't provide llvm-config.exe. 

Exactly, they don't have it.
In case there's no llvm-config found in the system, then libafl_cc does not build the llvm passes. so you can't use llvm pass for instrumentation.

If you want to use llvm passes, then you'll need to build llvm from source. (llvm-config is not enough)
Probably the discussion here is related https://github.com/AFLplusplus/LibAFL/pull/710

**Comment by lentikr** [comment]
> could you tell me what the error say

Strangely enough, at this time, my attempt was successful.

I think the issue could be closed.

And I want to know what does "can't use llvm pass" mean?  Does it mean LibAFL's instrumenting part won't work?

**Comment by tokatoka** [comment]
> Does it mean LibAFL's instrumenting part won't work?
No.
You can't use llvm pass to instrument the program if the llvm passes are simply not built
However you can still use other instrumentation backends, (sancov_pcguard).
This example uses sancov backend and should work
https://github.com/AFLplusplus/LibAFL/tree/main/fuzzers/libfuzzer_stb_image
