### ISSUE TITLE
Executors and observers for non-native targets

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [AFLplusplus/LibAFL#742]
**Is your feature request related to a problem? Please describe.**
Currently, libafl only supports native targets. There are many targets which are not native, e.g. JavaScript, Python, Java, etc. targets, which can benefit from many of the existing observers, feedbacks, and other features present in libafl. Additionally, such support would allow us to unify efforts for different fuzzing domains.

**Describe the solution you'd like**
Executors and observers for various interpreted languages, e.g., libafl_v8, libafl_openjdk, libafl_pyo3, etc.

**Describe alternatives you've considered**
There are many existing fuzzers for interpreted/VM targets.
- JavaScript has [jsfuzz] and more recently [jazzer.js]
- Java has [javafuzz] and [jazzer]
- Python has [pythonfuzz] and [atheris]

Again, while these alternatives are present, it doesn't allow us the same extensibility or code reuse as libafl.

**Additional context**
In future work, we may be able to leverage such tools in greater contexts, e.g. libafl_v8 to find XSS bugs in various frontend JS libraries by integrating with Google Chrome and using something similar to the recent [ExecSan] work.

[jsfuzz]: https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/jsfuzz
[jazzer.js]: https://github.com/CodeIntelligenceTesting/jazzer.js
[javafuzz]: https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/javafuzz
[jazzer]: https://github.com/CodeIntelligenceTesting/jazzer
[pythonfuzz]: https://gitlab.com/gitlab-org/security-products/analyzers/fuzzers/pythonfuzz
[atheris]: https://github.com/google/atheris
[ExecSan]: https://github.com/google/oss-fuzz/tree/master/infra/experimental/sanitizers/ExecSan

**Comment by VTCAKAVSMoACE** [comment]
Oh, and obviously I'm interested in working on this. :) I wanted to see what the libafl team's response would be before getting started. I'll make individual issues with tasks for each interpreted executor/observer.

**Comment by domenukk** [comment]
Take a look at libafl_atheris which can fuzz python:
https://github.com/AFLplusplus/LibAFL/tree/main/fuzzers/libafl_atheris

**Comment by domenukk** [comment]
(but obviously it's awesome if you want to work on this ;) )

**Comment by VTCAKAVSMoACE** [comment]
> You can also take a look at libafl_atheris which can fuzz python: https://github.com/AFLplusplus/LibAFL/tree/main/fuzzers/libafl_atheris

Oops! I didn't grok that that was already present, despite looking at it multiple times :facepalm: Getting it as its own executor would still be nice. :)

**Comment by domenukk** [comment]
We got some more executors now, like #864 #966 and #744 so closing for now
