### ISSUE TITLE
frida-asan: Add error analysis results to saved metadata

### ISSUE THREAD

**Issue by s1341** [AFLplusplus/LibAFL#76]
At the moment, we only save the raw `AsanErrors` in the metadata written to disk. 

In the `report_error` method, we do a lot of analysis of the error. The results of that analysis should also be included in the output metadata, including:
- [ ] original PC/IP
- [ ] disassembly around error
- [ ] type of error
- [ ] allocation offset

**Comment by domenukk** [comment]
Would be nice to have, but I don't think anybody will be working on this any time soon. Closing for now.
