### ISSUE TITLE
error: failed to run custom build command for `libafl_cc v0.8.1...

### ISSUE THREAD

**Issue by mzs555557** [AFLplusplus/LibAFL#764]
error: failed to run custom build command for `libafl_cc v0.8.1 (/home/mzs/Desktop/LibAFL/libafl_cc)`

Caused by:
  process didn't exit successfully: `/home/mzs/Desktop/LibAFL/target/release/build/libafl_cc-98f89a4aa2e59958/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_CONFIG
  cargo:rerun-if-env-changed=LIBAFL_EDGES_MAP_SIZE
  cargo:rerun-if-env-changed=LIBAFL_ACCOUNTING_MAP_SIZE
  cargo:rerun-if-changed=src/common-llvm.h
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=src/cmplog-routines-pass.cc

  --- stderr
  thread 'main' panicked at 'Failed to compile cmplog-routines-pass.cc', libafl_cc/build.rs:135:33
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

when i run `cargo build --release`, I have this problem, how can I fix it?:(

**Comment by domenukk** [comment]
Which version of llvm do you have installed?

**Comment by mzs555557** [comment]
i run `sudo apt-get purge llvm` and solve it, this may be my llvm version conflict, thank you :), i will close this issue
