### ISSUE TITLE
Question about in process fuzzing.

### ISSUE THREAD

**Issue by dgh05t** [AFLplusplus/LibAFL#772]
Hello, 

Is there a way that I can use LibAFL to fuzz some close sourced program on Windows.

For example, I only know the function address of a close sourced module, is there a way I can call this function repeatly in process (attach to it , and mutate arguments ) and perform like a normal fuzzing process?

Thank you !

**Comment by tokatoka** [comment]
you can use the libafl_frida but currently you need target compiled as a dll to fuzz

**Comment by tokatoka** [comment]
for example like this https://github.com/AFLplusplus/LibAFL/tree/main/fuzzers/frida_libpng
you need to make your harness and compile them into harness.dll and then fuzz it

**Comment by domenukk** [comment]
Technically an exe is a dll too, you should be able to fuzz that directly, right? Still will need reverse engineering for harnessing (to figure out the important locations, how to initialise it properly, and how to call it).

**Comment by dgh05t** [comment]
Thank you for the quick replying.

The biggest problem for me is that it's hard to generate a harness correctly, because there's too many function calls and global properties need to be initialized, but if I run the .exe program directly, these things will be initialized by the closed sourced main module, so if I can find a way attach to the existing process and just call the target function repeatly, things will be much easier :)

**Comment by dgh05t** [comment]
OK, I'll take a look, thanks :)
