### ISSUE TITLE
Any suggestions for fuzzing the interface with multi-arguments?

### ISSUE THREAD

**Issue by icepng** [AFLplusplus/LibAFL#805]
I want to fuzz an interface like `target_func(char*, char*, char*)`. Any suggestions for splitting the `in-process fuzz data` into three arguments?  
```
harness_function(char* data, usize len) {
      char* a1 = from data;
      char* a2 = from data; 
      char* a3 = from data;


      target_func(a1, a2, a3);
}
```

**Comment by domenukk** [comment]
I'm a big fan of the arbitrary crate in rust (https://docs.rs/arbitrary/latest/arbitrary/), it generates a struct from a byte array and should be able to generate byte buffers in your harness.
You can also do it manually (i.e., the first byte indicates a split ratio, or something)
Or you can use a custom input, for example an input with four byteinputs, and Multiplex the mutators, or a grammar input like nautilus

**Comment by icepng** [comment]
Very useful, thank you very much.
