### ISSUE TITLE
b2b thread loop traps into infinite idle loop when peer has closed

### ISSUE THREAD

**Issue by xiaohuajiao** [AFLplusplus/LibAFL#850]
**Describe the bug**
In `b2b` mode, brokers on both side will create a new thread via `b2b_thread_on` and use `TCPStream` to communicate.

In each round of b2b thread main loop, it sends all local broadcast msg to peer side and use `recv_tcp_msg` to read remote msg. [https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/bolts/llmp.rs#L2137-#L2156](https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/bolts/llmp.rs#L2137).

However, when `recv_tcp_msg`, thread does not process error, instead using `if let Ok(val) = recv_tcp_msg(&mut stream)` to check if it's ok for this behavior. 

When peer broker quit, this b2b link (TCP link) is no longer existed. In this case, the thread should quit to end this b2b link, instead trapping into an infinite loop. More detaileded, it will print following warning infinitely. (with `llmp_debug` enable).

```
Received no input, timeout or closed. Looping back up :)
Received no input, timeout or closed. Looping back up :)
...
```

The error returned by `recv_tcp_msg` is `File(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }, ErrorBacktrace)`

**To Reproduce**
1. create a broker `B1` listened on Port `P1`
2. create another broker `B2` listened on Port `P2`, also with a remote b2b port to `P1`
3. stop `B2`
4. view `B1` bug behaviors.

**Expected behavior**
`B1` should use errors returned by stream to detect that `B2` has ended, and this b2b thread in `B1` may also need to end, since this b2b link is not existing anymore.

**Screen output/Screenshots**
<img width="772" alt="image" src="https://user-images.githubusercontent.com/3733728/197131599-bcd87933-a9f9-4eb2-b065-0e142ac075de.png">

> Add some debug prints in img for showing the error info

**Comment by domenukk** [comment]
Nice catch! We should probably also make sure to clean up the llmp out pages and announce to the broker we're no longer available (likely needs a new LLMP message)

**Comment by domenukk** [comment]
https://github.com/AFLplusplus/LibAFL/blob/main/libafl/src/bolts/llmp.rs#L2119

This line also crashes, we should not `expect` here
