### ISSUE TITLE
Check for casts from immutable references to mutable pointers

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#895]
In libafl there should be few casts between immutable refs to immutable pointers and then to mutable pointers.
While it is now ok, with the evolution of the Rust compiler this will be UB as the compiler will be able to optimize the code under the assumption that the pointed memory under an immutable ref is immutable.

In the long term, we should replace these code points with valid alternatives.

**Comment by domenukk** [comment]
Even Casting a mut reference to a mut ptr is potentially UB, if the mut reference is still read from, after we write to the mut ptr

**Comment by domenukk** [comment]
Is this actionable at the moment, do you have an example for such a thing? Else I'd close this

**Comment by domenukk** [comment]
Closing for now, we should open bugs for individual ocurrences / fix them
