### ISSUE TITLE
`__libafl_targets_cmplog_routines` interface

### ISSUE THREAD

**Issue by waderwu** [AFLplusplus/LibAFL#903]
Why only `__libafl_targets_cmplog_instructions` interface is provided without `__libafl_targets_cmplog_routines` interface

**Comment by tokatoka** [comment]
because we use __libafl_targets_cmplog_instructions from other crates like libafl_qemu so we want the pub api. (?)
you can expose `__libafl_targets_cmplog_routines ` in libafl_targets too if you need it
