### ISSUE TITLE
Directory hierarchy refactor

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#909]
As the number of crates is increasing (libafl_tinyinst soon) and the examples can be not just fuzzers but for instance symcc runtimes, analysis built on top of libafl_qemu not just for fuzzing or corpus minimizer we need a different directory structure.

Now it is the time, before 1.0, otherwise it will be a too much breaking change in the future.

My proposal is something like

- framework/
  * libafl
  * libafl_qemu
  * bindings/
  * ...
- frontends/
  * fuzzers/
  * runtimes/
  * minimizers/
  * ...
- utils/
- scripts/
- Cargo.toml with a single workspace when possible (the CI time will be reduced)

**Comment by domenukk** [comment]
Do we still want this?
