### ISSUE TITLE
AttributeError: module 'libafl' has no attribute 'MapFeedbackStateI32'

### ISSUE THREAD

**Issue by cokeBeer** [AFLplusplus/LibAFL#911]
**Describe the bug**
failed to run baby_fuzzer.py in /fuzzer/baby_fuzzer

**To Reproduce**
1. run baby_fuzzer.py in /fuzzer/baby_fuzzer

**Expected behavior**
success

**Screen output/Screenshots**
<img width="779" alt="image" src="https://user-images.githubusercontent.com/70683161/203743914-4d26b725-af5c-4803-b487-45b4cf94284c.png">

**Comment by tokatoka** [comment]
We removed feedbackstate a while ago, but have not updated that baby_fuzzer's code yet
https://github.com/AFLplusplus/LibAFL/pull/627

**Comment by domenukk** [comment]
How is this not built in CI?

**Comment by domenukk** [comment]
Ah it's python, guess we need CI that runs it

**Comment by tokatoka** [comment]
yes, it cannot detect the error unless it is run

**Comment by domenukk** [comment]
CC @andreafioraldi

**Comment by domenukk** [comment]
Fixed with #1016, thanks for reporting :)
Sorry for the delay.
