### ISSUE TITLE
some bugs in libafl_qemu i386

### ISSUE THREAD

**Issue by Handchongboy** [AFLplusplus/LibAFL#918]
I just try to follow the [Hacking TMNF - Fuzzing the game server](https://blog.bricked.tech/posts/tmnf/part1/) tutorial, i git clone it's source code and then run ```CROSS_CC="gcc" cargo run```, finally i got some errors.

**To Reproduce**
1. write ```libafl_qemu = { path = "../LibAFL/libafl_qemu/", features = ["i386", "usermode"] }``` in Cargo.toml (but there are no problem with "x86_64" )

**Expected behavior**
```cargo run ``` executed successfully

**Screen output/Screenshots**
![图片](https://user-images.githubusercontent.com/119218171/204147944-1b1d0228-c977-45c8-b6b4-a37b1fefb5c7.png)

**Additional context**
I spend some time auditing code, i found two problems:
1. in ```libafl_qemu/src/snapshot.rs: line 21```, use SYS_newfstatat, but i386 arch do not have syscall SYS_newfstatat
2. in ```libafl_qemu/src/block.rs: line 46```, the absence of cpu_target="i386" condition lead to cs not found in this scope error

these bug looks strange, i'm not sure if LibAFL_qemu not support i386 arch anymore or just forget consider this situation when coding.

**Comment by tokatoka** [comment]
Thanks for reporting #924 should fix this
