### ISSUE TITLE
Unable to build "make distrib" on Arch Linux. Error: "PROGRAM ABORT: GCC and plugin have incompatible versions, expected GCC 12.1.0, is 12.2.0"

### ISSUE THREAD

**Issue by nicholicaron** [AFLplusplus/LibAFL#943]
Location: plugin_init(), instrumentation/afl-gcc-pass.so.cc:479

I have attempted to downgrade GCC and GCC-libs to 12.1.0 using the Arch Linux Archives. Once I try to make once more, I receive a similar error message saying **"expected GCC 12.1.0, is 12.1.0"**. Is there a way to tell the makefile to build with Clang/LLVM instead? Unsure if this is issue-worthy, but a more experienced opinion would be helpful.

**Comment by andreafioraldi** [comment]
1) this is the wrong repo, not afl++
2) this seems an error in your setup and/or in the arch linux packaging of gcc-dev
