### ISSUE TITLE
no AsanBacktraceObserver  in observers

### ISSUE THREAD

**Issue by cokeBeer** [AFLplusplus/LibAFL#971]
**Describe the bug**
no AsanBacktraceObserver  in observers

**To Reproduce**
1. copy code from fuzzers/backtrace_baby_fuzzers/forkserver_executor/src/main.rs
2. cargo run

**Expected behavior**
success

**Screen output/Screenshots**
<img width="626" alt="image" src="https://user-images.githubusercontent.com/70683161/209360351-a336ba9d-d604-402e-bfa0-fdfbbdcec704.png">

**Additional context**
Seems there is an ASANBacktraceObserver

**Comment by domenukk** [comment]
Probably a merge fail, it should be Asan or ASan für both. Interesting that it didn't come up in CI

**Comment by domenukk** [comment]
Where did you find the reference about `ASANBacktraceObserver`? Seems like you looked at an older version of the file

**Comment by cokeBeer** [comment]
The error information told me that there is an ASANBacktraceObserver.
I tried to import it in my IDE.
It can be found in libafl-0.8.2/src/observers/stacktrace.rs. 
Looks like the ASANBacktraceObserver has became AsanBacktraceObserver in master branch but does not change in package.

**Comment by domenukk** [comment]
Yes you can either use the 0.8.2 tag, or you have to use the current main branch in your Cargo.toml.

You can do something like
```toml
libafl = { git = "https://github.com/AFLplusplus/LibAFL.git", rev = "7ed1ac9" }
```

**Comment by domenukk** [comment]
We will release 0.9 soon, then the API is correct again
