### ISSUE TITLE
Fuzzers jobs panic silently on the CI

### ISSUE THREAD

**Issue by ergrelet** [AFLplusplus/LibAFL#974]
**Describe the bug**

Both 'fuzzers' jobs seem to panic in the "Build and run example fuzzers" step on the `main` branch, without making the jobs fail.
It seems related to cargo's workspace inheritance feature.

**Expected behavior**

1. Jobs should fail if they're expected to be able to run the fuzzers properly.
2. Jobs should eventually be fixed to avoid failing.

**Screen output/Screenshots**

Here are examples:
* Ubuntu: https://github.com/AFLplusplus/LibAFL/actions/runs/3780662237/jobs/6426940307
```
     Running `target/debug/build_and_test_fuzzers remotes/origin/main 'HEAD^'`
thread 'main' panicked at 'cannot read manifest: WorkspaceIntegrity("This manifest requires workspace inheritance, but `inherit_workspace` hasn't been called yet")', utils/build_and_test_fuzzers/src/diffing.rs:66:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

* macOS: https://github.com/AFLplusplus/LibAFL/actions/runs/3780662237/jobs/6426940362`
```
     Running `target/debug/build_and_test_fuzzers remotes/origin/main 'HEAD^'`
thread 'main' panicked at 'cannot read manifest: WorkspaceIntegrity("This manifest requires workspace inheritance, but `inherit_workspace` hasn't been called yet")', utils/build_and_test_fuzzers/src/diffing.rs:66:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
./scripts/test_all_fuzzers.sh: line 41: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
declare -A not avaliable, please update your bash version to 4
```

**Comment by domenukk** [comment]
@andreafioraldi can you take a look?

**Comment by tokatoka** [comment]
we can simply delete https://github.com/AFLplusplus/LibAFL/blob/main/scripts/test_all_fuzzers.sh#L41
this declare -A line. if it causes a problem on macos

for the diffing.rs's error, I can't reproduce it

**Comment by tokatoka** [comment]
it works until this commit https://github.com/AFLplusplus/LibAFL/commit/75f12bd0eb3ffffc67f8a12d3837b8b0ef369dd6
and it's broken from this commit https://github.com/AFLplusplus/LibAFL/commit/476cb7e7dcd424992041dc058483e551486d01d7
but I don't know what causes it

**Comment by tokatoka** [comment]
updated the dependency in #976 and it should be fixed
