### ISSUE TITLE
Memory leak in qemu_fullsystem mode

### ISSUE THREAD

**Issue by elbiazo** [AFLplusplus/LibAFL#991]
**IMPORTANT**
1. You have verified that the issue to be present in the current `main` branch

Thank you for making LibAFL better!

**Describe the bug**
it looks like qemu fullsystem mode does not let go of memory maxing out ram usage.

**To Reproduce**
1. run qemu_fullsystem example from fuzzer directory
2. wait few minutes.

**Expected behavior**
It does not use all of my memory.

**Screen output/Screenshots**
If applicable, add copy-paste of the screen output or screenshot that shows the issue. Please ensure the output is in **English** and not in Chinese, Russian, German, etc.
![Screenshot from 2023-01-06 13-20-39](https://user-images.githubusercontent.com/23147879/211103012-364fe0be-e33b-423d-8a9c-969fdaad6307.png)
![Screenshot from 2023-01-06 13-21-09](https://user-images.githubusercontent.com/23147879/211103014-33a4578b-5a84-4e0a-9829-973fb8c78210.png)

**Comment by andreafioraldi** [comment]
Hey @elbiazo can you try to reproduce removing the snapshot functions in the fuzzer and using restore_state? The code is commented under OPTION 1 in the harness, I suspect that the memory leak is related to the devices snapshot

**Comment by andreafioraldi** [comment]
uncomment this 

```
        let saved_cpu_states: Vec<_> = (0..emu.num_cpus())
            .map(|i| emu.cpu_from_index(i).save_state())
            .collect();
```
and

```
                 for (i, s) in saved_cpu_states.iter().enumerate() {
                     emu.cpu_from_index(i).restore_state(s);
                 }
```

and remove the emu.create_fast_snapshot and emu.restore_fast_snapshot

**Comment by elbiazo** [comment]
> uncomment this
> 
> ```
>         let saved_cpu_states: Vec<_> = (0..emu.num_cpus())
>             .map(|i| emu.cpu_from_index(i).save_state())
>             .collect();
> ```
> 
> and
> 
> ```
>                  for (i, s) in saved_cpu_states.iter().enumerate() {
>                      emu.cpu_from_index(i).restore_state(s);
>                  }
> ```
> 
> and remove the emu.create_fast_snapshot and emu.restore_fast_snapshot

I have tried option 1 and option 2. It seems like this is related to the new fast snapshot only.

**Comment by andreafioraldi** [comment]
Thanks, this restricts the scope a lot, probably it is the dirty pages tracking

**Comment by andreafioraldi** [comment]
https://github.com/AFLplusplus/LibAFL/pull/998
