### ISSUE TITLE
Some scheduler does not have unique on_replace method implemented.

### ISSUE THREAD

**Issue by andreafioraldi** [AFLplusplus/LibAFL#994]
Some scheduler (ProbabilitySamplingScheduler, CoverageAccountingScheduler ,PowerQueueScheduler ) does not have unique on_replace method implemented. So I'd say they are not ready for replacing corpus entries.
(well, it is also difficult to implement these, because like I said in the above comment, maybe we want to cancel the effect of the leaving testcase to the global metadata to make it 100% intended, but maybe that is not as simple as it seems)

Maybe we want a trait like `HasReplace`, only then it is clear on_replace or on_remove behaves right

_Originally posted by @tokatoka in https://github.com/AFLplusplus/LibAFL/issues/947#issuecomment-1373525904_

**Comment by tokatoka** [comment]
on_replace added to power scheduler
https://github.com/AFLplusplus/LibAFL/pull/1067

I think on_replace & on_remove should be separated into another trait from `trait Scheduler`
